### PR TITLE
multiple market fixes

### LINKED ISSUE #9317: Cards (greetings, thank you, etc) should not have multiple Batch Buying (also gear, Backgrounds, Mystery Item sets, Rebirth, Fortify, Armoire)
Currently, when you buy a card to give to a party member, you're asked how many you want to buy.

That option shouldn't be available for cards because as soon as you've bought a card, you have to select the party member to give it to. It only makes sense to buy one card at a time.

For reference for new contributors, these are the cards that this issue refers to:
image

### LINKED ISSUE #9401: Confirmation Step for Gem/Hourglass Purchases
There should be a confirmation step when you buy anything with gems or hourglasses, such as the one that pops up when you buy backgrounds.

### PR DESCRIPTION
**Pull request by negue**
- fixes https://github.com/HabitRPG/habitica/issues/9401 confirmation of gem / hourglass purchases
- fixes https://github.com/HabitRPG/habitica/issues/9317 disable the amount selection on purchasing `gear`, `backgrounds`, `mystery sets`, `cards`, `special potions` and  `armoire`

other fixes:
- fix mystery set previews
- users can now send cards to themselves
- fix filter reset on (un)pinning market items

### CODE REVIEW

File: website/client/components/shops/market/index.vue [hunk 1]
```diff
@@ -532,9 +532,11 @@ export default {
           }
 
           categories.map((category) => {
-            this.$set(this.viewOptions, category.identifier, {
-              selected: true,
-            });
+            if (!this.viewOptions[category.identifier]) {
```
Comment (paglias) [inline website/client/components/shops/market/index.vue]: why this change?

Comment (paglias) [inline website/client/components/shops/market/index.vue:505]: why this change?

File: website/client/components/shops/buyModal.vue [hunk 2]
```diff
@@ -285,6 +285,11 @@
 
   import moment from 'moment';
 
+  const hideAmountSelectionForPurchaseTypes = [
```
Comment (paglias) [inline website/client/components/shops/buyModal.vue:288]: I think @TheHollidayInn implemented a partial fix for this here https://github.com/HabitRPG/habitica/pull/9519/commits/8664243ca9e35f22289187a848b375a03d016a53#diff-b66c19ca9da748e74190b22776c587b7L45, this fix seems broader but you'll want to remove his code when this is merged

**Review by paglias — DISMISSED** [review]

File: website/client/components/shops/market/index.vue (hunk 1 above)
Comment (negue) [reply website/client/components/shops/market/index.vue:505]: on pinning items the store data refreshes, including the `market.categories` which then refreshes the `categories`, this fix is to prevent the viewOptions to be reseted on that refresh (if you already unchecked one of the filters)

**Comment by paglias** [comment]
Can you fix the conflicts here? Also, I'm supposing this is ready, right?

**Comment by negue** [comment]
yep, fixed the conflicts, its ready to merge
