### PR TITLE
Fix for search guilds result being inconsistent between "My Guilds" and "Discover Guilds"

### LINKED ISSUE #11860: Searching guilds is inconsistent between "My Guilds" and "Discover Guilds"
Reported by loremi:

> Hi, thank you for looking into the "CAD Cads" guild not being found under "3D" issue! Just as a follow-up: the guild leader has now included the word "3D" in both the summary and description, and the guild is now searchable under "Discover Guilds" :) This solved the problem, I just wanted to point to what's possibly a quirk for completion's sake: When searching for "3D" under "My Guilds", the guild still won't show up in the results. 

Confirmed by me in Firefox using that guild/keyword.

### PR DESCRIPTION
**Pull request by tsukimi2**
Fixes #11860

Fixes the problem of search guilds result being inconsistent between "My Guilds" and "Discover Guilds" by adding search term matching against guild summary and description.

The added code seems to be working properly under manual testing.

One question though.  I was trying to add some unit tests against the added code under the file tests/unit/mxins/groupsUtilities.spec.js.  However, when I run the "npm run test:api:unit", it stops at the following due to error from other parts of the unit tests and so the unit test I wrote did not seem to get to run:

bugfix

How should I make it so that the unit tests I would like to write can run? Thanks.

### CODE REVIEW

**Comment by paglias** [comment]
Hi @tsukimi2 from the screenshot you posted looks like you were running the server side API unit tests instead of the client side ones that can be run with `npm run client:unit`, you can also see the output here https://github.com/HabitRPG/habitica/pull/11903/checks?check_run_id=464584079

**Comment by paglias** [comment]
About the API unit tests failing, could you post the entire terminal output?

**Comment by tsukimi2** [comment]
> About the API unit tests failing, could you post the entire terminal output?

osiris@osiris-LIFEBOOK-SH572:~$ cd habitica/
osiris@osiris-LIFEBOOK-SH572:~/habitica$ git branch
* bugfix-search-guilds
  develop
  member-list-update
osiris@osiris-LIFEBOOK-SH572:~/habitica$ npm run test:api:unit

> habitica@4.134.2 test:api:unit /home/osiris/habitica
> gulp test:api:unit

[20:34:47] Using gulpfile ~/habitica/gulpfile.js
[20:34:47] Starting 'test:api:unit'...


(node:16903) DeprecationWarning: current URL string parser is deprecated, and will be removed in a future version. To use the new parser, pass option { useNewUrlParser: true } to MongoClient.connect.
(node:16903) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
(node:16903) DeprecationWarning: collection.count is deprecated, and will be removed in a future version. Use Collection.countDocuments or Collection.estimatedDocumentCount instead
  analyticsService
    #track
      Amplitude
        ✓ calls out to amplitude
        ✓ uses a dummy user id if none is provided
        ✓ sends details about event
        ✓ sends english item name for gear if itemKey is provided
        ✓ sends english item name for egg if itemKey is provided
        ✓ sends english item name for food if itemKey is provided
        ✓ sends english item name for hatching potion if itemKey is provided
        ✓ sends english item name for quest if itemKey is provided
        ✓ sends english item name for purchased spell if itemKey is provided
        ✓ sends user data if provided
        platform
          ✓ logs web platform
          ✓ logs iOS platform
          ✓ logs Android platform
          ✓ logs 3rd Party platform
          ✓ logs unknown if headers are not passed in
        Operating System
          ✓ sets default (44ms)
          ✓ sets iOS
          ✓ sets Android
          ✓ sets Unknown if headers are not passed in
      GA
        ✓ calls out to GA
        ✓ sends details about event
    #trackPurchase
      Amplitude
        ✓ calls out to amplitude
        ✓ uses a dummy user id if none is provided
        ✓ sends details about purchase
        ✓ sends user data if provided
        platform
          ✓ logs web platform
          ✓ logs iOS platform
          ✓ logs Android platform
          ✓ logs 3rd Party platform
          ✓ logs unknown if headers are not passed in
        Operating System
          ✓ sets default
          ✓ sets iOS
          ✓ sets Android
          ✓ sets Unknown if headers are not passed in
      GA
        ✓ calls out to GA
        ✓ sends details about purchase
    mockAnalyticsService
      ✓ has stubbed track method
      ✓ has stubbed trackPurchase method

  API Messages
    ✓ returns an API message
    ✓ throws if the API message does not exist
    ✓ clones the passed variables
    ✓ pass the message through _.template

  Base model plugin
    ✓ throws if "typeKey" is not set to $type
    ✓ adds a _id field to the schema
    ✓ can add timestamps fields
    ✓ can sanitize input objects
    ✓ accepts an array of additional fields to sanitize at runtime
    ✓ can make fields private
    ✓ accepts a further transform function for toJSON
    ✓ accepts a transform function for sanitize

  Collection Manipulators
    removeFromArray
      ✓ removes element from array
      ✓ removes object from array
      ✓ does not change array if value is not found
      ✓ returns the removed element
      ✓ returns the removed object element
      ✓ returns false if item is not found
      ✓ persists removal of element when mongoose document is saved (252ms)

  cron
    ✓ updates user.preferences.timezoneOffsetAtLastCron
    ✓ resets user.items.lastDrop.count
    ✓ increments user cron count
    ✓ calls analytics
    ✓ calls analytics when user is sleeping
    end of the month perks
      ✓ awards current mystery items to subscriber (40ms)
      ✓ awards multiple mystery item sets if user skipped months between logins (55ms)
      ✓ resets plan.gemsBought on a new month
      ✓ resets plan.gemsBought on a new month if user does not have purchased.plan.dateUpdated
      ✓ does not reset plan.gemsBought within the month
      ✓ resets plan.dateUpdated on a new month
      ✓ increments plan.consecutive.count
      ✓ increments plan.consecutive.count by more than 1 if user skipped months between logins (61ms)
      ✓ decrements plan.consecutive.offset when offset is greater than 0
      ✓ does not award unearned plan.consecutive.trinkets if subscription ended during an absence
      ✓ does not increment plan.consecutive.gemCapExtra when user has reached the gemCap limit
      ✓ does not reset plan stats if we are before the last day of the cancelled month
      ✓ does reset plan stats if we are after the last day of the cancelled month
      for a 1-month recurring subscription
Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 0
Error: 
    at Moment.zone (/home/osiris/habitica/node_modules/moment/moment.js:320:98)
    at Context.<anonymous> (/home/osiris/habitica/test/api/unit/libs/cron.test.js:243:46)
    at callFn (/home/osiris/habitica/node_modules/mocha/lib/runnable.js:372:21)
    at Test.Runnable.run (/home/osiris/habitica/node_modules/mocha/lib/runnable.js:364:7)
    at Runner.runTest (/home/osiris/habitica/node_modules/mocha/lib/runner.js:455:10)
    at /home/osiris/habitica/node_modules/mocha/lib/runner.js:573:12
    at next (/home/osiris/habitica/node_modules/mocha/lib/runner.js:369:14)
    at /home/osiris/habitica/node_modules/mocha/lib/runner.js:379:7
    at next (/home/osiris/habitica/node_modules/mocha/lib/runner.js:303:14)
    at Immediate._onImmediate (/home/osiris/habitica/node_modules/mocha/lib/runner.js:347:5)
    at processImmediate (internal/timers.js:456:21)
    at process.topLevelDomainCallback (domain.js:137:15)
        ✓ does not increment consecutive benefits after the first month (77ms)
        ✓ does not increment consecutive benefits after the second month
        ✓ increments consecutive benefits after the third month
        ✓ does not increment consecutive benefits after the fourth month
        ✓ increments consecutive benefits correctly if user has been absent with continuous subscription (86ms)
      for a 3-month recurring subscription
        ✓ does not increment consecutive benefits in the first month of the first paid period that they already have benefits for
        ✓ does not increment consecutive benefits in the middle of the period that they already have benefits for
        ✓ does not increment consecutive benefits in the final month of the period that they already have benefits for
        ✓ increments consecutive benefits the month after the second paid period has started
        ✓ does not increment consecutive benefits in the second month of the second period that they already have benefits for
        ✓ does not increment consecutive benefits in the final month of the second period that they already have benefits for
        ✓ increments consecutive benefits the month after the third paid period has started
        ✓ increments consecutive benefits correctly if user has been absent with continuous subscription (47ms)
      for a 6-month recurring subscription
        ✓ does not increment consecutive benefits in the first month of the first paid period that they already have benefits for
        ✓ does not increment consecutive benefits in the final month of the period that they already have benefits for (80ms)
        ✓ increments consecutive benefits the month after the second paid period has started
        ✓ increments consecutive benefits the month after the third paid period has started (75ms)
        ✓ increments consecutive benefits correctly if user has been absent with continuous subscription (76ms)
      for a 12-month recurring subscription
        ✓ does not increment consecutive benefits in the first month of the first paid period that they already have benefits for
        ✓ does not increment consecutive benefits in the final month of the period that they already have benefits for (116ms)
        ✓ increments consecutive benefits the month after the second paid period has started
        ✓ increments consecutive benefits the month after the third paid period has started (125ms)
        ✓ increments consecutive benefits correctly if user has been absent with continuous subscription (141ms)
      for a 3-month gift subscription (non-recurring)
        ✓ does not increment consecutive benefits in the first month of the gift subscription
        ✓ does not increment consecutive benefits in the second month of the gift subscription
        ✓ does not increment consecutive benefits in the third month of the gift subscription
        ✓ does not increment consecutive benefits in the month after the gift subscription has ended
      for a 6-month recurring subscription where the user has incorrect consecutive month data from prior bugs
        ✓ increments consecutive benefits in the first month since the fix for #4819 goes live
        ✓ does not increment consecutive benefits in the second month after the fix goes live
        ✓ does not increment consecutive benefits in the third month after the fix goes live
        ✓ increments consecutive benefits in the seventh month after the fix goes live (53ms)
    end of the month perks when user is not subscribed
      ✓ resets plan.gemsBought on a new month
      ✓ does not reset plan.gemsBought within the month
      ✓ does not reset plan.dateUpdated on a new month
      ✓ does not increment plan.consecutive.count
      ✓ does not decrement plan.consecutive.offset when offset is greater than 0
      ✓ does not increment plan.consecutive.trinkets when user has reached a month that is a multiple of 3
      ✓ does not increment plan.consecutive.gemCapExtra when user has reached a month that is a multiple of 3
      ✓ does not increment plan.consecutive.gemCapExtra when user has reached the gemCap limit
      ✓ does nothing to plan stats if we are before the last day of the cancelled month
      - does nothing to plan stats when we are after the last day of the cancelled month
    todos
      ✓ should make uncompleted todos redder
      ✓ should add history of completed todos to user history
      ✓ should remove completed todos from users taskOrder list
      ✓ should preserve todos order in task list
    dailys
      ✓ computes isDue
      ✓ computes isDue when user is sleeping
      ✓ computes nextDue
      ✓ should add history
      ✓ should set tasks completed to false
      ✓ should set tasks completed to false when user is sleeping
      ✓ should reset task checklist for completed dailys
      ✓ should reset task checklist for completed dailys when user is sleeping
      ✓ should reset task checklist for dailys with scheduled misses
      ✓ should do damage for missing a daily
      ✓ should not do damage for missing a daily when user is sleeping
      ✓ should not do damage for missing a daily when CRON_SAFE_MODE is set (179ms)
      ✓ should not do damage for missing a daily if user stealth buff is greater than or equal to days missed
      ✓ should do less damage for missing a daily with partial completion
      ✓ should decrement quest.progress.down for missing a daily
      ✓ should not decrement quest.progress.down for missing a daily when user is sleeping
      ✓ should do damage for only yesterday's dailies
    habits
      ✓ should decrement only up value
      ✓ should decrement only down value
      ✓ should do nothing to habits with both up and down
      counters
        ✓ should reset a daily habit counter each day
        ✓ should reset habit counters even if user is sleeping
        ✓ should reset a weekly habit counter each Monday
        ✓ should reset a weekly habit counter with custom daily start (38ms)
        ✓ should not reset a weekly habit counter when server tz is Monday but user's tz is Tuesday
        ✓ should reset a weekly habit counter when server tz is Sunday but user's tz is Monday
        ✓ should not reset a weekly habit counter when server tz is Monday but user's tz is Sunday
        ✓ should reset a monthly habit counter the first day of each month
        ✓ should reset a monthly habit counter when server tz is last day of month but user tz is first day of the month
        ✓ should not reset a monthly habit counter when server tz is first day of month but user tz is 2nd day of the month
    perfect day
      ✓ stores a new entry in user.history.exp
      ✓ increments perfect day achievement if all (at least 1) due dailies were completed
      ✓ does not increment perfect day achievement if no due dailies
      ✓ gives perfect day buff if all (at least 1) due dailies were completed
      ✓ gives perfect day buff if all (at least 1) due dailies were completed when user is sleeping
      ✓ clears buffs if user does not have a perfect day (no due dailys)
      ✓ clears buffs if user does not have a perfect day (no due dailys) when user is sleeping
      ✓ clears buffs if user does not have a perfect day (at least one due daily not completed)
      ✓ clears buffs if user does not have a perfect day (at least one due daily not completed) when user is sleeping
      ✓ always grants a perfect day buff when CRON_SAFE_MODE is set (262ms)
      ✓ always grants a perfect day buff when CRON_SAFE_MODE is set when user is sleeping (199ms)
    adding mp
      ✓ should add mp to user
      ✓ should not add mp to user when user is sleeping
      ✓ set user's mp to statsComputed.maxMP when user.stats.mp is greater
    quest progress
      ✓ resets user progress
      ✓ applies the user progress
    notifications
      ✓ adds a user notification
      ✓ condenses multiple notifications into one
    login incentives
      ✓ increments incentive counter each cron
      ✓ pushes a notification of the day's incentive each cron
      ✓ replaces previous notifications (47ms)
      ✓ increments loginIncentives by 1 even if days are skipped in between
      ✓ increments loginIncentives by 1 even if user is sleeping
      ✓ awards user bard robes if login incentive is 1
      ✓ awards user incentive backgrounds if login incentive is 2
      ✓ awards user Bard Hat if login incentive is 3
      ✓ awards user RoyalPurple Hatching Potion if login incentive is 4
      ✓ awards user a Chocolate, Meat and Pink Contton Candy if login incentive is 5
      ✓ awards user moon quest if login incentive is 7
      ✓ awards user RoyalPurple Hatching Potion if login incentive is 10
      ✓ awards user a Strawberry, Patato and Blue Contton Candy if login incentive is 14
      ✓ awards user a bard instrument if login incentive is 18
      ✓ awards user second moon quest if login incentive is 22
      ✓ awards user a RoyalPurple hatching potion if login incentive is 26
      ✓ awards user Fish, Milk, Rotten Meat and Honey if login incentive is 30
      ✓ awards user a RoyalPurple hatching potion if login incentive is 35
      ✓ awards user the third moon quest if login incentive is 40
      ✓ awards user a RoyalPurple hatching potion if login incentive is 45
      ✓ awards user a saddle if login incentive is 50

  recoverCron
    ✓ throws an error if user cannot be found (301ms)
    ✓ increases status.times count and reruns up to 4 times (1503ms)
    ✓ throws an error if recoverCron runs 5 times (1504ms)

  emails
    getUserInfo
      ✓ returns an empty object if no field request (61ms)
      ✓ returns correct user data (64ms)
      ✓ returns correct user data [facebook users] (75ms)
      ✓ has fallbacks for missing data (68ms)
    getGroupUrl
      ✓ returns correct url if group is the tavern
      ✓ returns correct url if group is a guild
      ✓ returns correct url if group is a party
    sendTxnEmail
      ✓ can send a txn email to one recipient (91ms)
      ✓ does not send email if address is missing (57ms)
      ✓ uses getUserInfo in case of user data (101ms)
      ✓ sends email with some default variables (49ms)

  encryption
    ✓ can encrypt and decrypt

  Custom Errors
    CustomError
      ✓ is an instance of Error
    NotAuthorized
      ✓ is an instance of CustomError
      ✓ it returns an http code of 401
      ✓ returns a default message
      ✓ allows a custom message
    NotFound
      ✓ is an instance of CustomError
      ✓ it returns an http code of 404
      ✓ returns a default message
      ✓ allows a custom message
      NotificationNotFound
        ✓ is an instance of NotFound
        ✓ it returns an http code of 404
        ✓ returns a standard message
    BadRequest
      ✓ is an instance of CustomError
      ✓ it returns an http code of 401
      ✓ returns a default message
      ✓ allows a custom message
    InternalServerError
      ✓ is an instance of CustomError
      ✓ it returns an http code of 500
      ✓ returns a default message
      ✓ allows a custom message

  highlightMentions
    ✓ doesn't change text without mentions
    ✓ highlights existing users
    ✓ highlights special characters
    ✓ doesn't highlight nonexisting users
    ✓ highlights multiple existing users
    ✓ doesn't highlight more than 5 users

  i18n
    translations
      ✓ includes a translation object for each locale
    langCodes
      ✓ is a list of all the language codes

  Items Utils
    getDefaultOwnedGear
      ✓ clones the result object
    validateItemPath
      ✓ returns false if not an item path
      ✓ returns true if a valid schema path
      ✓ works with owned gear paths
      ✓ works with pets paths
      ✓ works with eggs paths
      ✓ works with hatching potions paths
      ✓ works with food paths
      ✓ works with mounts paths
      ✓ works with quests paths
    castItemVal
      ✓ returns the item val untouched if not an item path
      ✓ returns the item val untouched if an unsupported path
      ✓ converts values for pets paths to numbers
      ✓ converts values for eggs paths to numbers
      ✓ converts values for hatching potions paths to numbers
      ✓ converts values for food paths to numbers
      ✓ converts values for mounts paths to numbers
      ✓ converts values for quests paths to numbers
      ✓ converts values for owned gear

  logger
    info
      ✓ calls winston's info log
    error
      non-error object
        ✓ passes through arguments if the first arg is not an error object
      error object
        ✓ logs the stack and the err data
        ✓ logs the stack and the err data with it's own fullError property
        ✓ logs the error when errorData is null
        ✓ logs the error when errorData is not an object
        ✓ logs the error when errorData does not include isHandledError property
        ✓ logs the error when errorData includes isHandledError property but is a 500 error
        ✓ logs a warning when errorData includes isHandledError property and is not a 500 error
        ✓ logs additional data from a CustomError

  Password Utilities
    compare
      ✓ can compare a correct password hashed with SHA1
      ✓ can compare an invalid password hashed with SHA1
      ✓ can compare a correct password hashed with bcrypt (238ms)
      ✓ can compare an invalid password hashed with bcrypt (234ms)
      ✓ throws an error if user is missing
      ✓ throws an error if passwordToCheck is missing
      ✓ defaults to SHA1 encryption if salt is provided
      ✓ throws an error if an invalid hashing method is used
      ✓ returns true if comparing the same password (250ms)
      ✓ returns true if comparing a different password (184ms)
    convertToBcrypt
      ✓ converts an user password hashed with sha1 to bcrypt (182ms)
      ✓ throws an error if user is missing
      ✓ throws an error if plainTextPassword is missing
    validatePasswordResetCodeAndFindUser
      ✓ returns false if the code is missing
      ✓ returns false if the code is invalid json
(node:16903) DeprecationWarning: collection.remove is deprecated. Use deleteOne, deleteMany, or bulkWrite instead.
      ✓ returns false if the code cannot be decrypted (883ms)
      ✓ returns false if the code is expired (728ms)
      ✓ returns false if the user does not exist
      ✓ returns false if the user has no local auth (738ms)
      ✓ returns false if the code doesn't match the one saved at user.auth.passwordResetCode (830ms)
      ✓ returns the user if the password reset code is valid (1489ms)
    bcrypt
      Hash
        ✓ returns a hashed string (94ms)
      Compare
        ✓ returns true if comparing the same password (189ms)
        ✓ returns true if comparing a different password (197ms)
    SHA1
      Encrypt
        ✓ always encrypt the same password to the same value when using the same salt
        ✓ never encrypt the same password to the same value when using a different salt
      Make Salt
        ✓ creates a salt with length 10 by default
        ✓ can create a salt of any length

  Amazon Payments - Cancel Subscription
    ✓ should throw an error if we are missing a subscription
    ✓ should cancel a user subscription
    ✓ should close a user subscription if amazon not closed
    ✓ should throw an error if group is not found (543ms)
    ✓ should throw an error if user is not group leader (545ms)
    ✓ should cancel a group subscription
    ✓ should close a group subscription if amazon not closed

  Amazon Payments - Checkout
    ✓ should purchase gems
    ✓ should error if gem amount is too low
    ✓ should error if user cannot get gems gems
    ✓ should gift gems (513ms)
    ✓ should gift a subscription (316ms)

  Amazon Payments - Subscribe
    ✓ should throw an error if we are missing a subscription
    ✓ should throw an error if we are missing a billingAgreementId
    ✓ should throw an error when coupon code is missing
    ✓ should throw an error when coupon code is invalid (231ms)
    ✓ subscribes with amazon with a coupon (298ms)
    ✓ subscribes with amazon (588ms)
    ✓ subscribes with amazon with price to existing users (924ms)

  #upgradeGroupPlan
    ✓ charges for a new member (702ms)

  Apple Payments
    verifyGemPurchase
      ✓ should throw an error if receipt is invalid
      ✓ should throw an error if getPurchaseData is invalid
      ✓ errors if the user cannot purchase gems
      ✓ errors if amount does not exist (244ms)
      ✓ purchases com.habitrpg.ios.Habitica.4gems gems (544ms)
      ✓ purchases com.habitrpg.ios.Habitica.20gems gems (305ms)
      ✓ purchases com.habitrpg.ios.Habitica.21gems gems (222ms)
      ✓ purchases com.habitrpg.ios.Habitica.42gems gems (242ms)
      ✓ purchases com.habitrpg.ios.Habitica.84gems gems (245ms)
      ✓ gifts gems (835ms)
    subscribe
      ✓ should throw an error if sku is empty
      ✓ should throw an error if receipt is invalid
      ✓ creates a user subscription for subscription1month
      ✓ creates a user subscription for com.habitrpg.ios.habitica.subscription.3month
      ✓ creates a user subscription for com.habitrpg.ios.habitica.subscription.6month
      ✓ creates a user subscription for com.habitrpg.ios.habitica.subscription.12month
      ✓ errors when a user is already subscribed (540ms)
    cancelSubscribe 
      ✓ should throw an error if we are missing a subscription
      ✓ should throw an error if subscription is still valid
      ✓ should throw an error if receipt is invalid
      ✓ should cancel a user subscription

  Google Payments
    verifyGemPurchase
      ✓ should throw an error if receipt is invalid
      ✓ should throw an error if productId is invalid (241ms)
      ✓ should throw an error if user cannot purchase gems
      ✓ purchases gems (249ms)
      ✓ gifts gems (734ms)
    subscribe
      ✓ should throw an error if receipt is invalid
      ✓ should throw an error if sku is invalid
      ✓ creates a user subscription
    cancelSubscribe 
      ✓ should throw an error if we are missing a subscription
      ✓ should throw an error if receipt is invalid
      ✓ should cancel a user subscription

  Canceling a subscription for group
    ✓ adds a month termination date by default
    ✓ adds extraMonths to dateTerminated value
    ✓ handles extra month fractions
    ✓ terminates at next billing date if it exists
    ✓ resets plan.extraMonths
    ✓ sends an email
    ✓ prevents non group leader from managing subscription
    ✓ allows old group leader to cancel if they created the subscription (40ms)
    ✓ cancels member subscriptions (203ms)
    ✓ sends an email to members of group (160ms)
    ✓ does not cancel member subscriptions when member does not have a group plan sub (i.e. UNLIMITED_CUSTOMER_ID) (119ms)
    ✓ does not cancel a user subscription if they are still in another active group plan (292ms)
    ✓ does cancel a leader subscription with two cancelled group plans (263ms)

  Purchasing a group plan for group
    ✓ creates a group plan
    ✓ sends an email
    ✓ sets extraMonths if plan has dateTerminated date
    ✓ does not set negative extraMonths if plan has past dateTerminated date
    ✓ grants all members of a group a subscription (84ms)
    ✓ sends an email to member of group who was not a subscriber (168ms)
    ✓ sends one email to subscribed member of group, stating subscription is cancelled (Stripe) (266ms)
    ✓ sends one email to subscribed member of group, stating subscription is cancelled (Amazon) (147ms)
    ✓ sends one email to subscribed member of group, stating subscription is cancelled (PayPal) (226ms)
    ✓ sends appropriate emails when subscribed member of group must manually cancel recurring Android subscription (735ms)
    ✓ sends appropriate emails when subscribed member of group must manually cancel recurring iOS subscription (638ms)
    ✓ adds months to members with existing gift subscription (577ms)
    ✓ adds months to members with existing multi-month gift subscription (447ms)
    ✓ adds months to members with existing recurring subscription (Stripe) (158ms)
    ✓ adds months to members with existing recurring subscription (Amazon) (151ms)
    ✓ adds months to members with existing recurring subscription (Paypal) (152ms)
    - adds months to members with existing recurring subscription (Android)
    - adds months to members with existing recurring subscription (iOS)
    ✓ adds months to members who already cancelled but not yet terminated recurring subscription (156ms)
    ✓ adds months to members who already cancelled but not yet terminated group plan subscription (161ms)
    ✓ resets date terminated if user has old subscription (145ms)
    ✓ adds months to members with existing recurring subscription and includes existing extraMonths (163ms)
    ✓ adds months to members with existing recurring subscription and ignores existing negative extraMonths (244ms)
    ✓ does not override gemsBought, mysteryItems, dateCreated, and consective fields (304ms)
    ✓ does not modify a user with a group subscription when they join another group (208ms)
(node:16903) DeprecationWarning: collection.update is deprecated. Use updateOne, updateMany, or bulkWrite instead.
    ✓ does not remove a user who is in two groups plans and leaves one (300ms)
    ✓ does not modify a user with an unlimited subscription (116ms)
    ✓ does not modify a user with an Android subscription (120ms)
    ✓ does not modify a user with an iOS subscription (141ms)
    ✓ updates a user with a cancelled but active group subscription (158ms)

  payments/index
    #createSubscription
      Purchasing a subscription as a gift
        ✓ awards the Royal Purple Jackalope pet (47ms)
        ✓ adds extra months to an existing subscription (49ms)
        ✓ does not set negative extraMonths if plan has past dateTerminated date (111ms)
        ✓ does not reset Gold-to-Gems cap on an existing subscription (46ms)
        ✓ adds to date terminated for an existing plan with a future terminated date (94ms)
        ✓ replaces date terminated for an account with a past terminated date (151ms)
        ✓ sets a dateTerminated date for a user without an existing subscription (217ms)
        ✓ sets plan.dateUpdated if it did not previously exist (141ms)
        ✓ sets plan.dateUpdated if it did exist but the user has cancelled (43ms)
        ✓ sets plan.dateUpdated if it did exist but the user has a corrupt plan (45ms)
        ✓ sets plan.dateCreated if it did not previously exist (40ms)
        ✓ does not change plan.customerId if it already exists (75ms)
        ✓ sets plan.customerId to "Gift" if it does not already exist (44ms)
        ✓ increases the buyer's transaction count (48ms)
        ✓ sends a private message about the gift (50ms)
        ✓ sends an email about the gift (46ms)
        ✓ sends a push notification about the gift (44ms)
        ✓ tracks subscription purchase as gift (67ms)
      Purchasing a subscription for self
        ✓ creates a subscription (94ms)
        ✓ awards the Royal Purple Jackalope pet (40ms)
        ✓ sets extraMonths if plan has dateTerminated date
        ✓ does not set negative extraMonths if plan has past dateTerminated date
        ✓ does not reset Gold-to-Gems cap on additional subscription
        ✓ sets lastBillingDate if payment method is "Amazon Payments" (53ms)
        ✓ increases the user's transaction count (51ms)
        ✓ sends a transaction email
        ✓ tracks subscription purchase
      Block subscription perks
        ✓ adds block months to plan.consecutive.offset (93ms)
        ✓ does not add to plans.consecutive.offset if 1 month subscription (61ms)
        ✓ adds 5 to plan.consecutive.gemCapExtra for 3 month block
        ✓ adds 10 to plan.consecutive.gemCapExtra for 6 month block
        ✓ adds 20 to plan.consecutive.gemCapExtra for 12 month block (50ms)
        ✓ does not raise plan.consecutive.gemCapExtra higher than 25 (117ms)
        ✓ adds a plan.consecutive.trinkets for 3 month block
        ✓ adds 2 plan.consecutive.trinkets for 6 month block (376ms)
        ✓ adds 4 plan.consecutive.trinkets for 12 month block (91ms)
      Mystery Items
        1) awards mystery items when within the timeframe for a mystery item
        2) does not award mystery item when user already owns the item
        3) does not award mystery item when user already has the item in the mystery box
    #cancelSubscription
      Canceling a subscription for self
        ✓ adds a month termination date by default
        ✓ adds extraMonths to dateTerminated value
        ✓ handles extra month fractions (156ms)
        ✓ terminates at next billing date if it exists
        ✓ terminates at next billing date even if dateUpdated is prior to now
        ✓ resets plan.extraMonths
        ✓ sends an email
    #buyGems
      Self Purchase
        ✓ amount property defaults to 5
        ✓ can set amount that is purchased
        ✓ sends a donation email
      Gift
        ✓ calculates balance from gem amount if gift
        ✓ sends a gifted-gems email (51ms)
        ✓ sends a message from purchaser to recipient (78ms)
        ✓ sends a message from purchaser to recipient with custom message (79ms)
        ✓ sends a push notification if user did not gift to self (39ms)
        ✓ sends gem donation message in each participant's language (54ms)
    addSubToGroupUser
      ✓ adds a group subscription to a new user (99ms)
      ✓ awards the Royal Purple Jackalope pet (86ms)
      ✓ saves previously unused Mystery Items and Hourglasses for an expired subscription (135ms)

  checkout success
    ✓ purchases gems
    ✓ gifts gems (574ms)
    ✓ gifts subscription (635ms)

  checkout
    ✓ creates a link for gem purchases
    ✓ should error if gem amount is too low
    ✓ should error if the user cannot get gems
    ✓ creates a link for gifting gems (675ms)
    ✓ creates a link for gifting a subscription

  ipn
    ✓ should cancel a user subscription
    ✓ should cancel a group subscription

  subscribeCancel
    ✓ should throw an error if we are missing a subscription
    ✓ should throw an error if group is not found (522ms)
    ✓ should throw an error if user is not group leader (599ms)
    ✓ should cancel a user subscription
    ✓ should cancel a group subscription

  subscribeSuccess
    ✓ creates a user subscription
    ✓ create a group subscription

  subscribe
    ✓ should throw an error when coupon code is missing
    ✓ should throw an error when coupon code is invalid (216ms)
    ✓ subscribes with paypal with a coupon (247ms)
    ✓ creates a link for a subscription

  cancel subscription
    ✓ throws an error if there is no customer id
    ✓ throws an error if the group is not found (1223ms)
    ✓ throws an error if user is not the group leader (574ms)
    success
      ✓ cancels a user subscription
      ✓ cancels a group subscription

  checkout with subscription
    ✓ should throw an error if we are missing a token
    ✓ should throw an error when coupon code is missing
    ✓ should throw an error when coupon code is invalid (276ms)
    ✓ subscribes with stripe with a coupon (412ms)
    ✓ subscribes a user
    ✓ subscribes a group (566ms)
    ✓ subscribes a group with the correct number of group members (1197ms)

  checkout
    ✓ should error if there is no token
    ✓ should error if gem amount is too low
    ✓ should error if user cannot get gems
    ✓ should purchase gems
    ✓ should gift gems (544ms)
    ✓ should gift a subscription

  edit subscription
    ✓ throws an error if there is no customer id
    ✓ throws an error if a token is not provided
    ✓ throws an error if the group is not found (1419ms)
    ✓ throws an error if user is not the group leader (479ms)
    success
      ✓ edits a user subscription
      ✓ edits a group subscription

  Stripe - Webhooks
    all events
      ✓ logs an error if an unsupported webhook event is passed
      ✓ retrieves and validates the event from Stripe
    customer.subscription.deleted
      ✓ does not do anything if event.request is null (subscription cancelled manually)
      user subscription
        ✓ throws an error if the user is not found
        ✓ deletes the customer on Stripe and calls payments.cancelSubscription (594ms)
      group plan subscription
        ✓ throws an error if the group is not found
        ✓ throws an error if the group leader is not found (340ms)
        ✓ deletes the customer on Stripe and calls payments.cancelSubscription (722ms)

  Stripe - Upgrade Group Plan
    ✓ updates a group plan quantity (556ms)

  preenHistory
    ✓ does not modify history if all entries are more recent than cutoff (free users)
    ✓ does not modify history if all entries are more recent than cutoff (subscribers)
    ✓ does aggregate data in monthly entries before cutoff (free users)
    ✓ does aggregate data in monthly entries before cutoff (subscribers)
    ✓ does aggregate data in monthly and yearly entries before cutoff (free users) (54ms)
    ✓ does aggregate data in monthly and yearly entries before cutoff (subscribers)
    ✓ correctly aggregates values

  pushNotifications
    ✓ throws if user is not supplied
    ✓ throws if user.preferences.pushNotifications.unsubscribeFromAll is true
    ✓ throws if details.identifier is not supplied
    ✓ throws if details.title is not supplied
    ✓ throws if details.message is not supplied
    ✓ returns if no device is registered
    - uses APN for iOS devices

  setupNconf
    ✓ sets up nconf
    ✓ sets IS_PROD variable
    ✓ sets IS_DEV variable
    ✓ allows a custom config.json file to be passed in

  slack
    sendFlagNotification
      ✓ sends a slack webhook
      ✓ includes a title link if guild is public
      ✓ links to tavern
      ✓ provides name for system message
      ✓ noops if no flagging url is provided (56ms)

  taskManager
    ✓ creates user tasks (1208ms)
    ✓ gets user tasks (500ms)
    ✓ creates group tasks (614ms)
    ✓ gets group tasks (691ms)
    ✓ creates challenge tasks (456ms)
    ✓ gets challenge tasks (629ms)
    ✓ returns syncable attibutes (433ms)
    ✓ moves tasks to a specified position
    ✓ moves tasks to a specified position out of length
    onboarding
      ✓ adds the onboarding achievement to the user and checks the onboarding status (594ms)
      ✓ does not add the onboarding achievement to the user if flags.welcomed is false (501ms)
      ✓ does not add the onboarding achievement to the user if it's already been awarded (1222ms)

  webhooks
    WebhookSender
      ✓ creates a new WebhookSender object
      ✓ provides default function for data transformation
      ✓ adds default data (user and webhookType) to the body
      ✓ can pass in a data transformation function
      ✓ provides a default filter function
      ✓ can pass in a webhook filter function
      ✓ can pass in a webhook filter function that filters on data
      ✓ ignores disabled webhooks
      ✓ ignores webhooks with invalid urls
      ✓ ignores webhooks of other types
      ✓ sends every type of activity to global webhooks
      ✓ sends multiple webhooks of the same type
    taskScoredWebhook
      ✓ sends task and stats data
      ✓ sends task and stats data to globalActivity webhookd
      ✓ does not send task scored data if scored option is not true
    taskActivityWebhook
      ✓ sends created tasks
      ✓ does not send task created data if created option is not true
      ✓ sends updated tasks
      ✓ does not send task updated data if updated option is not true
      ✓ sends deleted tasks
      ✓ does not send task deleted data if deleted option is not true
      checklistScored
        ✓ sends 'checklistScored' tasks
        ✓ does not send task 'checklistScored' data if 'checklistScored' option is not true
    userActivityWebhook
      ✓ sends petHatched webhooks
      ✓ does not send webhook petHatched data if petHatched option is not true
      ✓ sends mountRaised webhooks
      ✓ does not send webhook mountRaised data if mountRaised option is not true
      ✓ sends leveledUp webhooks
      ✓ does not send webhook leveledUp data if leveledUp option is not true
    questActivityWebhook
      ✓ sends questStarted webhooks
      ✓ does not send webhook questStarted data if questStarted option is not true
      ✓ sends questFinised webhooks
      ✓ does not send webhook questFinised data if questFinised option is not true
      ✓ sends questInvited webhooks
      ✓ does not send webhook questInvited data if questInvited option is not true
    groupChatReceivedWebhook
      ✓ sends chat data
      ✓ does not send chat data for group if not selected

  analytics middleware
    ✓ attaches analytics object res.locals
    ✓ attaches stubbed methods for non-prod environments
    ✓ attaches real methods for prod environments

  auth middleware
    auth with headers
      ✓ allows to specify a list of user field that we do not want to load
      ✓ makes sure some fields are always included

  cors middleware
    ✓ sets the correct headers
    ✓ responds immediately if method is OPTIONS

  cron middleware
    ✓ calls next when user is not attached
    ✓ calls next when days have not been missed (141ms)
    ✓ should clear todos older than 30 days for free users (336ms)
    ✓ should not clear todos older than 30 days for subscribed users (938ms)
    ✓ should clear todos older than 90 days for subscribed users (442ms)
    ✓ should call next if user was not modified after cron (154ms)
    ✓ updates user.auth.timestamps.loggedin and lastCron (96ms)
    ✓ does damage for missing dailies (133ms)
    ✓ updates tasks (406ms)
    ✓ applies quest progress (765ms)
    4) recovers from failed cron and does not error when user is already cronning
    5) cronSignature less than an hour ago should error
    ✓ cronSignature longer than an hour ago should allow cron (126ms)

  ensure access middlewares
    ensure admin
      ✓ returns not authorized when user is not an admin
      ✓ passes when user is an admin
    ensure sudo
      ✓ returns not authorized when user is not a sudo user
      ✓ passes when user is a sudo user

  developmentMode middleware
    ✓ returns not found when in production mode
    ✓ passes when not in production

  errorHandler
    ✓ sends internal server error if error is not a CustomError and is not identified
    ✓ identifies errors with statusCode property and format them correctly
    ✓ doesn't leak info about 500 errors
    ✓ sends CustomError
    ✓ handle http-errors errors
    ✓ handle express-validator errors
    ✓ handle Mongoose Validation errors
    ✓ logs error

  language middleware
    res.t
      ✓ attaches t method to res
      ✓ uses the language specified in req.language
    getUserLanguage
      query parameter
        ✓ uses the language in the query parameter if avalaible
        ✓ falls back to english if the query parameter language does not exists
        ✓ uses query even if the request includes a user and session
      authorized request
        ✓ uses the user preferred language if avalaible
        ✓ falls back to english if the user preferred language is not avalaible
        ✓ uses the user preferred language even if a session is included in request
      request with session
        ✓ uses the user preferred language if avalaible
      browser fallback
        ✓ uses browser specificed language
        ✓ uses first language in series if browser specifies multiple
        ✓ skips invalid lanaguages and uses first language in series if browser specifies multiple
        ✓ uses normal version of language if specialized locale is passed in
        ✓ uses normal version of language if specialized locale is passed in
        ✓ uses es if es is passed in
        ✓ uses es_419 if applicable es-languages are passed in
        ✓ uses es_419 if multiple es languages are passed in
        ✓ zh
        ✓ uses english if browser specified language is not compatible
        ✓ uses english if browser does not specify
        ✓ uses english if browser does not supply an accept-language header

  maintenance mode middleware
    ✓ does not return 503 error when maintenance mode is off
    ✓ returns 503 error when maintenance mode is on
    ✓ renders maintenance page when request type is HTML
    ✓ sends error message when request type is JSON

  redirects middleware
    forceSSL
      ✓ sends http requests to https
      ✓ does not redirect https forwarded requests
      ✓ does not redirect outside of production environments (48ms)
      ✓ does not redirect if base URL is not https (42ms)
      ✓ does not redirect if passed skip ssl request param is passed with corrrect key
      ✓ does redirect if skip ssl request param is passed with incorrrect key
      ✓ does redirect if skip ssl check key is not set
    forceHabitica
      ✓ sends requests with differing hostname to base URL host (91ms)
      ✓ does not redirect outside of production environments (75ms)
      ✓ does not redirect if env is set to ignore redirection
      ✓ does not redirect if request hostname matches base URL host (41ms)
      ✓ does not redirect if request is an API URL (54ms)
      ✓ does not redirect if request method is not GET (44ms)

  response middleware
    ✓ attaches respond method to res
    ✓ can be used to respond to requests
    ✓ can be passed a third parameter to be used as optional message
    ✓ treats status >= 400 as failures
    ✓ returns userV if a user is authenticated
    ✓ returns notifications if a user is authenticated

  Challenge Model
    habit
      ✓ adds tasks to challenge and challenge members (106ms)
      ✓ adds a challenge to a user (63ms)
      ✓ does not add a challenge to a user that already in the challenge (55ms)
      ✓ syncs challenge tasks to a user (78ms)
      ✓ syncs challenge tasks to a user with the existing task (66ms)
      ✓ updates tasks to challenge and challenge members (102ms)
      ✓ removes a tasks to challenge and challenge members (38ms)
      ✓ unlinks and deletes challenge tasks for a user when remove-all is specified (75ms)
      ✓ unlinks and keeps challenge tasks for a user when keep-all is specified (60ms)
    todo
      ✓ adds tasks to challenge and challenge members
      ✓ adds a challenge to a user (39ms)
      ✓ does not add a challenge to a user that already in the challenge (43ms)
      ✓ syncs challenge tasks to a user (96ms)
      ✓ syncs challenge tasks to a user with the existing task (58ms)
      ✓ updates tasks to challenge and challenge members
      ✓ removes a tasks to challenge and challenge members
      ✓ unlinks and deletes challenge tasks for a user when remove-all is specified (122ms)
      ✓ unlinks and keeps challenge tasks for a user when keep-all is specified
    daily
      ✓ adds tasks to challenge and challenge members
      ✓ adds a challenge to a user (41ms)
      ✓ does not add a challenge to a user that already in the challenge (56ms)
      ✓ syncs challenge tasks to a user (125ms)
      ✓ syncs challenge tasks to a user with the existing task (96ms)
      ✓ updates tasks to challenge and challenge members (48ms)
      ✓ removes a tasks to challenge and challenge members
      ✓ unlinks and deletes challenge tasks for a user when remove-all is specified
      ✓ unlinks and keeps challenge tasks for a user when keep-all is specified (38ms)
    reward
      ✓ adds tasks to challenge and challenge members (113ms)
      ✓ adds a challenge to a user (70ms)
      ✓ does not add a challenge to a user that already in the challenge (55ms)
      ✓ syncs challenge tasks to a user (93ms)
      ✓ syncs challenge tasks to a user with the existing task (60ms)
      ✓ updates tasks to challenge and challenge members
      ✓ removes a tasks to challenge and challenge members
      ✓ unlinks and deletes challenge tasks for a user when remove-all is specified (240ms)
      ✓ unlinks and keeps challenge tasks for a user when keep-all is specified
    type specific updates
      ✓ updates habit specific field to challenge and challenge members (214ms)
      ✓ updates todo specific field to challenge and challenge members (62ms)
      ✓ does not update checklists on the user task (146ms)
      ✓ updates daily specific field to challenge and challenge members (128ms)

  Group Model
    Static Methods
      processQuestProgress
        early returns
          ✓ returns early if user is not in a party (246ms)
          ✓ returns early if party is not on quest
          ✓ returns early if user is not on quest
          ✓ returns early if user has made no progress
          ✓ returns early if quest does not exist
          ✓ calls _processBossQuest if quest is a boss quest (377ms)
          ✓ calls _processCollectionQuest if quest is a collection quest (455ms)
          ✓ does not call _processBossQuest when user is resting in the inn (298ms)
          ✓ does not call _processCollectionQuest when user is resting in the inn (224ms)
        Boss Quests
          ✓ applies user's progress to quest boss hp
          ✓ sends a chat message about progress
          ✓ applies damage only to participating members of party (102ms)
          ✓ applies damage only to participating members of party even under buggy conditions (111ms)
          ✓ sends message about victory
          ✓ calls finishQuest when boss has <= 0 hp
          with healing Rage
            ✓ applies down progress to boss rage
            ✓ activates rage when progress.down triggers rage bar
            ✓ rage sets boss hp to max hp if raging would have caused hp to be higher than the max
          with Mana drain Rage
            ✓ applies down progress to boss rage
            ✓ activates rage when progress.down triggers rage bar (134ms)
        Collection Quests
          ✓ applies user's progress to found quest items
          ✓ does not drop an item if not need when on a collection quest
          ✓ sends a chat message about progress
          ✓ sends a chat message if no progress is made (102ms)
          ✓ sends a chat message if no progress is made on quest with multiple items
          ✓ handles collection quests with multiple items (49ms)
          ✓ sends message about victory (40ms)
          ✓ calls finishQuest when all items are found
          ✓ gives out rewards when quest finishes (69ms)
      validateInvitations
        ✓ throws an error if no uuids or emails are passed in
        ✓ throws an error if only uuids are passed in, but they are not an array
        ✓ throws an error if only emails are passed in, but they are not an array
        ✓ throws an error if emails are not passed in, and uuid array is empty
        ✓ throws an error if uuids are not passed in, and email array is empty
        ✓ throws an error if uuids and emails are passed in as empty arrays
        ✓ throws an error if total invites exceed max invite constant
        ✓ does not throw error if number of invites matches max invite limit
        ✓ does not throw an error if only user ids are passed in
        ✓ does not throw an error if only emails are passed in
        ✓ does not throw an error if both uuids and emails are passed in
        ✓ does not throw an error if uuids are passed in and emails are an empty array
        ✓ does not throw an error if emails are passed in and uuids are an empty array
      translateSystemMessages
        ✓ translate quest_start
        ✓ translate boss_damage
        ✓ translate boss_dont_attack
        ✓ translate boss_rage
        ✓ translate boss_defeated
        ✓ translate user_found_items
        ✓ translate all_items_found
        ✓ translate spell_cast_party
        ✓ translate spell_cast_user
        ✓ translate quest_cancel
        ✓ translate quest_abort
        ✓ translate tavern_quest_completed
        ✓ translate tavern_boss_rage_tired
        ✓ translate tavern_boss_rage
        ✓ translate tavern_boss_desperation
        ✓ translate claim_task
      toJSONCleanChat
        ✓ shows messages with 1 flag to non-admins
        ✓ shows messages with >= 2 flag to admins
        ✓ doesn't show flagged messages to non-admins
    Instance Methods
      #getParticipatingQuestMembers
        ✓ returns an array of members whose quest status set to true
      #checkChatSpam
        ✓ group that is not the tavern returns false, while tavern returns true
        ✓ high enough contributor returns false
        ✓ chat with no messages returns false
        ✓ user has not reached limit but another one has returns false
        ✓ user messages is less than the limit returns false
        ✓ user has reached the message limit outside of window returns false
        ✓ user has posted too many messages in limit returns true
      #leaveGroup
        ✓ removes user from group quest
        ✓ unlink group tag (54ms)
        ✓ deletes a private party when the last member leaves (153ms)
        ✓ does not delete a private group when the last member leaves and a subscription is active
        ✓ does not allow a leader to leave a group with an active subscription
        ✓ deletes a private group when the last member leaves and a subscription is cancelled (120ms)
        ✓ does not delete a public group when the last member leaves (76ms)
        ✓ does not delete a private party when the member count reaches zero if there are still members (82ms)
        ✓ deletes a private guild when the last member leaves (49ms)
        ✓ does not delete a private guild when the member count reaches zero if there are still members (79ms)
      #sendChat
        ✓ formats message
        ✓ formats message as system if no user is passed in
        ✓ updates users about new messages in party
        ✓ updates users about new messages in group
        ✓ does not send update to user that sent the message
        ✓ skips sending new message notification for guilds with > 5000 members
        ✓ skips sending messages to the tavern
      #startQuest
        Failure Conditions
          ✓ throws an error if group is not a party
          ✓ throws an error if party is not on a quest
          ✓ throws an error if quest is already active
        Successes
          ✓ activates quest
          ✓ sets up boss quest
          ✓ sets up rage meter for rage boss quest
          ✓ sets up collection quest
          ✓ sets up collection quest with multiple items
          ✓ prunes non-participating members from quest members object
          ✓ applies updates to user object directly if user is participating (without resetting progress, except progress.down)
          ✓ applies updates to other participating members (without resetting progress, except progress.down) (411ms)
          ✓ does not apply updates to nonparticipating members (297ms)
          6) sends email to participating members that quest has started
          7) sends webhook to participating members that quest has started
          8) sends email only to members who have not opted out
          9) does not send email to initiating member
          ✓ updates participting members (not including user) (280ms)
          ✓ updates non-user quest leader and decrements quest scroll (400ms)
          ✓ modifies the participating initiating user directly (294ms)
          ✓ does not modify user if not participating (307ms)
          ✓ removes the quest directly if initiating user is the quest leader (229ms)
      #finishQuest
        ✓ gives out achievements (46ms)
        ✓ gives out super awesome Masterclasser achievement to the deserving (94ms)
        10) gives out super awesome Masterclasser achievement when quests done out of order
        ✓ gives out other pet-related quest achievements (136ms)
        ✓ gives xp and gold (39ms)
        11) sends webhook to participating members that quest has finished
        user update retry failures
          ✓ doesn't retry successful operations
          ✓ stops retrying when a successful update has occurred
          ✓ retries failed updates at most five times per user
        drops
          ✓ awards gear
          ✓ awards eggs
          ✓ awards food
          ✓ awards hatching potions
          ✓ awards quest scrolls to owner
          ✓ awards non quest leader rewards to quest leader
          ✓ doesn't award quest owner rewards to all participants
          ✓ awards pets
          ✓ awards mounts
        Party quests
          ✓ updates participating members with rewards
          ✓ updates participating members quest object to a clean state (except for progress)
        World quests in Tavern
          ✓ updates all users with rewards
          ✓ sets quest completed to the world quest key
      sendGroupChatReceivedWebhooks
        ✓ looks for users in specified guild with webhooks
        ✓ looks for users in specified party with webhooks
        12) sends webhooks for users with webhooks
        13) sends webhooks for users with webhooks triggered by system messages
        14) sends webhooks for each user with webhooks in group
      isSubscribed
        ✓ returns false if group does not have customer id
        ✓ returns true if group does not have plan.dateTerminated
        ✓ returns true if group if plan.dateTerminated is after today
        ✓ returns false if group if plan.dateTerminated is before today
      hasNotCancelled
        ✓ returns false if group does not have customer id
        ✓ returns true if group does not have plan.dateTerminated
        ✓ returns false if group if plan.dateTerminated is after today
        ✓ returns false if group if plan.dateTerminated is before today
      hasCancelled
        ✓ returns false if group does not have customer id
        ✓ returns false if group does not have plan.dateTerminated
        ✓ returns true if group if plan.dateTerminated is after today
        ✓ returns false if group if plan.dateTerminated is before today

  Group Task Methods
    habit
      ✓ syncs an assigned task to a user (50ms)
      ✓ create tags for a user when task is synced (85ms)
      ✓ syncs updated info for assigned task to a user (88ms)
      ✓ syncs checklist items to an assigned user (96ms)
      ✓ removes an assigned task and unlinks assignees (53ms)
      ✓ unlinks and deletes group tasks for a user when remove-all is specified (168ms)
      ✓ unlinks and keeps group tasks for a user when keep-all is specified (511ms)
      syncs updated info
        ✓ syncs updated info for assigned task to all users (125ms)
        ✓ syncs a new checklist item to all assigned users
        ✓ syncs updated info for checklist in assigned task to all users when flag is passed
        ✓ removes a checklist item in assigned task to all users when flag is passed with checklist id
    todo
      ✓ syncs an assigned task to a user (162ms)
      ✓ create tags for a user when task is synced (53ms)
      ✓ syncs updated info for assigned task to a user (422ms)
      ✓ syncs checklist items to an assigned user (62ms)
      ✓ removes an assigned task and unlinks assignees (48ms)
      ✓ unlinks and deletes group tasks for a user when remove-all is specified (55ms)
      ✓ unlinks and keeps group tasks for a user when keep-all is specified (70ms)
      syncs updated info
        ✓ syncs updated info for assigned task to all users (47ms)
        ✓ syncs a new checklist item to all assigned users
        ✓ syncs updated info for checklist in assigned task to all users when flag is passed (40ms)
        ✓ removes a checklist item in assigned task to all users when flag is passed with checklist id
    daily
      ✓ syncs an assigned task to a user
      ✓ create tags for a user when task is synced (292ms)
      ✓ syncs updated info for assigned task to a user (52ms)
      ✓ syncs checklist items to an assigned user
      ✓ removes an assigned task and unlinks assignees
      ✓ unlinks and deletes group tasks for a user when remove-all is specified (308ms)
      ✓ unlinks and keeps group tasks for a user when keep-all is specified (50ms)
      syncs updated info
        ✓ syncs updated info for assigned task to all users
        ✓ syncs a new checklist item to all assigned users (38ms)
        ✓ syncs updated info for checklist in assigned task to all users when flag is passed
        ✓ removes a checklist item in assigned task to all users when flag is passed with checklist id
    reward
      ✓ syncs an assigned task to a user (146ms)
      ✓ create tags for a user when task is synced
      ✓ syncs updated info for assigned task to a user (40ms)
      ✓ syncs checklist items to an assigned user
      ✓ removes an assigned task and unlinks assignees
      ✓ unlinks and deletes group tasks for a user when remove-all is specified (45ms)
      ✓ unlinks and keeps group tasks for a user when keep-all is specified (62ms)
      syncs updated info
        ✓ syncs updated info for assigned task to all users (141ms)
        ✓ syncs a new checklist item to all assigned users
        ✓ syncs updated info for checklist in assigned task to all users when flag is passed
        ✓ removes a checklist item in assigned task to all users when flag is passed with checklist id

  Task Model
    habit
      ✓ preens challenge tasks history when scored
    daily
      ✓ preens challenge tasks history when scored
    Static Methods
      findByIdOrAlias
        ✓ throws an error if task identifier is not passed in
        ✓ throws an error if user identifier is not passed in
        ✓ returns task by id
        ✓ returns task by alias
        ✓ scopes alias lookup to user
        ✓ returns null if task cannot be found
        ✓ accepts additional query parameters

  User Model
    ✓ keeps user._tmp when calling .toJSON
    ✓ can add computed stats to a JSONified user object
    ✓ can transform user object without mongoose helpers (648ms)
    ✓ can transform user object without mongoose helpers (including computed stats) (509ms)
    achievements
      ✓ can add an achievement
      ✓ throws an error if the achievement is not valid
      static push method
        ✓ throws an error if the achievement is not valid (598ms)
        ✓ adds an achievement for a single member via static method (513ms)
        ✓ adds an achievement for all given users via static method (614ms)
    notifications
      ✓ can add notifications without data
      ✓ removes invalid notifications when calling toJSON
      ✓ can add notifications with data and already marked as seen
      static push method
        ✓ adds notifications for a single member via static method (499ms)
        ✓ validates notifications via static method (1023ms)
        ✓ adds notifications without data for all given users via static method (580ms)
        ✓ adds notifications with data and seen status for all given users via static method (597ms)
    isSubscribed
      ✓ returns false if user does not have customer id
      ✓ returns true if user does not have plan.dateTerminated
      ✓ returns true if user if plan.dateTerminated is after today
      ✓ returns false if user if plan.dateTerminated is before today
    canGetGems
      ✓ returns true if user is not subscribed
      ✓ returns true if user is not subscribed with a group plan
      ✓ returns true if user is subscribed with a group plan
      ✓ returns true if user is part of a group
      ✓ returns true if user is part of a group with a subscription (190ms)
      ✓ returns true if leader is part of a group with a subscription and canGetGems: false (234ms)
      ✓ returns true if user is part of a group with no subscription but canGetGems: false (283ms)
      ✓ returns false if user is part of a group with a subscription and canGetGems: false (233ms)
    hasNotCancelled
      ✓ returns false if user does not have customer id
      ✓ returns true if user does not have plan.dateTerminated
      ✓ returns false if user if plan.dateTerminated is after today
      ✓ returns false if user if plan.dateTerminated is before today
    hasCancelled
      ✓ returns false if user does not have customer id
      ✓ returns false if user does not have plan.dateTerminated
      ✓ returns true if user if plan.dateTerminated is after today
      ✓ returns false if user if plan.dateTerminated is before today
    pre-save hook
      ✓ does not try to award achievements when achievements or items not selected in query (501ms)
      ✓ adds achievements to notification list (588ms)
      manage unallocated stats points notifications
        ✓ doesn't add a notification if there are no points to allocate (555ms)
        ✓ removes a notification if there are no more points to allocate (494ms)
        ✓ adds a notification if there are points to allocate (546ms)
        ✓ adds a notification if the points to allocate have changed (611ms)
        ✓ does not add a notification if the user has disabled classes (642ms)
        ✓ does not add a notification if the user has not selected a class (563ms)
    days missed
      ✓ should not cron early when going back a timezone
      ✓ should not cron early when going back a timezone with a custom day start

  UserNotification Model
    convertNotificationsToSafeJson
      ✓ converts an array of notifications to a safe version

  Webhook Model
    Instance Methods
      #formatOptions
        type is taskActivity
          ✓ it provides default values for options
          ✓ provides missing task options
          ✓ discards additional options
          ✓ validates that created is a boolean
          ✓ validates that updated is a boolean
          ✓ validates that deleted is a boolean
          ✓ validates that scored is a boolean
          ✓ validates that checklistScored is a boolean
        type is userActivity
          ✓ it provides default values for options
          ✓ provides missing user options
          ✓ discards additional options
          ✓ validates that petHatched is a boolean
          ✓ validates that petHatched is a boolean
          ✓ validates that leveledUp is a boolean
        type is questActivity
          ✓ it provides default values for options
          ✓ provides missing user options
          ✓ discards additional options
          ✓ validates that questStarted is a boolean
          ✓ validates that questFinished is a boolean
        type is groupChatReceived
          ✓ creates options
          ✓ discards additional objects
          ✓ requires groupId option to be a uuid
        type is globalActivity
          ✓ discards additional objects

  15) "after all" hook

  937 passing (11m)
  4 pending
  15 failing

  1) payments/index
       #createSubscription
         Mystery Items
           awards mystery items when within the timeframe for a mystery item:
     AssertionError: expected [ Array(2) ] to include 'armor_mystery_201605'
      at Context.<anonymous> (test/api/unit/libs/payments/payments.test.js:434:53)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  2) payments/index
       #createSubscription
         Mystery Items
           does not award mystery item when user already owns the item:

      AssertionError: expected [ Array(2) ] to have a length of 1 but got 2
      + expected - actual

      -2
      +1
      
      at Context.<anonymous> (test/api/unit/libs/payments/payments.test.js:452:60)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  3) payments/index
       #createSubscription
         Mystery Items
           does not award mystery item when user already has the item in the mystery box:
     AssertionError: expected push to have been called exactly once, but it was called twice
    push(armor_mystery_201606) => 2 at /home/osiris/habitica/website/server/libs/payments/subscriptions.js:1:34553
    push(head_mystery_201606) => 3 at /home/osiris/habitica/website/server/libs/payments/subscriptions.js:1:34553
      at Context.<anonymous> (test/api/unit/libs/payments/payments.test.js:469:9)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:97:5)

  4) cron middleware
       recovers from failed cron and does not error when user is already cronning:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/osiris/habitica/test/api/unit/middlewares/cronMiddleware.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  5) cron middleware
       cronSignature less than an hour ago should error:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/osiris/habitica/test/api/unit/middlewares/cronMiddleware.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  6) Group Model
       Instance Methods
         #startQuest
           Successes
             sends email to participating members that quest has started:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/osiris/habitica/test/api/unit/models/group.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  7) Group Model
       Instance Methods
         #startQuest
           Successes
             sends webhook to participating members that quest has started:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/osiris/habitica/test/api/unit/models/group.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  8) Group Model
       Instance Methods
         #startQuest
           Successes
             sends email only to members who have not opted out:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/osiris/habitica/test/api/unit/models/group.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  9) Group Model
       Instance Methods
         #startQuest
           Successes
             does not send email to initiating member:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/osiris/habitica/test/api/unit/models/group.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  10) Group Model
       Instance Methods
         #finishQuest
           gives out super awesome Masterclasser achievement when quests done out of order:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/osiris/habitica/test/api/unit/models/group.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  11) Group Model
       Instance Methods
         #finishQuest
           sends webhook to participating members that quest has finished:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/osiris/habitica/test/api/unit/models/group.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  12) Group Model
       Instance Methods
         sendGroupChatReceivedWebhooks
           sends webhooks for users with webhooks:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/osiris/habitica/test/api/unit/models/group.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  13) Group Model
       Instance Methods
         sendGroupChatReceivedWebhooks
           sends webhooks for users with webhooks triggered by system messages:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/osiris/habitica/test/api/unit/models/group.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  14) Group Model
       Instance Methods
         sendGroupChatReceivedWebhooks
           sends webhooks for each user with webhooks in group:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/osiris/habitica/test/api/unit/models/group.test.js)
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)

  15) "after all" hook:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at listOnTimeout (internal/timers.js:549:17)
      at processTimers (internal/timers.js:492:7)




=============================== Coverage summary ===============================
Statements   : 42.88% ( 5542/12923 )
Branches     : 29.47% ( 1929/6546 )
Functions    : 33.98% ( 509/1498 )
Lines        : 44.94% ( 5317/11831 )
================================================================================
[20:45:41] The following tasks did not complete: test:api:unit
[20:45:41] Did you forget to signal async completion?
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! habitica@4.134.2 test:api:unit: `gulp test:api:unit`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the habitica@4.134.2 test:api:unit script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/osiris/.npm/_logs/2020-02-26T12_45_42_245Z-debug.log
osiris@osiris-LIFEBOOK-SH572:~/habitica$

**Comment by tsukimi2** [comment]
> Hi @tsukimi2 from the screenshot you posted looks like you were running the server side API unit tests instead of the client side ones that can be run with `npm run client:unit`, you can also see the output here https://github.com/HabitRPG/habitica/pull/11903/checks?check_run_id=464584079

Thanks for the info.  Wasn't aware of this command since it's not on habitica wiki's article "Using Your Local Install to Modify Habitica's Website and API" where it talks about running the test suite.  On hindsight, should have checked the package.json first.  ^_^

**Comment by Alys** [comment]
@tsukimi2 If you'd like to edit that wiki page to add any missing information, your help would be welcome!

**Comment by tsukimi2** [comment]
> @tsukimi2 If you'd like to edit that wiki page to add any missing information, your help would be welcome!

@Alys Sure, I'll see whether I can do it during the weekend.  ^_^

File: website/client/src/components/shops/buyModal.vue [hunk 1]
```diff
@@ -119,7 +122,10 @@
         <div v-if="attemptingToPurchaseMoreGemsThanAreLeft">
           {{ $t('notEnoughGemsToBuy') }}
         </div>
-        <div v-if="nonSubscriberHourglasses" class="hourglass-nonsub mt-3">
+        <div
```
Comment (paglias) [inline website/client/src/components/shops/buyModal.vue]: @tsukimi2 looks like your text editor might be autoformatting the code in some places, is it possible to disable that behavior? Because it ends up inserting a lot of unrelated changes inside PRs that make it a bit difficult to see what actually changed

File: website/client/src/mixins/groupsUtilities.js [hunk 2]
```diff
@@ -75,11 +91,11 @@ export default {
       }
 
       if (filters.guildSize && filters.guildSize.indexOf('gold_tier') !== -1) {
-        correctSize = group.memberCount > 1000;
+        correctSize = group.memberCount >= 1000;
```
Comment (paglias) [inline website/client/src/mixins/groupsUtilities.js:94]: why the change from > to >=?

File: website/client/src/mixins/groupsUtilities.js [hunk 3]
```diff
@@ -1,4 +1,22 @@
 import intersection from 'lodash/intersection';
+import _ from 'lodash';
+
+const containsAnyCi = (target, patterns) => patterns.some(el => target.match(new RegExp(el, 'i')));
```
Comment (paglias) [inline website/client/src/mixins/groupsUtilities.js:4]: what does CI stands for?

Comment (tsukimi2) [reply website/client/src/mixins/groupsUtilities.js:4]: @paglias Ci = case insensitive.

File: website/client/src/mixins/groupsUtilities.js (hunk 2 above)
Comment (tsukimi2) [reply website/client/src/mixins/groupsUtilities.js:94]: @paglias Because from the [Habitica Wiki on Guilds Guide](https://habitica.fandom.com/wiki/Guilds_Guide), it says "Large Guilds of Habitica Guilds with 1000 or more members.  I take it this corresponds to the gold tier guilds, and 1000 or more members is equivalent to "membercount >= 1000 instead of > 1000"?

File: website/client/src/components/shops/buyModal.vue (hunk 1 above)
Comment (tsukimi2) [reply website/client/src/components/shops/buyModal.vue]: @paglias Yes, sorry, I noticed this problem before also, and I thought it was due to lint modifying the files after running "npm run lint" (since when I run git status after making code changes but before running npm run lint, the git status showed only the files I made changes as being modified, but after running npm run lint, a bunch of files that I have not made any changes myself got marked as modified).  I always thought it's lint modifying the files after running "npm run lint" and not noticing it may be due to the visual studio code that I'm using (first time using this ide on a project) to edit code.  I've just set its editor.formatOnSave to false in its settings.json now and see whether this fixes the problem next time I submit a PR, or I might simply try using a barebone vi to edit code first and see what happens.  Sorry for the inconvenience this has caused.

File: website/client/src/mixins/groupsUtilities.js (hunk 2 above)
Comment (paglias) [reply website/client/src/mixins/groupsUtilities.js:94]: makes sense, good catch!

File: website/client/src/components/shops/buyModal.vue (hunk 1 above)
Comment (paglias) [reply website/client/src/components/shops/buyModal.vue]: No worries, it's happening quite often with other PRs as well. I thought about `npm run lint` as well but I don't think it's, VSCode is more likely but I'm not sure if it's just applying some extra lint rules (warns instead of errors) that aren't applied by `npm run lint` in which case it's totally fine or if it's using it's own rules. I'll let you know if I find what's causing this

**Comment by paglias** [comment]
@tsukimi2 thanks for the tests, very appreciated!

I've found a couple of issues though (but only with Public Guilds):

- Adding a white space in the search input causes the results to include every guild with a space in the title

Schermata 2020-03-09 alle 21 28 27

^ see the first result even though it doesn't have any match

- it seems to have some issues with summaries in Discover Guilds, given the second guild in the screenshot above searching for `summary` doesn't return it even though it's in the summary

So my guilds works fine but there are still some differencies, if the PR was meant to handle only My Guilds then it works fine

**Comment by tsukimi2** [comment]
@paglias Yes, you are correct, should modify the Discovery Guilds code a bit as well so that the search behaviour between the MyGuilds and Discover Guilds are consistent.  Going to do that soon.

Will also expand on the "describe(filters)" section in the GET-groups.test.js under test:api-v3:integration so that the consistency between the search behaviour of Discovery Guilds and MyGuilds can be auto-tested (there're actually such test cases there already but apparently missing some test cases for some of the search conditions, like the test cases you have pointed out in your previous comment).  So just going to fill in the blanks there.

**Comment by paglias** [comment]
thanks @tsukimi2 :) noted towards your 3rd tier
