### PR TITLE
Potential fix for #6085 - fix subscriber benefits comparisons; round down 3 month blocks for perks - fixes #6085

### LINKED ISSUE #6085: Wrong subscriber benefits comparisons
Hello,

I was looking into the differences between subscribing for 3 consecutive months and 12 and the green bars that usually indicated the Buy Gems with Gold "Cap raised to _" and the "+_ Mystic Hourglass(es)" aren't functioning properly.

The green bars aren't there when "Recurring $5 every 1 months" is selected, which is what they're supposed to be.

But for the "Recurring $15 every 3 months", "Recurring $30 every 6 months", and "Recurring $48 every 12 months" the greens bars say "Cap raised to 26" and "+0 Mystic Hourglass". Even when switching back and forth and re-loading the page, and logging out and back in again.

My User ID: 2e7cc3ad-48b6-4f2a-a132-b1a0cb66ec34
Not sure if relevant, but I'm on the Version 46.0.2490.71 (64-bit) of Google Chrome on a OS X Yosemite, Version 10.10.4.

I hope it gets fixed; and I'll keep refreshing to see if/when it's fixed.

Sorry for any inconvenience!
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/27613527-wrong-subscriber-benefits-comparisons?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by ojeytonwilliams**
The view had the subscriber benefits bound to the basic subscription, so I changed that to be dynamic.  Also, the controller now rounds down number of 3 month blocks before adding to the subscriber perks.

### CODE REVIEW

**Comment by Alys** [comment]
Thanks @ojeytonwilliams! I've adjusted the title to add "fixes #6085" because that will cause the issue to be automatically closed if this PR is merged. I've also added some words so that we can identify this PR when looking through the list of PRs or when searching.

**Comment by ojeytonwilliams** [comment]
@Alys  Sorry about that - I thought it would be enough to have "fix" and the issue id in the title!  Thanks for sorting it out.

**Comment by Alys** [comment]
Oh no need to apologise! The other stuff are just optional extras that are nice to have. :)

File: website/public/js/controllers/settingsCtrl.js [hunk 1]
```diff
@@ -206,10 +206,10 @@ habitrpg.controller('SettingsCtrl',
       var baseCap = 25;
       var gemCapExtra = User.user.purchased.plan.consecutive.gemCapExtra;
       // @TODO: What are these magic numbers? 3? 5?
-      var blocks = Content.subscriptionBlocks[subscription.key].months / 3 * 5;
```
Comment (crookedneighbor) [inline website/public/js/controllers/settingsCtrl.js:209]: Can we figure out what these magic numbers are and create variables for them?

Comment (ojeytonwilliams) [inline website/public/js/controllers/settingsCtrl.js:209]: Is the new commit what you were after?  I had a look at adding them as vars in Content and referencing them here, but soon realized that I don't understand how script/src is converted to src.  

I reckon it would be better added to Content, but I didn't want to mess things up.

**Comment by crookedneighbor** [comment]
This looks good to me. @Alys How does it look to you?

**Comment by Alys** [comment]
I'll check it out within about 20 hours (I'm at work now and it's a late finish today).

**Comment by Alys** [comment]
This is good. Merging. 

@ojeytonwilliams This will count towards a contributor tier. What's your User ID (from Settings -> API)?

**Comment by ojeytonwilliams** [comment]
Cool.  My ID is 24103022-40d6-4888-939f-2778926c4ba5

**Comment by Alys** [comment]
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!
