### PR TITLE
Client: remove unnecessary API calls + members fixes

### LINKED ISSUE #9242: Guild Notifications and Party Notifications sometimes do not automatically clear.
Notifications for Guild and Party messages don’t reliably clear when you click them and go to the guild/party they are from. I’m pretty sure that Party never clears, and Guild notifications don’t clear if you go from one Guild to another, but we should definitely carefully investigate.

### LINKED ISSUE #12181: Searching party members via "View Party" in header fails ("unhandled promise rejection")
From Report a Bug:

> _Jubineo @crThiago (12601b79-cf8e-44b7-94b9-2bafc97adc16): "hi guys, I found a bug, when I try search anything in group popup nothing happening.
> https://snipboard.io/THaWgo.jpg"_ 
> 
> 
> _Drandaerfin @healingjourneyman (c4d64716-9f93-4356-a436-0df52dbf44d5): "[@crThiago](/profile/12601b79-cf8e-44b7-94b9-2bafc97adc16) I can reproduce it, but only if I click on `View Party` in the header.
> When going to the Party page, and clicking on Member List, then filtering works."_

Confirmed in Chrome and Firefox; here's a dump of my console log:

> app.9c85943c.js:1 Unhandled promise rejection: TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
> window.onunhandledrejection @ app.9c85943c.js:1
> app.9c85943c.js:1 Full info: PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
>     at https://habi…, type: "unhandledrejection", target: Window, …}
> window.onunhandledrejection @ app.9c85943c.js:1
> app.9c85943c.js:1 Uncaught (in promise) TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
>     at app.9c85943c.js:1
>     at u (chunk-vendors.8a5845dd.js:59)
>     at Generator._invoke (chunk-vendors.8a5845dd.js:59)
>     at Generator.S.forEach.t.<computed> [as next] (chunk-vendors.8a5845dd.js:59)
>     at r (chunk-vendors.8a5845dd.js:66)
>     at s (chunk-vendors.8a5845dd.js:66)
>     at chunk-vendors.8a5845dd.js:66
>     at new Promise (<anonymous>)
>     at chunk-vendors.8a5845dd.js:66
>     at a.searchMembers (app.9c85943c.js:1)
> (anonymous) @ app.9c85943c.js:1
> u @ chunk-vendors.8a5845dd.js:59
> (anonymous) @ chunk-vendors.8a5845dd.js:59
> S.forEach.t.<computed> @ chunk-vendors.8a5845dd.js:59
> r @ chunk-vendors.8a5845dd.js:66
> s @ chunk-vendors.8a5845dd.js:66
> (anonymous) @ chunk-vendors.8a5845dd.js:66
> (anonymous) @ chunk-vendors.8a5845dd.js:66
> searchMembers @ app.9c85943c.js:1
> searchTerm @ app.9c85943c.js:1
> nr.run @ chunk-vendors.8a5845dd.js:7
> Zn @ chunk-vendors.8a5845dd.js:7
> (anonymous) @ chunk-vendors.8a5845dd.js:7
> ue @ chunk-vendors.8a5845dd.js:7
> Promise.then (async)
> oe @ chunk-vendors.8a5845dd.js:7
> pe @ chunk-vendors.8a5845dd.js:7
> tr @ chunk-vendors.8a5845dd.js:7
> nr.update @ chunk-vendors.8a5845dd.js:7
> mt.notify @ chunk-vendors.8a5845dd.js:7
> set @ chunk-vendors.8a5845dd.js:7
> rr.set @ chunk-vendors.8a5845dd.js:7
> input @ app.9c85943c.js:1
> ne @ chunk-vendors.8a5845dd.js:7
> n @ chunk-vendors.8a5845dd.js:7
> Xi.o._wrapper @ chunk-vendors.8a5845dd.js:7
> app.9c85943c.js:1 Unhandled promise rejection: TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
> window.onunhandledrejection @ app.9c85943c.js:1
> app.9c85943c.js:1 Full info: PromiseRejectionEvent {isTrusted: true, promise: Promise, reason: TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
>     at https://habi…, type: "unhandledrejection", target: Window, …}
> window.onunhandledrejection @ app.9c85943c.js:1
> app.9c85943c.js:1 Uncaught (in promise) TypeError: t.$store.state.memberModalOptions.fetchMoreMembers is not a function
>     at app.9c85943c.js:1
>     at u (chunk-vendors.8a5845dd.js:59)
>     at Generator._invoke (chunk-vendors.8a5845dd.js:59)
>     at Generator.S.forEach.t.<computed> [as next] (chunk-vendors.8a5845dd.js:59)
>     at r (chunk-vendors.8a5845dd.js:66)
>     at s (chunk-vendors.8a5845dd.js:66)
>     at chunk-vendors.8a5845dd.js:66
>     at new Promise (<anonymous>)
>     at chunk-vendors.8a5845dd.js:66
>     at a.searchMembers (app.9c85943c.js:1)

To reproduce: click on "view party" in the header, type a couple of letters into the search bar.

### PR DESCRIPTION
**Pull request by paglias**
### group plans
- [x] only load once?

### world state

- [x] `world-state` is loaded every time the notification panel or some shops are opened. Can cache?
- [x] tests for async resource changes

### groups and challenge members
- [x] loading spinner
- [ ] loading spinner color and spacing
- [x] challenges with 0 members
- [x] challenge close / select winner
- [x] members modal ui
- [x] groups members should be loaded only when clicking `view members`
- [x] for parties they're already loaded on page load, use store?
- [x] challenge members should be loaded only when clicking `view members`
- [x] fix #12181 
- [x] accepting party invitation header isn't updated until page refreshed - user not synced on join + partyMembers in header not updated?
- [x] header: clicking on show party members the first time results in 3 requests for the invite route

### misc 
- [x] fix #9242
- [x] fix event listeners
- [x] double hp loss notification after cron (one from cron notification and one from userHp watcher)
- [x] https://github.com/vuejs/vue/issues/7323 in achievements/chooseClass 
Schermata 2020-05-20 alle 12 31 05

### CODE REVIEW

File: website/client/src/store/getters/worldState.js [hunk 1]
```diff
@@ -0,0 +1,29 @@
+export function brokenSeasonalShop (store) {
+  const worldState = store.state.worldState.data;
+
+  return worldState
+    && worldState.worldBoss
+    && worldState.worldBoss.extra
+    && worldState.worldBoss.extra.worldDmg
+    && worldState.worldBoss.extra.worldDmg.seasonalShop;
```
Comment (benkelaar) [inline website/client/src/store/getters/worldState.js]: Perhaps use https://lodash.com/docs/4.17.15#get instead? So that would be something like:

```suggestion
  // Use lodash#get to allow for every level being nullable
  return lodash.get(worldState, 'worldBoss.extra.worldDmg.seasonalShop');
```

Comment (paglias) [reply website/client/src/store/getters/worldState.js]: It's a bit nicer but I don't think it's worth introducing the dependency. Also in future we should be able to use this https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

Comment (benkelaar) [reply website/client/src/store/getters/worldState.js]: Elvis is indeed the modern way to do this. Perhaps introduce a private method along the lines of `function getWorldDamage(worldState, type)` to reduce the duplication?

Comment (paglias) [reply website/client/src/store/getters/worldState.js]: Fixed in https://github.com/HabitRPG/habitica/pull/12179/commits/a89c436c400be7d862480b84ac0f4ba2c14714aa
