### PR TITLE
FIX: Challenge Creation without Group not found error

### LINKED ISSUE #10228: creating a challenge when not in a party shows you the "Group not found or you don't have access" error
If you are not in a party and you start to create a new challenge, as soon as the challenge creation form opens, you see the error message "Group not found or you don't have access" in a red snackbar notification. Server logs show that the error is being thrown from the `GET /api/v3/groups/party` command (which needs to be run to find the name of your party for the case when you are in one). 

That error message should not be visible to the user. Either the code should suppress the user-visible notification or it should check if the user has a value for `party._id` before trying to do the GET.

~I'll leave this as suggestion-discussion for a few days for staff to weigh in on which fix they think is best.~

This isn't just a cosmetic error. It stops the player from creating "Public Challenges" (i.e., Tavern challenges to use the old terminology) because the "Public Challenges" entry doesn't appear in the "Add to" drop-down after the party error is thrown.

### PR DESCRIPTION
**Pull request by negue**
prevent loading the party, if the user isn't part of one

fixes #10228

### CODE REVIEW

File: website/client/components/challenges/challengeModal.vue [hunk 1]
```diff
@@ -317,14 +317,17 @@ export default {
...
-      await this.$store.dispatch('party:getParty');
-      const party = this.$store.state.party.data;
-      if (party._id) {
-        this.groups.push({
-          name: party.name,
-          _id: party._id,
-          privacy: 'private',
-        });
+
+      if (this.user.party) {
```
Comment (paglias) [inline website/client/components/challenges/challengeModal.vue]: I think this should also check `this.user.party._id` as `user.party` always exist

Comment (paglias) [inline website/client/components/challenges/challengeModal.vue]: I think this should also check this.user.party._id as user.party always exist

**Review by paglias — CHANGES_REQUESTED** [review]

File: website/client/components/challenges/challengeModal.vue (hunk 1 above)
Comment (negue) [reply website/client/components/challenges/challengeModal.vue]: it didn't exist for my test user, or it did exist but it never passed the if statement, I'll add the _id check

**Review by paglias — APPROVED** [review]
