### PR TITLE
Api v3 party quest fixes

### LINKED ISSUE #7317: [API v3]Cannot accept/reject quest from Party interface
General Info
- UUID: 
- Browser: Chrome
- OS:  Win10
### Description

Accept/Reject buttons next to Ian do not work. They get the blue outline highlight, but do not do anything. Have to refresh page to get the quest invite pop-up again.

### PR DESCRIPTION
**Pull request by TheHollidayInn**
#7317
#7332
#7326
#7330
#7329
#7296
### Changes

---

UUID:

### CODE REVIEW

File: website/client/js/controllers/partyCtrl.js [hunk 1]
```diff
@@ -183,6 +186,7 @@ habitrpg.controller("PartyCtrl", ['$rootScope','$scope','Groups','Chat','User','
       $scope.questForceStart = function(){
         Quests.sendAction('quests/force-start')
           .then(function(quest) {
+            console.log(quest)
```
Comment (crookedneighbor) [inline website/client/js/controllers/partyCtrl.js:189]: console.log

Comment (paglias) [inline website/client/js/controllers/partyCtrl.js:189]: I've removed it when I merged
Il 18 mag 2016 1:52 PM, "Blade Barringer" notifications@github.com ha
scritto:
