### PR TITLE
Store original quantities, to avoid reordering in Inventory Items screen

### LINKED ISSUE #12040: When hatching the egg at the end of a row, eggs rearrange
Report from Geolojess: 
> Also, found another display bug! When I'm on the items page and hatching eggs, if I hatch the egg at the very end of the row, then that egg and the eggs in the second row will all switch places! But ONLY if you hatch the one on the end of the first row. I tested to see if hatching any of the eggs in the second row produced the same results but they did not. Only discovered this because I was hatching hippos and when I went to hatch a second I ended up hatching a cuttlefish, because the hippo egg moved! XD (and I'll keep the cuttlefish, no big deal!)

To reproduce...

1. Egg at the end of the row is hatchable:
image

2. Hatch it.

3. It has swapped with an egg from the row below.
image

_EDIT by Alys 2020-05-13:_

As described in the comments below, reordering happens because the numbers of the items change (items are sorted by how many you own). It's disconcerting though when you're still using them.

**The desired fix is that the items should not change order while looking at the page.**
**Reordering should only happen if you reload the page, or sync, or go to another page then back again.**

### PR DESCRIPTION
**Pull request by fmaximus**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes: #12040

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Create a quantity snapshot when loading the screen.
Sort based on the snapshot after updates.

Items_before

Hatching a Cotton Candy Pink Parrot

Items_after

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: c4d64716-9f93-4356-a436-0df52dbf44d5

### CODE REVIEW

File: website/client/src/components/inventory/items/index.vue [hunk 1]
```diff
@@ -458,12 +465,22 @@ export default {
...
+            itemsArray.sort((a, b) => quantitySnapshot[b.key] - quantitySnapshot[a.key]);
+          } else {
+            itemsArray.sort((a, b) => b.quantity - a.quantity);
+          }
+
+          if (quantitySnapshot === null) {
+            this.quantitySnapshot[groupKey] = Object.fromEntries(
+              itemsArray.map(item => [item.key, item.quantity]),
+            );
+          }
```
Comment (benkelaar) [inline website/client/src/components/inventory/items/index.vue]: You can avoid the initial branching if you invert the order
```suggestion
          const quantitySnapshot = this.quantitySnapshot[groupKey] || Object.fromEntries(
            itemsArray.map(item => [item.key, item.quantity]),
          );
          itemsArray.sort((a, b) => quantitySnapshot[b.key] - quantitySnapshot[a.key]);
          this.quantitySnapshot[groupKey] = quantitySnapshot;
```

File: website/client/src/components/inventory/items/index.vue [hunk 2]
```diff
@@ -458,12 +465,15 @@ export default {
           }
         });
 
-        itemsArray.sort((a, b) => {
-          if (this.sortBy === 'quantity') {
-            return b.quantity - a.quantity;
-          } // AZ
-          return a.text.localeCompare(b.text);
-        });
+        if (this.sortBy === 'quantity') {
```
Comment (paglias) [inline website/client/src/components/inventory/items/index.vue:468]: can we add a comment explaining the reasoning behind the need for the quantity snapshot?

File: website/client/src/components/inventory/items/index.vue [hunk 3]
```diff
@@ -458,12 +465,15 @@ export default {
...
+          const quantitySnapshot = this.quantitySnapshot[groupKey] || Object.fromEntries(
```
Comment (paglias) [inline website/client/src/components/inventory/items/index.vue:470]: Given an user can have a big number of items and the rendering is already a bit slow, instead of calculating the snapshot here by iterating on the existing `itemsArray` could we do it in the `each` block at line 445 where we already iterate on the items?

**Review by paglias — COMMENTED** [review]
it's working as expected but left two small comments

File: website/client/src/components/inventory/items/index.vue (hunk 3 above)
Comment (fmaximus) [reply website/client/src/components/inventory/items/index.vue:470]: I tried moving it inside, but it doesn't seem to improve the rendering.
I've added `console.time` and `console.timeEnd` around the each + sort:
| time (ms)                | size | develop | PR   | proposal |
|-----------------|------|---------|------|----------|
| eggs            | 8    | 10.8    | 5.5  | 12.8     |
| hatchingPotions | 13   | 12.6    | 12.8 | 14.0     |
| food            | 5    | 4.3     | 3.0  | 2.7      |
| special         | 4    | 3.0     | 1.8  | 5.9      |
| quests          | 2    | 1.8     | 1.0  | 2.6      |

Adding it inside the each, requires the use of an if block,
to check if it's already cached. 
Doing the check for every element seems slower,
than running it twice, and doing the check once.
Once a snapshot is available, the time will drop even further.

Also notice that by pulling up the `sortBy` check out of the comparator,
performance has already been improved.

Comment (paglias) [reply website/client/src/components/inventory/items/index.vue:470]: thanks for checking this, let's leave this as it is then

File: website/client/src/components/inventory/items/index.vue (hunk 2 above)
Comment (paglias) [reply website/client/src/components/inventory/items/index.vue:468]: If you can add a comment here I'll then merge it , thanks :)

**Comment by paglias** [comment]
thanks! noted towards your 3rd tier
