### PR TITLE
Fixed block icon not showing in profile modal.

### LINKED ISSUE #9626: "Block" button in User Profile should be an icon
**Current**
image

**Approved Design**
image

If you're interested in picking up this issue, please leave an email address to be invited to our Zeplin project.

### PR DESCRIPTION
**Pull request by xXenithx**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes https://github.com/HabitRPG/habitica/issues/9626

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
- Fixed the ordering of the button layout and the block and add icon not showing.
- Changed the color of icons to match the color `#686274`.
- Fixed tooltips not appearing when hovering over the buttons.

screenshot-2017-12-4 habitica
screenshot

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: aa84dd32-29d2-4dc6-9e4c-ab9005f01fe9

### CODE REVIEW

File: website/client/components/userMenu/profile.vue [hunk 1]
```diff
@@ -3,18 +3,18 @@ div
   b-modal#profile(title="Profile", size='lg', :hide-footer="true")
     div(slot='modal-header')
       .profile-actions
-        button.btn.btn-secondary(@click='sendMessage()')
+        button.btn.btn-secondary(:title="$t('sendMessage')", @click='sendMessage()', v-b-tooltip.hover.left="")
```
Comment (paglias) [inline website/client/components/userMenu/profile.vue]: so when a :title attribute is defined the tooltip can be emtpy?

File: website/client/assets/svg/positive.svg [hunk 2]
```diff
@@ -1,3 +1,3 @@
 <svg xmlns="http://www.w3.org/2000/svg" width="10" height="10" viewBox="0 0 10 10">
-    <path fill-rule="evenodd" d="M6 4V0H4v4H0v2h4v4h2V6h4V4H6z"/>
```
Comment (paglias) [inline website/client/assets/svg/positive.svg]: so there's a small problem here because if you set the fill parameter directly on the SVG, it's impossible to override it. So what we've been doing, when an icon is used in different colors, is to remove the fill parameter from the .svg file and specify the color as a css rule for the `.svg-icon` element

**Review by paglias — DISMISSED** [review]

File: website/client/components/userMenu/profile.vue (hunk 1 above)
Comment (xXenithx) [reply website/client/components/userMenu/profile.vue]: Hmm I was going off what @negue had suggested to get the tooltip to function properly. Should I put in what the tooltip would output?

File: website/client/assets/svg/positive.svg (hunk 2 above)
Comment (xXenithx) [reply website/client/assets/svg/positive.svg]: Okay, so I should make a css rule for .svg-icon in profile.vue then?

File: website/client/components/userMenu/profile.vue (hunk 1 above)
Comment (negue) [reply website/client/components/userMenu/profile.vue]: `v-b-tooltip.hover.left` just can't be written in the syntax, cause its an empty attribute, `:title` is used as the tooltip value

Comment (paglias) [reply website/client/components/userMenu/profile.vue]: Yeah, but cannot it be used like here https://github.com/HabitRPG/habitica/blob/develop/website/client/components/memberDetails.vue#L23 ?

File: website/client/assets/svg/positive.svg (hunk 2 above)
Comment (paglias) [reply website/client/assets/svg/positive.svg]: Yes, in this case since there are multiple icons you'll want to use a more specific class like `.remove-icon`,  ...

File: website/client/components/userMenu/profile.vue (hunk 1 above)
Comment (negue) [reply website/client/components/userMenu/profile.vue]: oh, I just took the bootstrap-vue docs for it

@xXenithx  could you try if it works the same as in memberDetails? if so, please use that syntax, looks much cleaner^^

Comment (xXenithx) [reply website/client/components/userMenu/profile.vue]: @paglias @negue Yeah just changed it according to memberDetails and it does in fact work. I'll commit the changes to the PR.

**Comment by SabreCat** [comment]
Merged! @xXenithx, we will use this in a staging environment for a bit to ensure no unexpected side effects have occurred, but you will see this live in a few days. I've awarded you your first Blacksmith contributor tier for this effort, thank you! Note that subsequent tiers require increasing amounts of effort from one to the next, so tier 2 may require multiple PRs or a larger PR to attain. But keep helping out and we will express our gratitude accordingly!
