### PR TITLE
Only includes backticks if they haven't been already included. Fixes …

### LINKED ISSUE #11202: quest system messages sometimes have double backticks (rage attack, etc)
As reported by @Chandramani_Adil (58de0b72-3af8-4f2a-b9a1-f7d196b29757), some quest system messages are incorrectly formatted because they have nested backticks:

index

It happens when the messages already contain backticks in the translatable strings. The code that displays the messages always inserts its own backticks around the translatable strings. It was reported for a boss_rage message but other types of system messages are also affected. I've included details below.

Perhaps the easiest fix for this would be for the code that displays the messages to first check if there's at least one backtick already in the message and then not display it. ~`I'll leave this issue as suggestion-discussion for a few days for the staff to comment if they wish, and then if there's no objections I'll mark it as help wanted for that fix.`~

This is the code that inserts the backticks:
https://github.com/HabitRPG/habitica/blob/e4b2ef65993f03c1acfc88d8923363ebf917b028/website/server/libs/chat/group-chat.js#L36-L106

For example, for the exact instance shown in the screenshot above:
https://github.com/HabitRPG/habitica/blob/e4b2ef65993f03c1acfc88d8923363ebf917b028/website/server/libs/chat/group-chat.js#L50
(For those new to JavaScript, the outer backticks on that line are just for quoting the string in a way that allows variable interpolation; the inner backticks which are escaped by backslashes are the ones that are printed as part of the string.)

Some or all of the relevant strings are in `website/common/locales/en/questsContent.json` and this is the one shown in the screenshot:
https://github.com/HabitRPG/habitica/blob/e4b2ef65993f03c1acfc88d8923363ebf917b028/website/common/locales/en/questsContent.json#L399

This issue can't be fixed by removing the backticks from the translatable strings because for some examples, only part of the string is formatted with backticks:
https://github.com/HabitRPG/habitica/blob/e4b2ef65993f03c1acfc88d8923363ebf917b028/website/common/locales/en/questsContent.json#L436

In any case where the translatable string includes one or more backticks, the code that displays that string should not insert its own backticks.

In case it helps, this is the relevant data for the quest "system" message stored in the `chats` collection in the database:
```
{
    "_id": "1cb8587f-740e-46e4-ae8f-ef07cca1c05b",
    "text": "`Magical Axolotl uses AXOLOTL REGENERATION!`\n\n`A curtain of colorful bubbles obscures the monster for a moment, and when it clears, some of its wounds have vanished!`",
    "info": {
        "type": "boss_rage",
        "quest": "axolotl"
    },
    "timestamp": "2019-06-01T04:11:34.396Z",
    "uuid": "system",
},
```

### PR DESCRIPTION
**Pull request by Scens**
…the problem.

[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11202 
Screenshot 2019-06-29 at 19 04 38

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Affects only messages created by translateMessage function in /website/server/libs/chat/group-chat.js. There doesn't seem to be any other case of displaying double backticks.

Code only includes backticks if they haven't been already included (because they might have been hardcoded in questContent.json).

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: dd59e7c1-b76a-466e-b301-783b852da699

### CODE REVIEW

**Comment by paglias** [comment]
Hi @Scens  and thanks for the PR! Sorry for the delay here but we'll review the pr soon

File: website/server/libs/chat/group-chat.js [hunk 1]
```diff
@@ -35,73 +35,76 @@ export function translateMessage (lang, info) {
...
-      msg = `\`${quests[info.quest].boss.desperation.text(lang)}\``;
+      msg = `${quests[info.quest].boss.desperation.text(lang)}`;
       break;
 
     case 'claim_task':
       msg = `${shared.i18n.t('userIsClamingTask', {username: info.user, task: info.task}, lang)}`;
       break;
   }
 
+  if (!msg.includes('\`')) {
```
Comment (paglias) [inline website/server/libs/chat/group-chat.js]: is the backslash here necessary?

File: website/server/libs/chat/group-chat.js [hunk 2]
```diff
@@ -35,73 +35,76 @@ export function translateMessage (lang, info) {
 
   switch (info.type) {
     case 'quest_start':
-      msg = `\`${shared.i18n.t('chatQuestStarted', {questName: questScrolls[info.quest].text(lang)}, lang)}\``;
+      msg = `${shared.i18n.t('chatQuestStarted', {questName: questScrolls[info.quest].text(lang)}, lang)}`;
```
Comment (paglias) [inline website/server/libs/chat/group-chat.js]: this looks good but here like in other messages below given that the string is only the result of the i18n.t call it's not necessary to use the backslashes, so

> msg = `${shared.i18n.t('chatQuestStarted', {questName: questScrolls[info.quest].text(lang)}, lang)}`;

can be

> msg = shared.i18n.t('chatQuestStarted', {questName: questScrolls[info.quest].text(lang)}, lang);

**Review by paglias — CHANGES_REQUESTED** [review]
left two small comments!

**Comment by Scens** [comment]
> left two small comments!

Thanks! You are right, I have taken care of these. I've tested this again and everything works fine.

**Comment by SabreCat** [comment]
Thanks, @Scens! This will go live on the production site around this time next week. Credited toward your second Blacksmith tier!
