### PR TITLE
fix drawer-slider carousel function && convert to pointer logic (fixes #9366 AND #9638)

### LINKED ISSUE #9366: Incorrect Divider in Food Quick Inventory
No matter how many times you cycle through the food in the quick inventory, the item on the right-hand side is always separated out slightly. The idea is that there is a separation that loops around like a conveyor belt. So if you have 10 items, the separator only shows up between item 10 and item 1. Right now, it just separates out whichever item is on the right-hand side. 

We had envisioned it working more like the "Multiple Items" slider demo seen here: http://kenwheeler.github.io/slick/

The divider should only appear between the last item and the first item as a visual identifier that you're back to the beginning, and there should not be a gap.

The divider:
screen shot 2017-11-01 at 9 42 34 pm

What it currently does:

screen shot 2017-11-01 at 9 42 41 pm

It should cycle through like this:

screen shot 2017-11-01 at 9 42 50 pm

### PR DESCRIPTION
**Pull request by matchajune**
[x]: Fixes https://github.com/HabitRPG/habitica/issues/9366 && https://github.com/HabitRPG/habitica/issues/9638

### Changes
[x]: Delete logic for paging for `drawerSlider.vue` and implement pointer logic. The pointer will act as the index of the array `this.items` and take `this.itemsPerPage()` elements.
[x]: Handle logic to display divider correctly.
[x]: Evenly space out `this.items` for the items being shown.
[x]: Create a new prop in `drawerSlider.vue` called `itemType` and watch for its value to change and reset `this.pointer` to 0 if it changes. This will remedy any false-negatives of not showing a user's items.

----
UUID: dd16c270-1d6d-44bd-b4f9-737342e79be6

### CODE REVIEW

File: website/client/components/ui/drawerSlider.vue [hunk 1]
```diff
@@ -115,45 +117,58 @@
...
+      showItems () {
+        let items = this.items;
+        let pointer = this.pointer;
+        let itemsPerPage = this.itemsPerPage();
+        let firstSlice = items.slice(pointer, pointer + itemsPerPage);
+
+        if (firstSlice.length === itemsPerPage) {
+          return firstSlice;
+        } else {
+          let getRemainderItems = Math.abs(itemsPerPage - firstSlice.length);
```
Comment (negue) [inline website/client/components/ui/drawerSlider.vue]: `itemsPerPage` and `firstSlice.length` shouldn't be less than 0, so I guess there is no need for `Math.abs`

File: website/client/components/ui/drawerSlider.vue [hunk 2]
```diff
@@ -115,45 +117,58 @@
...
-          this.currentPage = 0;
+          this.pointer = this.items.length - 1;
         }
       },
-
       itemsPerPage () {
         return Math.floor(this.currentWidth / (this.itemWidth + this.itemMargin));
       },
+      shouldAddVerticalLine (item) {
+        return this.items[this.itemsPerPage() - 1] === item && this.pointer !== 5;
```
Comment (negue) [inline website/client/components/ui/drawerSlider.vue:170]: why the `pointer !== 5` check ?

**Review by negue — CHANGES_REQUESTED** [review]
its LGTM :+1: 

only have the two requests ^^

File: website/client/components/ui/drawerSlider.vue (hunk 2 above)
Comment (matchajune) [reply website/client/components/ui/drawerSlider.vue:170]: The checker is to not show the pointer as so:

screen shot 2017-12-14 at 4 28 10 pm

**Review by negue — APPROVED** [review]

**Comment by SabreCat** [comment]
Thank you, @matchajune! Noted toward your third contributor tier!

**Comment by paglias** [comment]
@matchajune hey, I think we found some issues with this PR, in particular some items like saddles are shown twice and the direction of the scrolling in the quick inventory seems reversed, so clicking on the forward button actually does the opposite

File: website/client/components/ui/drawerSlider.vue [hunk 3]
```diff
@@ -115,45 +117,58 @@
...
-        });
+      showItems () {
+        let items = this.items;
+        let pointer = this.pointer;
+        let itemsPerPage = this.itemsPerPage();
+        let firstSlice = items.slice(pointer, pointer + itemsPerPage);
+
+        if (firstSlice.length === itemsPerPage) {
+          return firstSlice;
+        } else {
```
Comment (paglias) [inline website/client/components/ui/drawerSlider.vue:132]: I think this else code shouldn't run if the total number of items is < firstSlice.length

**Comment by paglias** [comment]
I think I've fixed them here https://github.com/HabitRPG/habitica/pull/9819

**Comment by matchajune** [comment]
Thanks for fixing the issues @paglias
