### PR TITLE
Fixed mp rounding

### LINKED ISSUE #5233: MP rounds down, MP alerts round up...
It makes sense for MP to round down... if it rounded up, it'd look like you could afford skills you can't.

However, MP alerts round up, which makes for some surprising total amounts of MP now. This is especially apparent because of the 1/4 amounts Habits give you.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/15592221-mp-rounds-down-mp-alerts-round-up?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Fixes #5233

### CODE REVIEW

File: website/client/mixins/notifications.js [hunk 1]
```diff
@@ -46,7 +46,7 @@ export default {
       this.notify(parsedMarkdown, 'info');
     },
     mp (val) {
-      this.notify(`${this.sign(val)} ${this.round(val)}`, 'mp', 'glyphicon glyphicon-fire', this.sign(val));
+      this.notify(`${this.sign(val)} ${this.round(val, 2)}`, 'mp', 'glyphicon glyphicon-fire', this.sign(val));
```
Comment (Alys) [inline website/client/mixins/notifications.js]: This needs to always round down, never round up so that it matches the type of rounding used in the mana stats bar. For example, 1.19 should be changed to 1.1 (not 1.2). I think the `this.round()` function is the one below, in which case it will round up for digits above 5, so that's not what we want.
https://github.com/HabitRPG/habitica/blob/f810fff6fc7ac4c0bb263e552d5892ab7b0ddcab/website/client/libs/notifications.js#L45-L47

Also displaying one decimal place instead of two would be best. Basically, the round() function here needs to be replaced with one that just truncates after one decimal place.

Comment (TheHollidayInn) [reply website/client/mixins/notifications.js]: This actually truncates for digits greater than 2 which ends up rounding down. 1.234 becomes 1.23. were you getting different results locally?

Comment (Alys) [reply website/client/mixins/notifications.js]: I didn't test locally because I can't think of how to easily control the amount of mana given by a task but I was extrapolating behaviour from the toFixed docs. 1.234 will become 1.23 (which is good) but 1.236 will become 1.24. We want rounding down in every case (so for our use, 1.26 would need to become 1.3).

Comment (TheHollidayInn) [reply website/client/mixins/notifications.js]: Ah I didn't see you reference the docs. I see now that toFixed is the issue: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toFixed#Using_toFixed

**Comment by SabreCat** [comment]
Possible cause of https://github.com/HabitRPG/habitica/issues/10623 ?

**Comment by TheHollidayInn** [comment]
Ah yep. I'll fix that
