### PR TITLE
PR to fix: Disallow line breaks in display names

### LINKED ISSUE #11946: Disallow line breaks in display names
A user managed to put a line break in their display name:

image

This seems like a bad idea, so the desired fix is to disallow any linebreaks in users' display names.

### PR DESCRIPTION
**Pull request by Amberlisi**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: #11946
Fixes #11946

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
This PR would make changes to 3 files:
1. settings.json - Needed for a new error message when a user tries to set their display name using a backslash followed by the letter N
2. validation.js - To add a validation check for the occurrence of a backslash followed by the letter N - Requires checking for '\\\n' and '\\n' because some systems automatically escape characters
3. index.js - To get the validator in the UI to check for the presence of a backslash followed by the letter N, and to prevent the user from updating their name if a backslash followed by the letter N is found

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 74ad4bd2-9de5-43f7-8efd-cfd684f47374

### CODE REVIEW

File: website/server/libs/user/validation.js [hunk 1]
```diff
@@ -15,6 +15,13 @@ export function nameContainsSlur (username) {
   return false;
 }
 
+export function nameContainsNewline (username) {
+  if (username.includes('\n') || username.includes('\\n')) {
```
Comment (paglias) [inline website/server/libs/user/validation.js]: @Amberlisi can you remind me why we're checking both \n and \\n?

**Review by paglias — COMMENTED** [review]
I've left a comment but it's looking good, we would need to add some tests covering this new check though. Let me know if you need help with them

File: website/server/libs/user/validation.js (hunk 1 above)
Comment (Amberlisi) [reply website/server/libs/user/validation.js]: When changing your username in the web UI, it automatically escapes the backslash N. So it doesn't see it as a newline. Which is why you have to search for \\\n

The API works differently. It doesn't automatically escape it, so you have to check for a newline which is \\n.

Not sure if that explanation makes sense

Comment (paglias) [reply website/server/libs/user/validation.js]: Hmm I see but the moment is escaped (so the api gets `\\n`) is this an issue anymore? since it's escaped it shouldn't result in a visible new line. Not a big deal but I'm not sure the second check is necessary

Comment (Amberlisi) [reply website/server/libs/user/validation.js]: This depends on what we want the end functionality to be.

Do we want the users to be able to set their name to something that includes a \ + n using the UI, like so?
image

Or should the ability to do that in the UI be restricted just like it would be in the API? I would think so, for consistency. If something isn't allowed in the API, I don't think we would want to allow it anywhere else. That's just my opinion and we can go whichever way is desired

Comment (paglias) [reply website/server/libs/user/validation.js]: > Or should the ability to do that in the UI be restricted just like it would be in the API? 

The UI under the hood uses the API , what we want to prevent here it simply people having actual line breaks (that then get displayed ) in their display name or username, if they have the literal `\n` we don't care as long as it doesn't create a new line

Comment (Amberlisi) [reply website/server/libs/user/validation.js]: If that's the case then the second check can be left out. I'll make that change in a moment. If you could help me figure out how to perform tests for this that would be great

Comment (paglias) [reply website/server/libs/user/validation.js]: For the tests you should update https://github.com/HabitRPG/habitica/blob/develop/test/api/v3/integration/user/PUT-user.test.js#L55 to add a new case covering a profile.name that includes `\n` and add a check that it fails like it's done for the other invalid profile names. 

Something similar will have to be done for the route verifying the validity of a display name here https://github.com/HabitRPG/habitica/blob/develop/test/api/v4/user/auth/POST-user_verify_display_name.test.js with the difference that in this case each different invalid "case" has a separate test (identified by an `it(...)` block) so you'll have to add a new one for `\n`

Comment (Amberlisi) [reply website/server/libs/user/validation.js]: Okay, I added tests. Let me know if I did that right and if not what I need to change. I also removed the second check from the validation.

**Review by paglias — APPROVED** [review]
Everything's looking good! I'll merge it at the end of the week

**Comment by paglias** [comment]
thanks @Amberlisi ! merged and noted towards your 2nd tier
