### PR TITLE
Fix password reset when querying for emails with upcase characters (fixes #9059)

### LINKED ISSUE #9059: password reset process fails if a user's email address has upper-case letters
If a user's email address in Habitica contains any upper-case letters, when they use the password reset form, their account is not given a value for `auth.local.passwordResetCode` and they do not receive a password reset email. This happens even if they enter their email address into the reset form using the exact case that it's stored in in Habitica.

If their email address in their account is changed to all lower case, the password reset form works correctly, no matter whether they enter their email address into the form in the same case as it's stored in Habitica or a different case.

This looks like the code to be changed:
https://github.com/HabitRPG/habitica/blob/136947169b466ed02b12a151c4576c791154a069/website/server/controllers/api-v3/auth.js#L563-L564
The find command should be case-insensitive and the `toLowerCase` won't be needed.

### PR DESCRIPTION
**Pull request by matchajune**
Fixes #9059

### Changes
[x]: When APIv3 was released 2 years ago, email was sanitized with `.toLowerCase()` upon creating a user. However, an inconsistency is currently happening when updating an email: emails submitted to update aren't sanitized.

Therefore, instead of checking for emails consisting of upcase characters before sending a password reset, I fixed updating an email to save as lowercase.

In addition, there is a migration script `20171211_sanitize_emails.js` to update existing Users' emails to lowercase for consistency.

----
UUID: dd16c270-1d6d-44bd-b4f9-737342e79be6

### CODE REVIEW

File: migrations/20171211_sanitize_emails.js [hunk 1]
```diff
@@ -0,0 +1,14 @@
+/*
+  User creation saves email as lowercase, but updating an email did not.
+  Run this script to ensure all lowercased emails in db AFTER fix for updating emails is implemented.
+  This will fix inconsistent querying for an email when attempting to password reset.
+*/
+
+db.users.find().forEach(user => {
```
Comment (Alys) [inline migrations/20171211_sanitize_emails.js]: This would need to filter for users who already have a value for auth.local.email (accounts that use only social media login don't have that), and would also need to update the users in batches to avoid overloading requests to the database. See some of the other migrations scripts for examples (just the more recently updated ones). However you might want to wait for feedback about the overall method first. :)

File: test/api/v3/integration/user/auth/POST-register_local.test.js [hunk 2]
```diff
@@ -288,6 +288,21 @@ describe('POST /user/auth/local/register', () => {
       });
     });
 
+    it('sanitizes email params to a lowercase string before creating the user', async () => {
+      let username = generateRandomUserName();
+      let email = 'ISANEmAiL@GMAIL.coM';
```
Comment (Alys) [inline test/api/v3/integration/user/auth/POST-register_local.test.js]: best to use @example.net here rather than @gmail.com, just in case someone has that email address and doesn't like it being used in github

**Review by Alys — CHANGES_REQUESTED** [review]

**Comment by Alys** [comment]
Interesting approach! There's 17 email addresses that are currently associated with two Habitica accounts each, using different case variants of the addresses. If we go with this approach, we'd need to handle those in some way. I'm happy to look into that further if needed. I'll leave a decision about whether we use this approach to the staff.

**Comment by matchajune** [comment]
Thanks. I will look forward to your reply. In the meantime, I will push a new commit with the change requests!

File: migrations/20171211_sanitize_emails.js (hunk 1 above)
Comment (matchajune) [reply migrations/20171211_sanitize_emails.js]: I will wait for feedback as suggested!

**Comment by paglias** [comment]
@Alys did we reach any decision on this?

**Comment by Alys** [comment]
I didn't hear anything about a decision.

It's occurred to me though that no matter which solution we use for case-insensitive password resets, those 17 users would have trouble if they tried to use the reset, so we'll have to sort them out regardless. I'll pull up the list of users again and I and the other mods will discuss contacting them.

**Comment by TheHollidayInn** [comment]
What issues would those 17 users have? Could we still merge this PR while waiting to contact them?

**Comment by Alys** [comment]
There's only one user left who needs to be considered for this. They have two accounts but have not used Habitica recently from either account. Mods will probably email them to help them with this.

This PR could be merged if it's reviewed, finished, and tested before that one user's case has been resolved.

**Comment by TheHollidayInn** [comment]
Thanks, @alys!

@matchajune looks like Travis found a lint error. Can you fix that?

**Comment by matchajune** [comment]
Thanks for catching the lint error. I will be able to fix that tonight!

File: migrations/20171211_sanitize_emails.js (hunk 1 above)
Comment (Alys) [reply migrations/20171211_sanitize_emails.js]: @matchajune Your suggested method is approved, so this change will be needed before the PR is merged.

**Comment by Alys** [comment]
As a note to admins: The migration script in this PR will need to be run shortly before the change is deployed to production and also shortly afterwards to catch any accounts that were created in the meantime (or just search recent accounts for uppercase in emails - that might be faster than a second run). FYI @SabreCat @TheHollidayInn since you're like to be the ones deploying.

File: migrations/20171211_sanitize_emails.js (hunk 1 above)
Comment (Alys) [reply migrations/20171211_sanitize_emails.js]: It would also be good if the update was performed only when the email address was not already fully lower case. That would speed up the migration.

Comment (matchajune) [reply migrations/20171211_sanitize_emails.js]: I took your comments and combined them to check for emails that don't have at least one capital letter. I'm not 100% certain I've written it correctly and would love feedback before proceeding. Thank you for your patience!

File: migrations/20171211_sanitize_emails.js [hunk 3]
```diff
@@ -0,0 +1,14 @@
+/*
+  User creation saves email as lowercase, but updating an email did not.
+  Run this script to ensure all lowercased emails in db AFTER fix for updating emails is implemented.
+  This will fix inconsistent querying for an email when attempting to password reset.
+*/
+
+db.users.find({'auth.local.email':{$not: /[A-Z]/}}).forEach(user => {
```
Comment (Alys) [inline migrations/20171211_sanitize_emails.js]: Will this actually find addresses that have no capital letters?

File: migrations/20171211_sanitize_emails.js (hunk 1 above)
Comment (Alys) [reply migrations/20171211_sanitize_emails.js]: We should still update the users in batches as mentioned above, rather than trying to do them all at once - that can cause loading problems. Have a look at migrations/20180130_habit_birthday.js - I think that would be a decent example, although if other admins give you a better one, listen to them. :)  

The `query` variable can contain the search for addresses that have upper-case letters.

The `fields` parameter in the `dbUsers.find` command could limit the returned fields to just the email address.

The logic for the `set` variable can be simplified for this - all you need is setting the email address.
As a note to whichever admin runs the script: any errors output by the set command should be saved for examination - errors would happen if a new account had been created with a lower-cased version of an email address in an old account (we've already checked for examples of that but one or two more might be created before this migration is run). 

The `inc` variable and the code that uses it can be deleted.

File: migrations/20171211_sanitize_emails.js (hunk 3 above)
Comment (matchajune) [reply migrations/20171211_sanitize_emails.js]: I fixed the query in order to find all emails that have any capital letters.

**Comment by paglias** [comment]
@SabreCat the migration attached will have to be run when this is deployed

**Comment by paglias** [comment]
@matchajune  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Comment by SabreCat** [comment]
Huh, the migration seems to have been deleted from `develop`? I'll run it from the branch.

**Comment by SabreCat** [comment]
Ah, never mind, found it! Moved to the `archive/2017` directory.
