### PR TITLE
Fix market dropdownmenu default text

### LINKED ISSUE #11423: dropdown menus in Market have no default text
As reported by citrusella:

"The dropdowns for sorting and grouping on the [Shops > Market] page only show the arrow. (As compared to, say, pet or equipment dropdowns showing the text and the arrow.)"

image

For an example of how it should work, see the Inventory > Items page where the "Sort By" menu has the default sort order displayed as soon as you load the page.

### PR DESCRIPTION
**Pull request by saraheisa**
Add text attribute to b-dropdown in filterDropdown component

[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11423
### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:

### CODE REVIEW

**Comment by saraheisa** [comment]
solving issue #11423

File: website/client/src/components/ui/filterDropdown.vue [hunk 1]
```diff
@@ -1,7 +1,9 @@
 <template>
   <span>
     <span class="dropdown-label">{{ label }}</span>
-    <b-dropdown right="right">
+    <b-dropdown
+    :text="(selectedItem.id.includes('sortBy')) ? selectedItem.id.substring(6) : selectedItem.id"
```
Comment (paglias) [inline website/client/src/components/ui/filterDropdown.vue]: this doesn't seem to be using the correct string version but simply the key meaning it won't be translated correctly, seeing this instead of the correct string that would be the capitalized "Warrior"
Schermata 2019-10-31 alle 12 17 58

I mean that the default selection should match the item listed in the dropdown (with the same text and icon)

**Review by paglias — CHANGES_REQUESTED** [review]

File: website/client/src/components/ui/filterDropdown.vue (hunk 1 above)
Comment (saraheisa) [reply website/client/src/components/ui/filterDropdown.vue]: I'm new to vue 
So would you please help me with this
How can I grab the value of the dropdown menu

I found out that "text" attribute returns the same value in the dropdown but it only works for class

Comment (paglias) [reply website/client/src/components/ui/filterDropdown.vue]: I think this is something that might have broken with a recent version of bootstrap vue because the slot is there so it might be a breaking change we missed. @negue any idea? The slot exists here https://github.com/HabitRPG/habitica/pull/11481/files#diff-b7d94aa4b827758be8c8eddcd201c4e4R7 but is not rendered

File: website/client/src/components/ui/filterDropdown.vue [hunk 2]
```diff
@@ -1,7 +1,9 @@
...
+    right="right">
       <span
         slot="text"
```
Comment (paglias) [inline website/client/src/components/ui/filterDropdown.vue]: @prosarahgamal I would try to change `slot="text"` with `slot="button-content"` here and remove your other changes

Comment (saraheisa) [reply website/client/src/components/ui/filterDropdown.vue]: @paglias Thanks a lot for your valuable comments
It works fine now

File: website/client/src/components/ui/filterDropdown.vue (hunk 1 above)
Comment (negue) [reply website/client/src/components/ui/filterDropdown.vue]: @prosarahgamal already found the correct slot name :tada:

@paglias yeah another vue-bootstrap upgrade issue I'll go through other components and see if we still have some removed properties / bindings

**Comment by paglias** [comment]
thanks @prosarahgamal, if you have an Habitica UUID or username I'll be happy to award you a contribution tier

**Comment by saraheisa** [comment]
> thanks @prosarahgamal, if you have an Habitica UUID or username I'll be happy to award you a contribution tier

Yeah sure!
my username @dev_sarah (ba216907-332d-461a-8e41-c1c5d295e4de)

**Comment by paglias** [comment]
@prosarahgamal awarding your contributor tier :)

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!
