### PR TITLE
Translator minor changes fixes #8917

### LINKED ISSUE #8917: Translators suggest minor changes to some locale strings
As noted and/or suggested by translators, some strings may benefit from slight changes:

Key - Suggestion - Reasoning
- [ ] enterprisePlansEmailSubject - should better be static as suggested by @mokovec - confirmed by @SabreCat https://github.com/HabitRPG/habitica/pull/8729#issuecomment-318910450
- [ ] deleteSocialAccountText & incorrectDeletePhrase - need token (variable) for DELETE - translators shouldn't translate this keyword as suggested by @Alys 
- [ ] noSudoAccess -  it will be better to have it static - because it's easy for translators to misunderstand the message (because the message is so cryptic) as suggested by @Alys 
- [ ] userItemsNotEnough - may be rephrased into *You do not have enough <%= type =%>* - as suggested by @Alys 
- [x] armorArmoireYellowPartyDressNotes - doesn't need the "Yellow Party Dress: " beginning - every other hairbow set items are directly starting by "you're perceptive / strong / smart..."

### PR DESCRIPTION
**Pull request by perkyguy**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8917 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Just set the strings to static where needed, or added variables where needed.

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: e8be8049-ac14-401f-89ff-ce0aaa3445b4

### CODE REVIEW

**Comment by perkyguy** [comment]
Edited my PR comment just to match the format. Sorry about that!

File: website/server/middlewares/ensureAccessRight.js [hunk 1]
```diff
@@ -16,7 +16,7 @@ export function ensureSudo (req, res, next) {
   let user = res.locals.user;
 
   if (!user.contributor.sudo) {
-    return next(new NotAuthorized(res.t('noSudoAccess')));
+    return next(new NotAuthorized('You don\'t have sudo access.'));
```
Comment (paglias) [inline website/server/middlewares/ensureAccessRight.js]: Instead of using plain strings could you use `apiMessages`, ( see https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/apiMessages.js and https://github.com/HabitRPG/habitica/search?utf8=%E2%9C%93&q=apimessages&type=) so that the string is not translated but not a plain string either? Thanks and sorry for the delay in reviewing this!

**Review by paglias — DISMISSED** [review]

**Comment by perkyguy** [comment]
@paglias , I added the string into apiMessage and used that for the ensureAccessRight and corresponding tests

**Comment by SabreCat** [comment]
Thanks for this, @perkyguy, and welcome to the ranks of the Blacksmiths! Note that contributor tiers require increasing amounts of effort from one to the next, so tier 2 may require multiple PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!
