### PR TITLE
Fixes #5094 Now show list based on whether or not a search query is defi...

### LINKED ISSUE #5094: When replying to a user, it requires 2 clicks to choose from the list of users
Hello! I noticed this while I was typing out messages to people in the tavern. Whenever you use the @ symbol to start a reply to someone, for example "@Rbrinkley Hello! " , if you try to choose a name from the drop down list the first time you click on a name the name will not appear. 

I am referring to this process here (Names blacked out for privacy)
chatdropdownlisterror

It is only until the second time you try and click that name, a process requiring retyping out the name or at least part of it, then you will be able to click from it and the name will appear.

So the process usually is:
Type out @ symbol **--->** Type out part of name **-->**  List appears **-->** click on intended user**-->** click fails to register **-->** retype entire name or part of name **-->** list appears **-->** click on intended user **-->** click registers and name is transferred to message box **-->** user types out message and sends.

I at first thought it was deliberate. Maybe to prevent accidentally clicking on the wrong name and other things. But I noticed that any name at all you choose from on the list, the first click attempt will not work, but the second attempt will. And every attempt after that will work, so it doesn't seem to be a confirmation click, I think it is just an error or bug involved with the clicking, it gets quite annoying to deal with. 

I'm not sure if this has already been mentioned before, its kinda hard to describe this issue but I just wanted to point it out.

User ID:6f14571c-f2e9-4446-8e4e-591a7a3a42eb

### PR DESCRIPTION
**Pull request by joyheron**
...ned. The autocomplete function from the directive is encapsulated so that it can be called and then the query can be set to null.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Sorry it's taken me so long to review this. Works great!

File: test/spec/groupCtrlSpec.js [hunk 1]
```diff
@@ -149,6 +149,20 @@ describe("Autocomplete controller", function() {
     });
   });
 
+  describe("performCompletion", function() {
+    it('auto complete triggers', function() {
+      scope.autoComplete = function(v) {}; // this function normally will be filled in by the auto-complete directive
```
Comment (crookedneighbor) [inline test/spec/groupCtrlSpec.js:154]: You can just do `scope.autoComplete = sinon.spy()`

I've refactored the test to look like this:

``` js
it('triggers autoComplete', function() {
  scope.autoComplete = sinon.spy();

  var msg = {user: "boo"}; // scope.autoComplete only cares about user
  scope.query = {text: "b"};
  scope.performCompletion(msg);

  expect(scope.query).to.be.eq(null);
  expect(scope.autoComplete.callCount).to.be.eq(1);
  expect(scope.autoComplete).to.have.been.calledWith(msg);
});
```

Whenever possible, it's best to think of the describe and it block as two parts of a sentence, so "performComplete triggers autoComplete" makes more sense than "performCompletion auto complete triggers" (unless Yoda is writing the test, then I guess I can be more lenient :wink:)

I try to keep comments spare in it blocks. The test should be descriptive. In this case, I added the comment for the msg variable because it's a truncated version of the object it's representing, and that's okay because autocomplete only cares about the user.

**Comment by crookedneighbor** [comment]
I want to reiterate, you did really good work. My comments on the test were nit-picky things. 

I've notated this toward your 3rd contributor tier. _Note:_ The higher tiers require more work than the lower tiers. You can [read more about it on the wiki page](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

**Comment by joyheron** [comment]
@crookedneighbor Thanks! =)

**Comment by Rbrinkley** [comment]
Thank you for fixing the issue. I was really bothering me and I'm really glad you were able to fix it. I can't thank you enough for how much better my habitrpg experience will be. I know its just a small thing, but I use the @command a lot and I have to use two clicks so often that it gets really annoying. I really appreciate you doing this. Thank you again.
