### PR TITLE
Corrected recipient email address in reported PM Slack notification - fixes #12256

### LINKED ISSUE #12256: Incorrect email address shown in slack notification when reporting a PM you sent
**Background info** in case it's helpful:
* When a PM is sent from one player to another, each person has their own copy of the message in their inbox. I.e., there's a separate database document for each copy. (You can see examples of this in the json code below.)
* When a player reports a private message (either one that they sent or one that was sent to them), an email is sent to moderators and a notification is sent to a moderators' Slack channel. The email and the notification include the email addresses of the person who sent the PM and the person who received the PM.

**Bug description:**
The information in the email is always correct.
The information in the Slack notification is partly wrong in some cases:
* When the PM is reported by the recipient of the PM, the Slack notification is correct. You can see an example of this in the first screenshot below.
* **When the PM is reported by the person who sent the PM, the email address of the recipient is wrong. Instead of showing the recipient's actual email address, you see the sender's email address.** You can see that in the second screenshot below. The same message is being reported in both screenshots.

In both cases the email address of the PM's sender is reported correctly.

**This is the Slack notification with the correct data, from when the PM was reported by the recipient:**
image

**This is the Slack notification with the wrong recipient email address, from when the PM was reported by the sender:**
image

Below are the database documents for the PM being reported. For clarity, I've removed some fields that aren't as relevant and I've removed the profile links in the `text`. 
(NB in each document, the `sent`, `ownerId`, and `uuid` fields have different values.)

* d904bd62-da08-416b-a816-ba797c9ee265 = User ID for alys
* 98089587-1bbe-4de2-92d3-0bbe76513a3f = User ID for blackgoblingo

**This is the database document for a PM that is reported by the RECIPIENT, corresponding with the first screenshot above:**
```
{
	"_id" : "72c285f0-6afc-4499-9ad5-0cb564487a8c",
	"sent" : false, // this indicates that the PM was RECEIVED by the person who owns this inbox
	"ownerId" : "98089587-1bbe-4de2-92d3-0bbe76513a3f", // the person who owns the inbox (the RECIPIENT for this PM)
	"text" : "This is a test PM sent from @alys to @blackgoblingo",
	"timestamp" : ISODate("2020-05-31T04:18:31.628Z"),
	"uuid" : "d904bd62-da08-416b-a816-ba797c9ee265", // the other person involved in the conversation (the SENDER for this PM)
	"user" : "alys",
	"username" : "alys"
}
```

This is the database document for a PM that is reported by the SENDER, corresponding with the second screenshot above:
```
{
	"_id" : "8d1cafec-e5cd-43c5-ab23-5029311ba8ca",
	"sent" : true, // this indicates that the PM was SENT by the person who owns this inbox
	"ownerId" : "d904bd62-da08-416b-a816-ba797c9ee265", // the person who owns the inbox (the SENDER for this PM)
	"text" : "This is a test PM sent from @alys to @blackgoblingo",
	"timestamp" : ISODate("2020-05-31T04:18:31.639Z"),
	"uuid" : "98089587-1bbe-4de2-92d3-0bbe76513a3f", // the other person involved in the conversation (the RECIPIENT for this PM)
	"user" : "blackgoblingo",
	"username" : "blackgoblingo"
}
```

This is the code that calls functions for sending the email and Slack notification:
https://github.com/HabitRPG/habitica/blob/8d8079209364eceac7c3ae0a6f20d126ac9568fb/website/server/libs/chatReporting/inboxChatReporter.js#L45-L65

This is the Slack notification function:
https://github.com/HabitRPG/habitica/blob/8d8079209364eceac7c3ae0a6f20d126ac9568fb/website/server/libs/slack.js#L110-L170

### PR DESCRIPTION
**Pull request by lsophie**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #12256 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Fixed the recipient email address that is included in the Slack notification sent to reporters when a user reports their own PM. Previously, the `messageUserEmail` was always assigned to be the author's email – if a user reports their own PM, the recipient's email address will falsely display the author's email address in the Slack notification. However, `messageUserEmail` can be the recipient's email if the reporter of the message is also the author of it.  I fixed the code to account for this logic.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: ddd2399a-30f0-4b6a-a2f6-d6731f4621c7

### CODE REVIEW

File: website/server/libs/chatReporting/inboxChatReporter.js [hunk 1]
```diff
@@ -31,7 +31,7 @@ export default class InboxChatReporter extends ChatReporter {
     if (validationErrors) throw validationErrors;
 
     if (this.user.contributor.admin && this.req.query.userId) {
-      this.inboxUser = await User.findOne({ _id: this.req.query.userId });
+      this.inboxUser = await User.findOne({ _id: this.req.query.userId }).exec();
```
Comment (paglias) [inline website/server/libs/chatReporting/inboxChatReporter.js:34]: good catch!

**Review by paglias — APPROVED** [review]
Looking good, thanks @lsophie !

**Comment by paglias** [comment]
@lsophie  thanks for this PR! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!
