### PR TITLE
Fix "Not Participating" filter checkbox on Discover Challenges screen, Fixes #13025

### LINKED ISSUE #13025: "not participating" search/filter checkbox doesn't work in Discover Challenges page
On the [Discover Challenges](https://habitica.com/challenges/findChallenges) page, if you tick the "Not Participating" checkbox (in the Role section of the filters), you see Challenges that you are participating in.

The expected behaviour is that you see only Challenges that aren't currently joined by you.

The same occurs if you tick both "Not Participating" and "Not Owned" so anyone fixing this bug should check that the fix works for that use case too.

_Thanks to @LindyBlues for reporting this!_

### PR DESCRIPTION
**Pull request by lizapritchard**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #13025

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

- Filtering added on the front-end of the "discover challenges" view,  to allow the user to view challenges they _are_ and _are not_ currently participating in. Mimics function in "my challenges" view. 
- Removed "role" filter from "my challenges" and "discover challenges" views (deemed extraneous by @saraolson in #13025 followups)
Screen Shot 2021-04-21 at 10 26 30 AM
Screen Shot 2021-04-21 at 10 26 41 AM

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:  6179e6e4-1070-43a1-b1df-c1aad12a3ef7

### CODE REVIEW

File: website/client/src/components/challenges/findChallenges.vue [hunk 1]
```diff
@@ -171,7 +171,23 @@ export default {
   computed: {
     ...mapState({ user: 'user.data' }),
     filteredChallenges () {
-      return this.challenges;
+      const { filters } = this;
```
Comment (SabreCat) [inline website/client/src/components/challenges/findChallenges.vue]: The code is identical between the two Challenge Vue files, now--could this be abstracted as a mixin?

File: website/client/src/components/challenges/sidebar.vue [hunk 2]
```diff
@@ -34,7 +34,7 @@
           </div>
         </div>
       </filter-group>
-      <filter-group :title="$t('role')">
+      <!-- <filter-group :title="$t('role')">
```
Comment (SabreCat) [inline website/client/src/components/challenges/sidebar.vue]: OK to delete these rather than commenting out. Git history will preserve it if we need to restore it!

File: website/client/src/components/challenges/sidebar.vue [hunk 3]
```diff
@@ -231,6 +244,7 @@ export default {
         categories: this.categoryFilters,
         roles: this.roleFilters,
```
Comment (SabreCat) [inline website/client/src/components/challenges/sidebar.vue]: We can remove role filtering here too

**Review by SabreCat — CHANGES_REQUESTED** [review]
Thanks for your help here! See minor comments in review, but this shouldn't be difficult to move across the finish line!

File: website/client/src/components/challenges/findChallenges.vue (hunk 1 above)
Comment (SabreCat) [reply website/client/src/components/challenges/findChallenges.vue]: We already have the `challengeUtilities` mixin, so it could live there

**Comment by SabreCat** [comment]
One functional thing I'm seeing: selecting _both_ Participating and Not Participating causes the filter to show only the Not Participating challenges. Compare the behavior of the Owned and Not Owned, which if you tick both acts the same as if neither is checked, i.e., not excluding any Challenges from the current list.

**Comment by lizapritchard** [comment]
@SabreCat thanks for the feedback! I think I addressed all of these issues in the new commits, but I was a little unsure about the mixin stuff so there might be some style conventions here that I'm missing

**Comment by SabreCat** [comment]
Looks great! Thanks for the updates! We'll get this into the staging environment and from there to production. Credited toward your second contributor tier!
