### PR TITLE
Fix analytics

### LINKED ISSUE #5473: Gibberish code (Math.floor(user.stats.exp) etc) on homepage / tasks page prevents viewing tasks
Heya.  I have no idea if this is the right place to put this, please let me know if not.  That said, the HabitRPG homepage looks like this for me:

screenshot 2015-06-23 at 8 54 40 pm

If this has already been brought up and fixed, I'm sorry.  Please let me know if you need more info.

Thanks!

_edit by admin:_
# What to do if you experience this bug:

This bug seems to be caused by extensions that block or otherwise affect Google Analytics features (e.g., adblockers, privacy tools, tracker blockers, spyware blockers, etc). We are trying to prevent this happening so that you can keep using those tools. In the meantime, please try any one of the following things (you don't need to do them all):
1. Disable all extensions. This should fix the problem immediately. You can then, if you wish, enable extensions one by one until you find the one(s) that caused the problem.
2. Use HabitRPG in incognito/privacy mode (this will only work if the relevant extension(s) have not been configured to run in incognito mode; if you have configured them to do that, turning off that setting will allow incognito mode to work).
3. Use HabitRPG on another browser that does not have the extensions installed.

The extensions that might be causing the issue could be:  
- Google Analytics Opt-out Add-on
- Avira
- Privacy Badger
- WebGL Inspector
- Adblock
- Adblock Plus
- Disable Anti-Adblock
- and maybe others

These workaround should be only temporary! Once we work out what interaction is causing the problem, we should be able to modify HabitRPG so that you can keep using all extensions, even on HabitRPG itself.

_NB: You do not need to read on below unless you are curious about the details of the investigation._

### PR DESCRIPTION
**Pull request by gisikw**
Fixes #5473 (uses `setTimeout` to take the third-party interaction outside of the Angular event-loop).

Verified using Google Analytics Opt-out Add-on.

### CODE REVIEW

File: test/spec/services/analyticsServicesSpec.js [hunk 1]
```diff
@@ -26,14 +28,16 @@ describe('Analytics Service', function () {
         sandbox.stub(window, 'ga');
       });
 
-      it('sets up user with Amplitude', function() {
+      it.only('sets up user with Amplitude', function() {
```
Comment (crookedneighbor) [inline test/spec/services/analyticsServicesSpec.js:31]: Only? :/

**Comment by crookedneighbor** [comment]
Can you explain why the timeouts fixed the issue? Very curious about it.

File: test/spec/services/analyticsServicesSpec.js (hunk 1 above)
Comment (crookedneighbor) [inline test/spec/services/analyticsServicesSpec.js:31]: Fixed with https://github.com/HabitRPG/habitrpg/commit/2d78f6c838279074201eab49c6c34a3bca814b18

Comment (gisikw) [inline test/spec/services/analyticsServicesSpec.js:31]: Bahhhhhhhhhhhhhh >.<
