### PR TITLE
Give MasterClasser Acheivement on completion of any of the series quests, not just the final.

### LINKED ISSUE #9461: Quest Completionist achievement should not require quests to be completed in order
As reported by Tex Geoffiamson in the Report a Bug guild and as confirmed by Lemoness, there is a bug with how you achieve the "Quest Completionist" achievement ("Completed all sixteen quests in the Masterclasser Quest Series and solved the mystery of the Lost Masterclasser!").

With our current code the achievement is only assessed when Masterclasser Part 4 is assessed: https://github.com/HabitRPG/habitica/blob/0e2b80ef2edec85b978ecac85f18aa41a97ce3bc/website/server/models/group.js#L776-L801

The correct behaviour to get the achievement is that you must complete all 16 quests, BUT you should be able to do them in any order. 

Steps to Reproduce:
   - Party member A completes "Stoïkalm Calamity, Part 1: Earthen Enemies"
   - Party members A & B complete 14 other Masterclasses prerequisite quests other then "Sto?kalm Calamity, Part 1: Earthen Enemies" and "The Mystery of the Masterclassers, Part 4: The Lost Masterclasser"
   - Party members A & B complete "The Mystery of the Masterclassers, Part 4: The Lost Masterclasser"
   - Party member B completes "Stoïkalm Calamity, Part 1: Earthen Enemies"

Current Behavior:
   - ONLY Party members A has "Quest Completionist: Masterclasser Series"

Expected Behavior:
   - Party members A & B has "Quest Completionist: Masterclasser Series"

For anyone who works on this, you can set up appropriate test user accounts without completing all the quests manually by setting the data below in each account in your local install's database. Leave out one of these achievements to make a test account that hasn't yet done all the quests before "The Mystery of the Masterclassers, Part 4".
```
"achievements.quests": {
	"dilatoryDistress1": 1,
	"dilatoryDistress2": 1,
	"dilatoryDistress3": 1,
	"mayhemMistiflying1": 1,
	"mayhemMistiflying2": 1,
	"mayhemMistiflying3": 1,
	"stoikalmCalamity1": 1,
	"stoikalmCalamity2": 1,
	"stoikalmCalamity3": 1,
	"taskwoodsTerror1": 1,
	"taskwoodsTerror2": 1,
	"taskwoodsTerror3": 1,
	"lostMasterclasser1": 1,
	"lostMasterclasser2": 1,
	"lostMasterclasser3": 1,
},
```

## What to do if this bug happens to you

**Anyone who has completed all 16 quests and doesn't have the  "Quest Completionist" achievement can post to the Report a Bug guild to have the achievement given to them.** Please do NOT post to this issue to request that. It's easier for us and faster for you if you post to the Report a Bug guild.

### PR DESCRIPTION
**Pull request by Hus274**
This change checks the user's achievement status and awards the masterClasser achievement upon completion of any of the masterClasser quests, not just the final one.

This pull-request has just pulled the logic from #9595, I'm pushing it here to see the status of the automated tests to try and determine the failure point. It also looks like the organization of the tests have changed since the last run on the related pull requests so this should provide additional data to try and diagnose the intermittent failures.

fixes #9461

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:

### CODE REVIEW

**Comment by Hus274** [comment]
It appears the problem still exists. It's interesting that adding the new masterclasser test causes the original test to fail. Posting the stack trace here for visibility:

```
  1) Group Model
       Instance Methods
         #finishQuest
           gives out super awesome Masterclasser achievement to the deserving:
     AssertionError: expected undefined to deeply equal true
      at _callee82$ (test/api/v3/unit/models/group.test.js:1410:65)
      at tryCatch (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:65:40)
      at GeneratorFunctionPrototype.invoke [as _invoke] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:303:22)
      at GeneratorFunctionPrototype.prototype.(anonymous function) [as next] (node_modules/babel-polyfill/node_modules/regenerator-runtime/runtime.js:117:21)
      at GeneratorFunctionPrototype.tryCatcher (node_modules/bluebird/js/release/util.js:16:23)
      at PromiseSpawn._promiseFulfilled (node_modules/bluebird/js/release/generators.js:97:49)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Promise._fulfill (node_modules/bluebird/js/release/promise.js:638:18)
      at PromiseArray._resolve (node_modules/bluebird/js/release/promise_array.js:126:19)
      at PromiseArray._promiseFulfilled (node_modules/bluebird/js/release/promise_array.js:144:14)
      at Promise._settlePromise (node_modules/bluebird/js/release/promise.js:574:26)
      at Promise._settlePromise0 (node_modules/bluebird/js/release/promise.js:614:10)
      at Promise._settlePromises (node_modules/bluebird/js/release/promise.js:693:18)
      at Async._drainQueue (node_modules/bluebird/js/release/async.js:133:16)
      at Async._drainQueues (node_modules/bluebird/js/release/async.js:143:10)
      at Immediate.Async.drainQueues (node_modules/bluebird/js/release/async.js:17:14)
```

**Comment by Hus274** [comment]
I think I found the problem here. The existing code was calling concat on the promises object but wasn't reassigning the promises object meaning that the new promise was just getting dropped and wasn't completing in time for the test requirements. https://github.com/HabitRPG/habitica/pull/9595/files#diff-b6f239870392ed0ec2a2b73cbebaa699R801

I've changed `promises.concat()` to `promises = promises.concat()`. Resubmitting.

**Comment by Hus274** [comment]
Looks like the API unit tests are now successfully passing which was the problem in the previous PR and duplicated the issue here. This may have actually been contributing to the  tests fragility overall since this path is hit by both the unit and integration tests and the new test just exacerbated the issue. Hopefully this helps the whole system.

**Comment by Hus274** [comment]
Looks like the integration tests failed due to timeouts in unrelated code paths:
```
  2 failing
  1) GET /challenges/:challengeId/members
       supports using req.query.lastId to get more members:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
  
  2) GET /groups/:groupId/members
       supports using req.query.lastId to get more members:
     Error: Timeout of 8000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

This should be ready for review. Let me know if there's anything else I should look into here.

**Comment by Alys** [comment]
I've restarted the tests and their all passing now. Thanks for this, @Hus274 !

File: website/server/models/group.js [hunk 1]
```diff
@@ -786,16 +786,15 @@ function _getUserUpdateForQuestReward (itemToAward, allAwardedItems) {
...
-        return _updateUserWithRetries(userId, updates, ++numTry, query);
-      } else {
-        throw err;
-      }
-    });
+  try {
+    return await User.update(query, updates).exec();
+  } catch (err) {
+    if (numTry < MAX_UPDATE_RETRIES) {
+      return _updateUserWithRetries(userId, updates, ++numTry);
```
Comment (paglias) [inline website/server/models/group.js]: shouldn't query be passed here? Otherwise query will be {} at the second retry an update the user even if it doesn't match anymore?

**Review by paglias — CHANGES_REQUESTED** [review]

File: website/server/models/group.js (hunk 1 above)
Comment (Hus274) [reply website/server/models/group.js]: Good catch, I totally missed that. I’ll fix it up

**Comment by Hus274** [comment]
Fixed this up, should be ready for review again.

**Review by paglias — APPROVED** [review]

**Comment by paglias** [comment]
Hmm I know this actually passed the tests but right now it's always failing

schermata 2018-03-25 alle 16 36 06

**Comment by paglias** [comment]
I'm restarting it once again but I already did it twice

**Comment by Hus274** [comment]
Are you able to replicate this when you run just the group unit tests or does this only happen when running the whole test suite?

I just merged into mainline and ran the group.test.js unit tests file and it fully passed for me.

**Comment by paglias** [comment]
It seems to be failing when running the whole uni tests suite

**Comment by paglias** [comment]
It actually passes for me locally but not on travis

**Comment by Hus274** [comment]
I believe the issue was a missing await on the return value. I pushed it to the branch listed here but it doesn't appear to have updated the commit, I'm assuming because it was already merged. Can you access the changes here?

If not, I can submit another pull request or you can just make the change as it's a single line change. The line here: https://github.com/HabitRPG/habitica/blob/develop/website/server/models/group.js#L888 to `return await Promise.all(promises)`. Can you give that a shot and let me know if that fixes the tests?

**Comment by paglias** [comment]
That worked, thanks!

Il Mar 27 Mar 2018, 14:45 Travis <notifications@github.com> ha scritto:

**Comment by Hus274** [comment]
Excellent! :)

**Comment by paglias** [comment]
So I have no idea why this keep failing on travis given that it passes locally even when running the entire test suite I'm going to disable the test for now

**Comment by paglias** [comment]
Oh gosh, now the other test has started failing 

https://travis-ci.org/HabitRPG/habitica/jobs/360594224#L6602
