### PR TITLE
Fix difficult to edit checklists in Firefox

### LINKED ISSUE #9430: Firefox - Difficult to edit checklists
In Firefox, when editing checklists, the cursor turns into a cross with arrows in all four directions so that you can move the whole item up and down to a different position in the list. However, this makes it impossible click into the text to change it, since the cursor only appears at the very end of the checklist entry. Instead, when hovering over the text entry, you should have a normal mouse cursor.

### PR DESCRIPTION
**Pull request by pcvonz**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9430

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Replaced the custom sortablejs directive with the [Vue Draggable](https://github.com/SortableJS/Vue.Draggable) component. Used Vue Draggable to pass an argument to sortablejs to limit the selection to the handle class in the taskModal component. 

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: b16e0c46-c20b-4aea-9f1f-6e9dd80ad61b

### CODE REVIEW

File: website/client/components/tasks/taskModal.vue [hunk 1]
```diff
@@ -26,7 +26,11 @@
         .option(v-if="checklistEnabled")
           label(v-once) {{ $t('checklist') }}
           br
-          div(v-sortable='true', @onsort='sortedChecklist')
+          draggable(
+          v-model="checklist",
```
Comment (paglias) [inline website/client/components/tasks/taskModal.vue]: can you indent these attributes?

**Comment by paglias** [comment]
The PR is working well, it'll be merged in the next few days :)
