### PR TITLE
fix: Corrects stat allocation bug where it was possible to receive more points than 100

### LINKED ISSUE #6434: Today i got attribute points over lvl 100...
Hello all,

today i got the notification that i have unallocated attribute points. my character is lvl 141 and i allocated them all some while ago. so i went to the character page and could allocate those points. (141 in total now.) after refreshing they are still there. 

i think i leveled up today, but i'm not sure when the attribute points appeared. 

My user ID is ce935e7f-00e6-44bc-a44a-5280553810f0

Happy New Year to you all!

### PR DESCRIPTION
**Pull request by crookedneighbor**
fixes #6434

### CODE REVIEW

File: common/script/index.js [hunk 1]
```diff
@@ -2271,41 +2271,56 @@ api.wrap = function(user, main) {
...
-            continue;
+          if (totalStatPoints >= MAX_STAT_POINTS) {
+            continue; // eslint-disable-line no-continue
           }
           if (user.preferences.automaticAllocation) {
             user.fns.autoAllocate();
           } else {
-            user.stats.points = user.stats.lvl - userTotalStatPoints;
+            user.stats.points = user.stats.lvl - allocatedStatPoints;
+            totalStatPoints = user.stats.points + allocatedStatPoints;
```
Comment (Alys) [inline common/script/index.js]: duplicate of line 2299?

Comment (Alys) [inline common/script/index.js]: sorry, ignore that.

**Comment by Alys** [comment]
Tested, is good. :)

There's still problems with stat de/allocation in general (in production, not in this PR) but I'm going to make a new issue for that.
