### PR TITLE
Fix can not remove Group Plan tag

### LINKED ISSUE #11522: Group Plan tags are not deletable after leaving group
When you're in a guild/party that has a Group Plan, a tag for the group is added to your personal tags (this is correct behaviour).

When you are no longer in that group, the tag remains and you are not able to edit or delete it. I'm not sure if this happens when you leave the group or when the leader removes you or both.

The correct behaviour is that the tag should become one of your personal tags. I.e., the `group` attribute should be removed from the tag (see the sample tag below which shows that attribute).

The tag should not be deleted automatically because the player might have used it to tag their own tasks, which is permissible.

This was reported by @Ceran (aabe567b-aa55-42c1-b612-b7699a7ba9b7):
_"I still have the tag from the group I used to be in. I don't see a way for me to remove this tag. Could this tag be removed, please? "The Groupish Group". Only group tag I have."_
I've confirmed they are no longer in the associated group and have deleted the tag for them. This is what the tag used to be:

```
    "tags": [
        {
            "id": "d2397cb7-e92d-42dc-aba8-6686cab105e3",
            "name": "The Groupish Group",
            "group": "d2397cb7-e92d-42dc-aba8-6686cab105e3"
        },
 ```

For any coder wanting to work on this, [Using Your Local Install to Modify Habitica%27s Website and API](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) shows you how to add a Group Plan to a guild or party (in the "Creating Test Data" section). So, in your local install, you can create a guild or party as normal with one test user account as leader, run that database command to convert it to a group plan, invite a second test user to it, then use that second user for testing how tags behave on leaving / being removed. At least in theory. :) Post here if that doesn't work (say what goes wrong) and if you need help working out how to replicate this bug.

### PR DESCRIPTION
**Pull request by nikonhub**
- Allow to change name and remove a group tag
- Add a rule to check if the group tag is an active one to hide the
trash icon

[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11522

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
image

Client : 
- Allow to edit names of all tags
- Allow to remove all tags except if the user belongs to it. (guild or party group plan subscription)

Server :
- api/v4/user update tags. Change rules of tags that will be kept. Do not by default keep all group tags but check if it belongs to an active user guild or party instead.
- When a group leader assigns a new task to a member, do not reset the tag name of this member.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 07bd9063-362f-40c6-8d0c-1fa8b977243d

### CODE REVIEW

File: website/server/libs/user/index.js [hunk 1]
```diff
@@ -126,39 +126,34 @@ export async function update (req, res, { isV3 = false }) {
...
         }
-      });
 
-      user.tags = oldTags;
-
-      val.forEach(t => {
-        const oldI = removedTagsIds.findIndex(id => id === t.id);
-        if (oldI > -1) {
-          removedTagsIds.splice(oldI, 1);
+        if (user.party._id && user.party._id === tag.group) {
```
Comment (paglias) [inline website/server/libs/user/index.js]: this seems to be only checking the user's party but you can also be part of a group that is not your party (see `user.groups`)

**Review by paglias — CHANGES_REQUESTED** [review]
left one comment but this is also going to need some integration / unit tests to make sure the API is working correctly, thanks @Nikosmonaut !

File: website/server/libs/user/index.js (hunk 1 above)
Comment (nikonhub) [reply website/server/libs/user/index.js]: Do you mean user.guilds ? If yes I check it just after at line 140.

**Comment by nikonhub** [comment]
> this is also going to need some integration / unit tests to make sure the API is 

I added 2 integrations tests. No sure about about unit ones though.

File: website/server/libs/user/index.js (hunk 1 above)
Comment (paglias) [reply website/server/libs/user/index.js]: sorry I missed that

**Review by paglias — CHANGES_REQUESTED** [review]
@Nikosmonaut sorry for the delay. I gave a better look at the PR and I think it's a bit overly complicated. 

Instead of changing the way the tags are updated I think it would be better to remove the `group` attribute from your tag when you leave or are removed from a group, like the original issue said

```
The correct behaviour is that the tag should become one of your personal tags. I.e., the group attribute should be removed from the tag (see the sample tag below which shows that attribute).
```

This way the changes to the client side won't be necessary. The code executed when you leave a group is here https://github.com/HabitRPG/habitica/blob/develop/website/server/models/group.js#L1315

**Comment by nikonhub** [comment]
Hello.

No problem for the delay. (But yes it kind of gets old in my head the reasons for this solution).
Like I said [here](https://github.com/HabitRPG/habitica/issues/11522#issuecomment-552503278) we may face another unwanted behavior if the user is reinvited twice to the same group. Because he's "personal" old group tag would be reused.

```
    "tags": [
        {
            "id": "d2397cb7-e92d-42dc-aba8-6686cab105e3",
            "name": "The Groupish Group",
            "group": "d2397cb7-e92d-42dc-aba8-6686cab105e3"
        },
```
I think the perfect solution would be to not have the same id. Tag id !== group. So we could just delete the group key and we're done. But it would need to change the whole database :/

If you're ok with this side effect of reusing the same tag, I revert my changes to just remove the group key.

Edit : 
It is this code I'm talking about.
Maybe another solution would be to findIndex by { group: group._id }. From now have id !== group and keep old tags as is. But I it seems confusing.

```
  const userTags = user.tags;
  const i = _.findIndex(userTags, { id: group._id });

  if (i === -1) {
    userTags.push({
      id: group._id,
      name: group.name,
      group: group._id,
    });
  }
```

**Comment by paglias** [comment]
> I think the perfect solution would be to not have the same id. Tag id !== group. So we could just delete the group key and we're done. But it would need to change the whole database :/

> If you're ok with this side effect of reusing the same tag, I revert my changes to just remove the group key.

Good point. I'd say I'm okay with reusing the same id but let's see if @Alys is okay with that. If you don't hear anything in the next few days feel free to reuse the id

**Comment by Alys** [comment]
@Nikosmonaut I'm okay with reusing the same id too. Thanks for thinking through the options and implications!

**Comment by paglias** [comment]
Thanks @Nikosmonaut and sorry for the delay! The code fix looks good but it would need some tests, if you want to add them great but if you have any problem let me know and I can add them :)

**Comment by nikonhub** [comment]
Hello @paglias.

Just added a test.
Sorry for the delay. Christmas holidays not obvious to find time.

**Comment by paglias** [comment]
Hi @Nikosmonaut  , sorry for the delay but I'm still catching up from the end of year holidays, I hope to get to this PR in the next couple of days

**Comment by paglias** [comment]
It took a while but I finally managed to merge this, thanks @Nikosmonaut ! I've notated this PR towards your 3rd tier
