### PR TITLE
Don't show shield when previewing two-handed weapon (fixes #9495)

### LINKED ISSUE #9495: Preview incorrectly shows two-handed weapon AND shield
If you try to change your costume while wearing a shield and try to equip a two-handed weapon (or vice-versa), the preview shows your Avatar wearing both. There is no message or other warning that it's a two-handed weapon, but you are not able to equip my Avatar as it appears in the preview. (Note that this is separate from but related to https://github.com/HabitRPG/habitica/issues/8441). The preview should not show both a two-handed weapon and a shield at the same time.

### PR DESCRIPTION
**Pull request by matchajune**
[x]: Fixes https://github.com/HabitRPG/habitica/issues/9495

### Changes
[x]: An equipped shield doesn't show when previewing a two-handed weapon.
[x]: Fix `twoHanded` attribute being lost in the object when bubbling down.

----
UUID: dd16c270-1d6d-44bd-b4f9-737342e79be6

### CODE REVIEW

File: website/common/script/libs/getItemInfo.js [hunk 1]
```diff
@@ -191,7 +192,7 @@ module.exports = function getItemInfo (user, type, item, officialPinnedItems, la
     case 'gear':
       // spread operator not available
       itemInfo = Object.assign(getDefaultGearProps(item, language), {
-        value: item.twoHanded ? 2 : 1,
+        value: item.value,
```
Comment (negue) [inline website/common/script/libs/getItemInfo.js]: `value` under `gear` needs to have the `item.twoHanded ? 2 : 1` because this shows the gem price, the values under `marketGear` is the one paid with gold

**Review by negue — DISMISSED** [review]
apart from the `value` its LGTM :+1:

**Comment by Alys** [comment]
@matchajune Does this fix both aspects of the issue? "If you try to change your costume while wearing a shield and try to equip a two-handed weapon **(or vice-versa)** ..."

**Comment by matchajune** [comment]
I tested it vice versa, and I will have to work on this. I will report back once completed.

**Comment by matchajune** [comment]
@Alys Thank you for double checking. I have pushed a commit that fixes the issue and works both ways.

File: website/client/components/inventory/equipment/equipGearModal.vue [hunk 2]
```diff
@@ -151,6 +151,8 @@
       memberOverrideAvatarGear (gear) {
         return {
           [gear.type]: gear.key,
+          hideShield: gear.twoHanded,
```
Comment (negue) [inline website/client/components/inventory/equipment/equipGearModal.vue]: Sorry to give you some more work ... ☹️ 

but I think we should move the two checks `hideShield` and `isEquippedTwoHanded` to `avatar.vue` itself, that way every other (future use) of this component won't have to add this checks if it should hide the shield or the weapon

inside of `avatar.vue` `this.overrideAvatarGear.weapon` would check if the `this.member.items.gear[this.costumeClass][gearType]` is twoHanded and then act the same

Comment (matchajune) [reply website/client/components/inventory/equipment/equipGearModal.vue]: No problem at all @negue !! Thanks for your patience.

I pushed the latest changes to reflect your comment.

Please let me know if there's anything else you need from me!

**Comment by SabreCat** [comment]
Great, thanks for this too @matchajune! Noted toward your second contributor tier!

**Comment by matchajune** [comment]
Thank you!

**Comment by matchajune** [comment]
Hey @SabreCat , I just thought of an edge case and pushed up the fix for it. Because this branch is already merged, what would the process be to quickly add in this fix?

**Comment by SabreCat** [comment]
@matchajune Thanks for letting us know! Go ahead and submit a fresh PR and I'll get it merged on an expedited basis. (It'd be not unlike what we might do if we'd spotted the issue during the staging period.)

**Comment by matchajune** [comment]
@SabreCat doing so now.

**Comment by matchajune** [comment]
@SabreCat Thank you for the swift response. The PR has been created [here](https://github.com/HabitRPG/habitica/pull/9676)
