### PR TITLE
load user info per conversation.id

### LINKED ISSUE #1223: All senders are with Tier 7 label
**Describe the bug**
All senders are flagged with Tier 7 in Inbox.

**To Reproduce**
Steps to reproduce the behavior: access the Inbox.

**Expected behavior**
The labels need identify if a user have a Tier or no, and which Tier this user is.

**Screenshots**
Screenshot_20190918-182908

**Smartphone (please complete the following information):**
 - Device: Xiaomi Mi A2 Lite
 - OS: Android One 9
 - App Version: 2.1.1 (2241) - BETA
 - Habitica Username: @Viccthor

### PR DESCRIPTION
**Pull request by negue**
Load user-infos after conversations - in order to get the correct userstyles

fixes https://github.com/HabitRPG/habitica-android/issues/1223

### CODE REVIEW

File: website/server/libs/inbox/index.js [hunk 1]
```diff
@@ -99,9 +98,32 @@ export async function listConversations (owner) {
 
   const conversationsList = await query.exec();
 
+  const usersQuery = {
+    _id: {$in: conversationsList.map(c => c._id) },
+  };
+
+  const usersAr = await User.find(usersQuery,  {
+    _id: 1,
```
Comment (paglias) [inline website/server/libs/inbox/index.js:106]: why 1,2,3..? I think 1 means take the filed, 0 don't so values over 1 don't do anything

Comment (negue) [reply website/server/libs/inbox/index.js:106]: woops, guess I misread an example for the projection^^, tested this now again with just `1` works, too bad there isn't a warning/hint when I used 2 and higher :/

fixing as I write this

**Comment by paglias** [comment]
@negue I'm going to revert this as it's breaking messages loading on web

```
2019-09-22T11:09:28.636756+00:00 app[web.2]: 2019-09-22T11:09:28.635Z - error: TypeError: Cannot read property 'items' of undefined
2019-09-22T11:09:28.636781+00:00 app[web.2]:     at /app/website/transpiled-babel/libs/inbox/index.js:124:32
2019-09-22T11:09:28.636785+00:00 app[web.2]:     at Array.map (<anonymous>)
2019-09-22T11:09:28.636787+00:00 app[web.2]:     at Object.listConversations (/app/website/transpiled-babel/libs/inbox/index.js:120:43)
2019-09-22T11:09:28.636790+00:00 app[web.2]:     at processTicksAndRejections (internal/process/task_queues.js:93:5)

```
