### PR TITLE
#12970 Fixed 'String " not found' bug in categories while saving guild descr…

### LINKED ISSUE #12970: When saving guild description, the selected categories briefly appear as 'String " not found'
Steps to reproduce:

- Go to edit a guild 
- Press "Update guild"
- Watch the "Categories" section flicker to 'String " not found'

image

The categories are saved correctly, so there's no issue there, so this *seems* to be a minor cosmetic issue.

### PR DESCRIPTION
**Pull request by shantanu96**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #12970

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

- Set categories on the copy of `this.workingGroup` which is `groupData`.
- And emit that copy instead of the original, to the `updatedGroup` event.
- The event and dispatch request both use categories that have an object array.

This ensures original `this.workingGroup.categories`, used in layout code, which is a string array remains unchanged.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 2daaf78e-75b6-4422-b69a-a7fd5477d8b7

### CODE REVIEW

File: website/client/src/components/groups/groupFormModal.vue [hunk 1]
```diff
@@ -616,14 +616,14 @@ export default {
           name: catName,
         });
       });
-      this.workingGroup.categories = serverCategories;
 
       const groupData = { ...this.workingGroup };
+      groupData.categories = serverCategories;
```
Comment (benkelaar) [inline website/client/src/components/groups/groupFormModal.vue]: If you rename `serverCategories` to `categories` you could do this in a single go like this:

```
const groupData = { ...this.workingGroup, categories };
```

**Comment by SabreCat** [comment]
Thanks for this, @shantanu96! This will go into a staging environment for a few days before going live on the main site.

I've awarded your first Blacksmith tier for having a PR merged. Further tiers will require multiple PRs or a larger PR to attain, but keep helping out and we'll express our gratitude accordingly!
