### PR TITLE
Attributes UI Refactoring

### LINKED ISSUE #9356: Sorting by Stat does not include class bonus
On the Equipment page, when you sort your equipment by a stat, like perception or strength, the sorting does not take the class bonus into account of the class, only the raw bonus. This results in an incorrect recommendation. It should include the class bonus.

### PR DESCRIPTION
**Pull request by negue**
fixes #9356: Sort Gear by Attributes with Class-Bonus

The popover / modal now also shows the class bonus and the sum (with gear value).

Also adds the popover at the profile / stats overview

### CODE REVIEW

File: website/client/components/inventory/equipment/attributesGrid.vue [hunk 1]
```diff
@@ -0,0 +1,169 @@
...
+    // unless we have a way to give a popover an id or class, it needs expand the attributes area
+    margin: -13px -16px;
+    display:flex;
+    flex-wrap: wrap;
+  }
+
+  .popover-content-attr {
+    font-weight: bold;
+    width: calc(50% - 1px);
+    background-color: #4e4a57;
```
Comment (paglias) [inline website/client/components/inventory/equipment/attributesGrid.vue]: color variable if possible

File: website/client/components/inventory/equipment/attributesGrid.vue [hunk 2]
```diff
@@ -0,0 +1,169 @@
...
+    flex-wrap: wrap;
+    padding: 4px 12px;
+    width: 100%;
+  }
+
+  .popover-content-attr-cell {
+    width: 50%;
+    text-align: left;
+
+    font-family: Roboto;
```
Comment (paglias) [inline website/client/components/inventory/equipment/attributesGrid.vue]: is this necessary?

File: website/client/components/inventory/equipment/attributesGrid.vue [hunk 3]
```diff
@@ -0,0 +1,169 @@
...
+      color: $white;
+      font-size: 12px;
+      font-weight: bold;
+      line-height: 1.33;
+    }
+
+    &.label {
+      font-size: 10px;
+      line-height: 1.2;
+      color: #a5a1ac;
```
Comment (paglias) [inline website/client/components/inventory/equipment/attributesGrid.vue]: color variable if possible

File: website/client/components/inventory/equipment/attributesGrid.vue [hunk 4]
```diff
@@ -0,0 +1,169 @@
...
+  }
+
+  .modal-body {
+
+    .group-content {
+      padding: 8px 17px;
+    }
+
+    .popover-content-attr {
+      background-color: #f4f4f4;
```
Comment (paglias) [inline website/client/components/inventory/equipment/attributesGrid.vue:96]: color variable if possible

File: website/client/components/inventory/equipment/attributesGrid.vue [hunk 5]
```diff
@@ -0,0 +1,169 @@
...
+
+      &:nth-of-type(even) {
+        margin-left: 1px;
+        width: 50%;
+      }
+    }
+
+    .popover-content-attr-cell {
+      &.key {
+        color: #c3c0c7;
```
Comment (paglias) [inline website/client/components/inventory/equipment/attributesGrid.vue]: color variable if possible

File: website/client/components/inventory/equipment/attributesGrid.vue [hunk 6]
```diff
@@ -0,0 +1,169 @@
...
+        font-size: 16px;
+        font-weight: bold;
+        line-height: 1.25;
+
+        &.hasValue {
+          color: #4e4a57;
```
Comment (paglias) [inline website/client/components/inventory/equipment/attributesGrid.vue]: color variable if possible

File: website/client/components/inventory/equipment/attributesGrid.vue [hunk 7]
```diff
@@ -0,0 +1,169 @@
...
+        }
+      }
+
+      &.label {
+        color: #c3c0c7;
```
Comment (paglias) [inline website/client/components/inventory/equipment/attributesGrid.vue]: color variable if possible

File: website/client/components/inventory/equipment/attributesGrid.vue [hunk 8]
```diff
@@ -0,0 +1,169 @@
...
+        font-size: 12px;
+        font-weight: bold;
+        line-height: 1.33;
+
+        &.hasValue {
+          color: #878190;
```
Comment (paglias) [inline website/client/components/inventory/equipment/attributesGrid.vue]: color variable if possible

File: website/client/components/inventory/equipment/equipGearModal.vue [hunk 9]
```diff
@@ -59,11 +63,45 @@
...
+    .classTag {
+      height: 24px;
+      display: flex;
+      align-items: center;
+      justify-content: center;
+    }
+
+    .className {
+      height: 24px;
+      font-family: Roboto;
```
Comment (paglias) [inline website/client/components/inventory/equipment/equipGearModal.vue]: is this necessary?

File: website/client/components/inventory/equipment/equipGearModal.vue [hunk 10]
```diff
@@ -59,11 +63,45 @@
...
+      font-size: 16px;
+      font-weight: bold;
+      font-stretch: condensed;
```
Comment (paglias) [inline website/client/components/inventory/equipment/equipGearModal.vue]: this doesn't work, you have to use the Roboto Condensed filename, also isn't an already existing class for this? that at least doesn't require re-declaring all these typhography rules

File: website/client/components/inventory/equipment/equipGearModal.vue [hunk 11]
```diff
@@ -59,11 +63,45 @@
...
+      line-height: 1.5;
+      text-align: left;
+      margin-left: 8px;
+    }
+
+    .healer {
+      color: #cf8229;
```
Comment (paglias) [inline website/client/components/inventory/equipment/equipGearModal.vue]: color vars :P

File: website/client/components/inventory/equipment/equipGearModal.vue [hunk 12]
```diff
@@ -116,6 +162,9 @@
         content: 'content',
         user: 'user.data',
       }),
+      showClassTag () {
+        return ['warrior', 'wizard', 'rogue', 'healer'].includes(this.itemClass);
```
Comment (paglias) [inline website/client/components/inventory/equipment/equipGearModal.vue]: there's a list of classes already defined in the content or constants files

File: website/client/components/shops/buyModal.vue [hunk 13]
```diff
@@ -248,8 +248,12 @@
       }
     }
 
-    .bordered {
+    .attributesGrid {
       margin-top: 8px;
+      border-radius: 2px;
+      background-color: #e1e0e3;
```
Comment (paglias) [inline website/client/components/shops/buyModal.vue]: color var

File: website/client/components/userMenu/profile.vue [hunk 14]
```diff
@@ -636,6 +630,17 @@ export default {
       selectedPage: 'profile',
       achievements: {},
       content: Content,
+      equipTypes: {
```
Comment (paglias) [inline website/client/components/userMenu/profile.vue:633]: where are these used?

**Review by paglias — CHANGES_REQUESTED** [review]

File: website/client/components/inventory/equipment/equipGearModal.vue (hunk 10 above)
Comment (negue) [reply website/client/components/inventory/equipment/equipGearModal.vue]: yeah probably too much copied from zeplin ^^ 

Edit: but there isn't any available class for this, I'll add it to typography.scss

File: website/client/components/userMenu/profile.vue (hunk 14 above)
Comment (negue) [reply website/client/components/userMenu/profile.vue:633]: https://github.com/HabitRPG/habitica/pull/9887/files#diff-296cf9ad5234aa0fac0c65fafc0c6b97R126

to list each type of gear, so that we don't have to write the same popover logic per item type ^^

File: website/client/components/inventory/equipment/attributesGrid.vue (hunk 4 above)
Comment (negue) [reply website/client/components/inventory/equipment/attributesGrid.vue:96]: none available, I could create one

Comment (paglias) [reply website/client/components/inventory/equipment/attributesGrid.vue:96]: If it's not available I'd say if it's only used in one place let's not bother about using a var

Comment (negue) [reply website/client/components/inventory/equipment/attributesGrid.vue:96]: its also in `app.vue` but no where else I could extract both, any name suggestions? `$nearlyWhite` ? 😅

Comment (paglias) [reply website/client/components/inventory/equipment/attributesGrid.vue:96]: not sure anymore I want a variable 😄

**Review by paglias — APPROVED** [review]

File: website/client/components/inventory/equipment/attributesGrid.vue [hunk 15]
```diff
@@ -0,0 +1,168 @@
+<template lang="pug">
+  div.attributes-group
+    .popover-content-attr(v-for="attr in ATTRIBUTES", :key="attr")
+      .group-content
+        span.popover-content-attr-cell.key(:class="{'hasValue': hasSumValue(attr) }") {{ `${$t(attr)}: ` }}
+        span.popover-content-attr-cell.label.value(:class="{'green': hasSumValue(attr) }") {{ `${stats.sum[attr]}` }}
+        span.popover-content-attr-cell.label.bold(:class="{'hasValue': hasGearValue(attr) }") Gear:
+        span.popover-content-attr-cell.label(:class="{'hasValue': hasGearValue(attr) }") {{ stats.gear[attr] }}
+        span.popover-content-attr-cell.label.bold(:class="{'hasValue': hasClassBonus(attr) }") Bonus:
```
Comment (Alys) [inline website/client/components/inventory/equipment/attributesGrid.vue]: These Gear and Bonus strings should be translatable.

If we use "Class Bonus", the string `classEquipBonus` can be used:
https://github.com/HabitRPG/habitica/blob/028da1d6a9e1d64865dee8ab87289e121efbdd09/website/common/locales/en/character.json#L65.json

**Comment by Alys** [comment]
Can we consider using "Class Bonus" instead of "Bonus"? New players won't know what the Bonus is for. It's likely to become a common question. Here's a mock-up of what the change might look like (before and after):

screenshot_2018-01-30_16-59-48

**Comment by paglias** [comment]
Will get merged on monday :)
