### PR TITLE
Fix asc/desc sort order when sorted by name

### LINKED ISSUE #11913: Party Sort Order Asc / Desc (Ascending / Descending) fails for "Sort by Name" in modal
When you click the "View Party" button in the header, a modal opens and you see a drop-down with "Sort by" options and another drop-down for  "Asc" (Ascending) and "Desc" (Descending).

The Asc / Desc options don't make any difference when "Sort by Name" has been selected.

The expected behaviour is that if you select "Sort by Name" and then switch between Asc and Desc, the party members in the modal should reverse order.

Asc / Desc does work as required for the other "Sort by" options.

image

### PR DESCRIPTION
**Pull request by nikonhub**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11913 
### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Reuse lodash orderby function for all cases to take care of sort order. Special case for profile.name when passing a function instead of a object path.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 07bd9063-362f-40c6-8d0c-1fa8b977243d

### CODE REVIEW

File: website/client/src/components/groups/membersModal.vue [hunk 1]
```diff
@@ -478,20 +478,12 @@ export default {
       let sortedMembers = this.members;
 
       if (!isEmpty(this.sortOption)) {
-        // Use the memberlist filtered by searchTerm
-        if (this.sortOption.value === 'profile.name') {
-          // If members are to be sorted by name, use localeCompare for case-
-          // insensitive sort
-          sortedMembers.sort(
-            (a, b) => a.profile.name.localeCompare(b.profile.name),
```
Comment (Alys) [inline website/client/src/components/groups/membersModal.vue:486]: localeCompare or a similar locale-aware case folding technique is still desirable for this so that names in all languages are handled correctly.

Comment (nikonhub) [reply website/client/src/components/groups/membersModal.vue:486]: Sorry ! My bad. Case folding rhymed with case insensitive in my head.

**Comment by paglias** [comment]
thanks @Nikosmonaut for both this and the other PR, both are working well. And welcome to the 3rd tier 🎉
