### PR TITLE
fix(task) - 11139 use start-from hours in due date calculation

### LINKED ISSUE #11139: Custom Day Start time is not used for displaying To-Do due dates
As reported by Arkadiy @arkadiyjs (4401fa80-29a5-4f9e-8a51-94081fb3bffd) who has their Custom Day Start time set to 4am:

'It seems that the custom day start is not functional [for To-Do due dates]. [To-Dos] that are "Due Today" change to "Due a day ago" after [midnight] even though the day is supposed to start at 4 am.'

### PR DESCRIPTION
**Pull request by benkelaar**
Fixes #11139

Based on @sayansur25 's work in #11163 , credit should go to them.

Sinned against my own standards and neglected creating a `task.vue` unit test.  Apologies.

### Changes
- Use dayStart information to calculate due date.

----
UUID: d71d2c57-a73d-4591-b64d-e688584a9092

### CODE REVIEW

**Comment by paglias** [comment]
I'm having some issues testing this, I changed my custom day start to 5pm (next cron on the 25th of september @ 5pm which is in the future at time I'm writing this comment) and set a daily to be due on the 24th. It's still showing as `Due a day ago` even though for the site it's the 24th

File: website/client/src/components/tasks/task.vue [hunk 1]
```diff
@@ -995,18 +992,19 @@ export default {
       this.scoreChecklistItem({ taskId: this.task._id, itemId: item.id });
     },
     calculateTimeTillDue () {
-      const endOfToday = moment().endOf('day');
-      const endOfDueDate = moment(this.task.date).endOf('day');
+      const dayEnd = m => m.endOf('day').add(this.user.preferences.dayStart, 'hours');
+
+      const endOfToday = dayEnd(moment());
```
Comment (paglias) [inline website/client/src/components/tasks/task.vue]: it looks like this value is shifted one day in the future, (right now it's 11am on the 25th and my CDS is set at 5pm) and if printed it says `Sat Sep 26 2020 16:59:59 GMT+0200`

Comment (paglias) [reply website/client/src/components/tasks/task.vue]: Looking at other places that handle time calculations with CDS, I think that if `currentHourOfTheDay < CDS` you should subtract 1 day and then add the dayStart preference, otherwise `dayEnd + CDS` will go to tomorrow.

Or if ``currentHourOfTheDay < CDS` use `startOf('day')` instead of `endOf('day')`

Comment (benkelaar) [reply website/client/src/components/tasks/task.vue]: Ah yeah, that makes sense.  Thanks a lot!  Gives me another opportunity to at least attempt a unit test 😉.

Comment (paglias) [reply website/client/src/components/tasks/task.vue]: @benkelaar I'm just checking in because I saw a forced push but I don't think the code changed, in case something went wrong with github

Comment (benkelaar) [reply website/client/src/components/tasks/task.vue]: Nah, that was probably just rebasing on `develop`. As mentioned somewhere else, my laptop broke before I could push the unit test I wrote for this story, so will look into re-making that somewhere this week.

Comment (paglias) [reply website/client/src/components/tasks/task.vue]: looking good now!

**Comment by paglias** [comment]
thanks @benkelaar ! Welcome to the 5th tier

**Comment by benkelaar** [comment]
Pretty cool, but I wasn't actually sure I was done with this 😋.  Was planning to add more testcases tonight.  Will just create a new PR I guess 😅

**Comment by paglias** [comment]
Hehe sorry, sometimes people don't leave a comment when a PR is ready and I thought it was :)

**Comment by benkelaar** [comment]
No worries, serves me right for not setting the merge request to WIP.
