### PR TITLE
Fixed text of check-in prize when it is a set of backgrounds

### LINKED ISSUE #8580: backgrounds Check-In prize has no name in the notification modal
The check-in prize for your second day in Habitica is a set of backgrounds. When you're given that prize, the modal does not show the name of the prize:

image

It should show the name in a way similar to this:

image

I expect that this is because the backgrounds aren't content in the same sense at the other prizes so the code can't fetch their name. 

One possible fix would be to hard-code a name into `website/common/script/content/loginIncentives.js` in a new field called something like `rewardName` (the value should be translatable of course). That field would be used for only the backgrounds (but could be reused in future if we needed to give a custom name to any other prizes). The code that inserts the name into the modal could first look for the `rewardName` and if it's not specified, it could then fetch the name from the content in the same way it currently does.

_After this is fixed for the website, we should test the Android and iOS apps to see if they pick up the fix automatically (I'm not sure whether the name lookup happens in the API or in the apps). Currently in the Android app, the backgrounds are described as "null"._

### PR DESCRIPTION
**Pull request by Yutsuten**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8580 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
BgReward

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 203f208a-e0f0-4442-bf16-d4f19e553e8a

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Thanks for submitting. I don' think we want to solve this problem by adding the rewardName explicitly. The solution should determine why the text from this section is not being called: https://github.com/Yutsuten/habitica/blob/1538326f076292ae7a9cfd76eb334ca3b9264506/website/common/script/content/appearance/backgrounds.js#L482

**Comment by Yutsuten** [comment]
Okay, so we have something to discuss here.

Before continuing, I think its important to determine what is the objective of this PR. So, in this case, what is the desired output.
I can see 2 solutions. If you can see any other, please tell me.

1. Use a new and customized name created for the set of backgrounds
2. Show the name of each background received

So the output would be, respectively:

1. "You have received Plain Background Set"
2. "You have received Blue, Green, Purple, Red, Yellow"

About the code:

Currently, the reward for the second check-in is ``[api.backgrounds.incentiveBackgrounds]``. It is an object that has the 5 backgrounds inside it. The difference of this reward and the others is that the ``api.backgrounds.incentiveBackgrounds`` DON'T have a field ``text`` (which has the name of the item). It's a big object with 5 "small" objects.

For the first solution, we don't have a item that is called "Plain Background Set". It is a set, and the code can't take such "complex" name from nowhere. That's the situation where ``rewardName`` is used. If ``rewardName`` was declared, we use it as a name.

For the second solution, a common way to do this is already implemented for other rewards: put each reward in the ``reward`` array. For example, the reward for the 5th check-in is ``[api.food.Chocolate, api.food.Meat, api.food.CottonCandyPink]``. For the output, it is shown the name of each item. We can do something similar for the backgrounds.

I chose the first solution for this PR because in my opinion its better, and because it was suggested (at least this is the way I understood) by @Alys in the issue.
> One possible fix would be to hard-code a name into ``website/common/script/content/loginIncentives.js`` in a new field called something like ``rewardName`` (the value should be translatable of course). That field would be used for only the backgrounds (but could be reused in future if we needed to give a custom name to any other prizes). The code that inserts the name into the modal could first look for the rewardName and if it's not specified, it could then fetch the name from the content in the same way it currently does.

**Comment by Alys** [comment]
@Yutsuten Yes, you understood my suggestion correctly.

I think it's a clean approach for a situation where an accurate name can't be pulled from the content data. 

Another approach would be to list all the backgrounds individually as we do for food, but then we'd need code to suppress the display of the images of all but one background, and the names wouldn't make a lot of sense ("Blue, Green, Purple, Red, Yellow") so we'd have to manually add the word "background" (the new users who are receiving this would not recognise the images as backgrounds), and we'd also have to suppress listing the new Violet background that will be part of the incentives set in the content data when that feature is released. `rewardName` is simpler.

**Comment by TheHollidayInn** [comment]
Okay, I agree with the use case. Let's continue with this approach.

File: website/server/libs/cron.js [hunk 1]
```diff
@@ -165,6 +165,11 @@ function awardLoginIncentives (user) {
       count += 1;
     }
 
+    // Overwrite notificationData.rewardText if rewardName was explicitly declared
+    if (loginIncentive.rewardName) {
+      notificationData.rewardText = i18n.t(loginIncentive.rewardName);
```
Comment (paglias) [inline website/server/libs/cron.js]: can you pass user.preferences.language as the second parameter here? Otherwise it'll always be in English. And since you're there can you also add it to the i18n.t call at line 160?

**Review by paglias — CHANGES_REQUESTED** [review]

File: website/server/libs/cron.js (hunk 1 above)
Comment (Yutsuten) [reply website/server/libs/cron.js]: Sure

**Review by paglias — APPROVED** [review]

**Comment by Alys** [comment]
I've tested this as described below and it's working. I have not reviewed the code.

1. Create new account. Leave its language set to `en`. 
2. Use the +1 missed days debug option to cron a few times, examining the check-in prize modal each time.
3. Prizes names were correct, including the new name for the background set.
4. Create a new account. Change language to `fr` (which has a translation for the set name).
5. Repeat 2 but in French.
6. Prize names were correct, including the French translation of the background set.

**Comment by TheHollidayInn** [comment]
Code looks fine to me.

**Comment by Alys** [comment]
Thank you @Yutsuten! I've noted this towards your tier progression.
