### PR TITLE
Fix: Inconsistent Quest Unlock Behavior

### LINKED ISSUE #13013: inconsistent unlock behaviour for Mystery of Masterclassers quest line quests
_This is suggestion-discussion. It's borderline between bug and feature change request, since I believe the current code is behaving as written, but I thought it best to put here. Even if it's closed with a note that the behaviour is intentional, it will be good to have in GitHub so that we can reference it if it's reported again and/or link to it from the wiki's Quests page._

_As reported by @Nakonana (33bb14bd-814d-40cb-98a4-7b76a752761c):_

"Might not be a bug, but it's still a bit funny:

"To purchase the 1st quest of the Mystery of Masterclassers quest line, [Read Between the Lines](https://habitica.fandom.com/wiki/Read_Between_the_Lines) [`lostMasterclasser1`], you have to complete the last parts of the other quest lines. But even if you don't meet the requirements yourself, you can still participate in the Mystery of the Masterclassers quests, if a party mate, who meets the requirements, invites you to those quests. So far, so good and as expected, however after finishing the party mate's Read Between the Lines, you are now able to purchase [Assembling the a'Voidant](https://habitica.fandom.com/wiki/Assembling_the_aVoidant) [`lostMasterclasser2`], but not Read Between the Lines. [screenshot below]

"I would expect that the quests are either all unlocked after I complete them or that they all remain locked until I meet the requirements for the 1st quest. Having only one of them remain locked after completion seems a bit inconsistent."

image

### LINKED ISSUE #13206: Locked quests are still buyable even though they appear not to be
image

The Golden Knight Part 3 should be locked for the user testing (NYFairy), and it does appear to be... but the quest was purchaseable and appears in their inventory, including after refreshing.

### PR DESCRIPTION
**Pull request by CuriousMagpie**
[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #13013 and #13206

### Changes
- grouped and alphabetized all quests in preparation for future refactoring of `quests.js`
- updated quest data in `quests.js` to have multiple previous steps in sequentially unlocking quests
- updated function `unlockQuest` in `getItemInfo.js` to check for multiple steps
- improved readability of function `unlockQuest` in `getItemInfo.js`
- removed `isGearLocked` from `quests/index.vue`
- added 'if (item.locked) return;' to `selectItem(item)` in `quests/index.vue`

**Note:** The fix to prevent users from purchasing locked quest items has been implemented in the client side only. Further investigation is needed to determine how to fix this in the API and a new issue will be opened.

----
UUID: f4e5c6da-0617-48bf-b3bd-9f97636774a8

### CODE REVIEW

File: website/common/script/content/quests.js [hunk 1]
```diff
@@ -14,1850 +14,1815 @@ const CURRENT_EVENT = find(
 );
 const userCanOwnQuestCategories = USER_CAN_OWN_QUEST_CATEGORIES;
 
+// separatihg & sorting quests by type --
+// generic unlockable, chain, masterclasser, seasonal, pet, potion, time travelers, world
+// with intent of eventually refactoring
```
Comment (SabreCat) [inline website/common/script/content/quests.js]: Maybe we leave this for a separate refactoring PR, then? It'd be good to be able to review the functionally relevant additions without having to wade through all the cut-paste intended for later work.

File: website/common/script/libs/getItemInfo.js [hunk 2]
```diff
@@ -9,12 +9,27 @@ import isFreeRebirth from './isFreeRebirth';
...
-    return user.loginIncentives < quest.unlockCondition.incentiveThreshold;
+
+  // checks unlockCondition.incentiveThreshold
+  if (
+    quest.unlockCondition
+    && quest.unlockCondition.incentiveThreshold
+    && user.loginIncentives < quest.unlockCondition.incentiveThreshold
+  ) return true;
+  if (user.achievements.quests) {
+    return quest.previous
```
Comment (SabreCat) [inline website/common/script/libs/getItemInfo.js]: After this update, do we even need to reference `quest.previous`? Given that all those should be in `quest.prereqQuests` now?

File: website/common/script/libs/getItemInfo.js [hunk 3]
```diff
@@ -52,7 +67,9 @@ export default function getItemInfo (user, type, item, officialPinnedItems, lang
 
   let itemInfo;
 
-  switch (type) { // eslint-disable-line default-case
+  switch ( // eslint-disable-line default-case
+    type
+  ) {
```
Comment (SabreCat) [inline website/common/script/libs/getItemInfo.js]: this is odd, did the linter ask you to do this?

File: website/common/script/ops/buy/buyQuestGem.js [hunk 4]
```diff
@@ -8,6 +8,7 @@ import content from '../../content/index';
 
 import errorMessage from '../../libs/errorMessage';
 import { AbstractGemItemOperation } from './abstractBuyOperation';
+// import itemInfo from '../../libs/getItemInfo';
```
Comment (SabreCat) [inline website/common/script/ops/buy/buyQuestGem.js]: We decided against doing this, no need to add a comment for it.

File: website/common/script/ops/buy/buyQuestGold.js [hunk 5]
```diff
@@ -53,7 +46,8 @@ export class BuyQuestWithGoldOperation extends AbstractGoldItemOperation { // es
 
   checkPrerequisites (user, questKey) {
     const item = content.quests[questKey];
-    if (questKey === 'lostMasterclasser1' && !this.userAbleToStartMasterClasser(user)) {
+    if (questKey.startsWith('lostMasterclasser')
+    && !this.userAbleToStartMasterClasser(user)) {
```
Comment (SabreCat) [inline website/common/script/ops/buy/buyQuestGold.js]: This is the cause of one of your test failures. You removed the `userAbleToStartMasterClasser` function but still try to invoke it here.

File: website/common/script/ops/buy/abstractBuyOperation.js [hunk 6]
```diff
@@ -139,6 +139,10 @@ export class AbstractGoldItemOperation extends AbstractBuyOperation {
     if (item && item.canOwn && !item.canOwn(user)) {
       throw new NotAuthorized(this.i18n('cannotBuyItem'));
     }
+
+    if (item.locked) {
+      throw new NotAuthorized(this.i18n('cannotBuyItem'));
+    }
```
Comment (SabreCat) [inline website/common/script/ops/buy/abstractBuyOperation.js]: I think this is causing the other test failure. Note that above we short-circuit if `item` isn't available--apparently we use this code for a subscriber to buy Gems using Gold, but there isn't a full `item` to represent a Gem.

So if we were doing this, the fix would be to change the condition line to `if (item && item.locked) {`
...but, I think we backed off making changes to `abstractBuyOperation` anyway? I don't think these conditions are ever going to hit, given the buy operation doesn't have access to `locked`. I think the actual correction to be made for this PR is to remove the changes to this file.

**Review by SabreCat — CHANGES_REQUESTED** [review]
Questions and suggestions included, have a look!

File: website/common/script/libs/getItemInfo.js (hunk 2 above)
Comment (CuriousMagpie) [reply website/common/script/libs/getItemInfo.js]: Probably not, we could likely change it to `return true`--I'll test that out.

File: website/common/script/libs/getItemInfo.js (hunk 3 above)
Comment (CuriousMagpie) [reply website/common/script/libs/getItemInfo.js]: It did! I couldn't get it to not throw an error unless I made the change. I suspect my linter may be using slightly stricter rules.

File: website/common/script/ops/buy/buyQuestGem.js (hunk 4 above)
Comment (CuriousMagpie) [reply website/common/script/ops/buy/buyQuestGem.js]: That's an artifact of a previous attempt--will delete.

File: website/common/script/ops/buy/buyQuestGold.js (hunk 5 above)
Comment (CuriousMagpie) [reply website/common/script/ops/buy/buyQuestGold.js]: putting it back in--there should be a way to call `locked` into `checkPrerequisites` but I think that's going to be part of the server-side fix when it's implemented

File: website/common/script/ops/buy/abstractBuyOperation.js (hunk 6 above)
Comment (CuriousMagpie) [reply website/common/script/ops/buy/abstractBuyOperation.js]: Took it out!

File: website/common/script/libs/getItemInfo.js [hunk 7]
```diff
@@ -9,12 +9,25 @@ import isFreeRebirth from './isFreeRebirth';
...
+  // checks unlockCondition.incentiveThreshold
+  if (
+    quest.unlockCondition
+    && quest.unlockCondition.incentiveThreshold
+    && user.loginIncentives < quest.unlockCondition.incentiveThreshold
+  ) return true;
+  if (user.achievements.quests
+    && !user.achievements.quests[quest.previous]);
+  // then if we've passed all the checks
   return quest.previous;
```
Comment (SabreCat) [inline website/common/script/libs/getItemInfo.js]: this last part of the logic has me puzzled--
what's with the `if` statement that just ends in a semicolon?
and why is the final return still `quest.previous`?

I'm guessing it should be

```
if (quest.previous) return !(user.achievements.quests && user.achievements.quests[quest.previous]);
return false;
```

File: website/common/script/content/quests.js (hunk 1 above)
Comment (SabreCat) [reply website/common/script/content/quests.js]: Because you have the refactoring PR out now, would it be OK to skip the alphabetization changes in quests.js for this PR? It's not necessary to the fix, and it's going to introduce conflicts with the refactor.

eh, on second thought, never mind--it will actually be more trouble to revert it, because we're also adding in the `prereqQuests` property. We'll probably need to manually add those to the refactor PR once this is merged.

**Review by SabreCat — CHANGES_REQUESTED** [review]
couple things that need a look still on the code side. I'll do some functional testing next!

File: website/common/script/libs/getItemInfo.js (hunk 7 above)
Comment (SabreCat) [reply website/common/script/libs/getItemInfo.js]: or, wait, I thought you said you were removing the `quest.previous` check entirely... I am confuzzled @.@

File: website/common/script/ops/buy/abstractBuyOperation.js (hunk 6 above)
Comment (SabreCat) [reply website/common/script/ops/buy/abstractBuyOperation.js]: looks like it's still there?

**Comment by SabreCat** [comment]
This is odd--only the middle part of the Lunar Battle chain reports a need to finish the prior entry in the series:

image
image

Should they both list sequential prereqs, or neither?

Oh, I see-- the `previous` property has been changed to `previous1` on `moon3` and I don't think anything checks for that.

File: website/common/script/ops/buy/abstractBuyOperation.js (hunk 6 above)
Comment (CuriousMagpie) [reply website/common/script/ops/buy/abstractBuyOperation.js]: I'm not seeing it? Here's the current code for `canUserPurchase` on the branch, lines 131 through 150:

```
  canUserPurchase (user, item) {
    this.item = item;
    const itemValue = this.getItemValue(item);

    const userGold = user.stats.gp;

    if (userGold < itemValue * this.quantity) {
      throw new NotAuthorized(this.i18n('messageNotEnoughGold'));
    }

    if (item && item.canOwn && !item.canOwn(user)) {
      throw new NotAuthorized(this.i18n('cannotBuyItem'));
    }
  }

  async subtractCurrency (user, item) {
    const itemValue = this.getItemValue(item);

    user.stats.gp -= itemValue * this.quantity;
  }
```

File: website/common/script/libs/getItemInfo.js (hunk 7 above)
Comment (CuriousMagpie) [reply website/common/script/libs/getItemInfo.js]: I think I meant to and spaced out on it--I've made a change and am going to test it:

```
  if (user.achievements.quests
    && !user.achievements.quests[quest.prereqQuests]);
  // then if we've passed all the checks
  return quest.prereqQuests;
```

If that doesn't work, then I'll try `return false;`

**Comment by CuriousMagpie** [comment]
Yeah, that `previous1` should have been `previous`...

File: website/common/script/libs/getItemInfo.js (hunk 7 above)
Comment (CuriousMagpie) [reply website/common/script/libs/getItemInfo.js]: `return false;` is the way to go!

Comment (SabreCat) [reply website/common/script/libs/getItemInfo.js]: right! `return quest.prereqQuests` would send back the whole array, when we're expecting a true/false.

**Comment by SabreCat** [comment]
Updates look good! I merged the quests refactor, though, so we will probably need to make the changes to individual quests in the refactored directory tree now. Let me know if you need a hand with that.

File: website/common/script/libs/getItemInfo.js [hunk 8]
```diff
@@ -9,13 +9,26 @@ import isFreeRebirth from './isFreeRebirth';
...
+  if (quest.lvl && user.stats.lvl < quest.lvl) return true;
+
+  // checks unlockCondition.incentiveThreshold for Lunar Battle
+  if (
+    quest.unlockCondition
+    && quest.unlockCondition.incentiveThreshold
+    && user.loginIncentives < quest.unlockCondition.incentiveThreshold
+  ) return true;
+  if (user.achievements.quests
+    && !user.achievements.quests[quest.prereqQuests]);
```
Comment (SabreCat) [inline website/common/script/libs/getItemInfo.js]: I still don't understand what's going on here. `quest.prereqQuests` is an array, which is unlikely to behave nicely used like this. And what is this `if` block doing, ending in a semicolon with no action following?

Comment (CuriousMagpie) [reply website/common/script/libs/getItemInfo.js]: I removed those lines and everything seems to be working as it should when I tested it.

**Review by SabreCat — APPROVED** [review]
