### PR TITLE
fix: I18n string update

### LINKED ISSUE #9210: Remove duplicate I18N strings
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

As reported by @paglias in our internal bug tracking doc:

> lots of unused / duplicate i18n strings. Should write an automated scripti for this.

We should remove duplicate strings used for the same meaning. E.g. https://github.com/HabitRPG/habitica/pull/9191/commits/1717c2a5df3e649764d224eeee780f7b07d0cb24 - removed `headGear` because we had `headgearCapitalized` already. Word of caution! There are places where the same English text is used but it's used for different meanings of the word, and thus can be translated differently. E.g. `text` ("Title", meaning the heading text for a task) vs. `title` ("Title" meaning someone's contributor label).

### PR DESCRIPTION
**Pull request by CuriousMagpie**
Fix for #9210 

### Changes
- Reviewed files in `website/common/locales/en/` for duplicates and/or redundant strings
- Updated all files where duplicate and/or redundant strings occurred
- Affected directories:
  - `test/api/v3/integration/`
  - `test/api/v4/user/`
  - `website/client/src/compents/`
  - `website/common/locales/en/`
  - `website/common/script/content/`
  - `website/server/controllers/api-v3/`
  - `website/server/libs/tasks/`
- Tested local copy to ensure that there were no errors

Resolved items listed in these comments:

- [Similar strings in the same file](https://github.com/HabitRPG/habitica/issues/9210#issuecomment-711064655)
- [Similar strings in different files](https://github.com/HabitRPG/habitica/issues/9210#issuecomment-711064685)
- [Different strings with same content in the same file](https://github.com/HabitRPG/habitica/issues/9210#issuecomment-711064721)
- [Different strings with same content in different files](https://github.com/HabitRPG/habitica/issues/9210#issuecomment-711064754)

Did not resolve these items:

- [Different strings with similar content](https://github.com/HabitRPG/habitica/issues/9210#issuecomment-711064772): unresolved due to punctuation being needed in some places but not another
- [Strings content that could be improved](https://github.com/HabitRPG/habitica/issues/9210#issuecomment-711064800): unresolved due to potential issues with translations

----
UUID:
f4e5c6da-0617-48bf-b3bd-9f97636774a8

### CODE REVIEW

File: website/client/src/components/hall/heroes.vue [hunk 1]
```diff
@@ -217,7 +217,7 @@
             <tr>
               <th>{{ $t('name') }}</th>
               <th v-if="user.contributor && user.contributor.admin">
-                {{ $t('UUID') }}
+                {{ $t('UserId') }}
```
Comment (SabreCat) [inline website/client/src/components/hall/heroes.vue]: I think this should be `userId`, no leading capital!

File: website/client/src/components/hall/patrons.vue [hunk 2]
```diff
@@ -10,7 +10,7 @@
           <tr>
             <th>{{ $t('name') }}</th>
             <th v-if="user.contributor.admin">
-              {{ $t('UUID') }}
+              {{ $t('UserId') }}
```
Comment (SabreCat) [inline website/client/src/components/hall/patrons.vue]: same here

File: website/client/src/components/tasks/brokenTaskModal.vue [hunk 3]
```diff
@@ -53,23 +53,23 @@
...
       </div>
       <!-- @TODO: I ported this over, but do we use it anymore?-->
       <!--div(v-if='brokenChallengeTask.challenge.broken
       === "UNSUBSCRIBED"')p {{ $t('unsubChallenge') }}
 p
-  a(@click="unlink('keep-all')") {{ $t('keepThem') }}
+  a(@click="unlink('keep-all')") {{ $t('keepTasks') }}
   | &nbsp;|&nbsp;
-      a(@click="unlink('remove-all')") {{ $t('removeThem') }}-->
+      a(@click="unlink('remove-all')") {{ $t('removeTasks') }}-->
```
Comment (SabreCat) [inline website/client/src/components/tasks/brokenTaskModal.vue]: Is this just a commented-out code block? I'd check how far back in the repository we last had this active, and if it's been a while, just delete this rather than make updates to unused code.

File: website/common/locales/en/challenge.json [hunk 4]
```diff
@@ -24,15 +23,13 @@
...
   "createChallengeCloneTasks": "Clone Challenge Tasks",
-  "addTaskToChallenge": "Add Task",
   "challengeTag": "Tag Name",
   "prize": "Prize",
   "publicChallengesTitle": "Public Challenges",
   "officialChallenge": "Official Habitica Challenge",
   "by": "by",
   "participants": "<%= membercount %> Participants",
   "join": "Join",
-  "exportChallengeCSV": "Export to CSV",
```
Comment (SabreCat) [inline website/common/locales/en/challenge.json:35]: This is actually used, albeit with the peculiar capitalization `exportChallengeCsv`; does this break the Challenge export button?

File: website/common/locales/en/inventory.json [hunk 5]
```diff
@@ -1,7 +1,6 @@
 {
   "noItemsAvailableForType": "You have no <%= type %>.",
   "foodItemType": "Pet Food",
-  "eggsItemType": "Eggs",
```
Comment (SabreCat) [inline website/common/locales/en/inventory.json]: This looks like a templated/dynamic string token--note to self, check this out in a functional test

**Review by SabreCat — CHANGES_REQUESTED** [review]
Did a first round of code review, found a couple of things to look at. I'll dig into more of a functional testing pass next!

File: website/common/locales/en/challenge.json (hunk 4 above)
Comment (CuriousMagpie) [reply website/common/locales/en/challenge.json:35]: No, it doesn't--I just checked on my local installation and was able to download a CSV and open it up.

File: website/client/src/components/tasks/brokenTaskModal.vue (hunk 3 above)
Comment (CuriousMagpie) [reply website/client/src/components/tasks/brokenTaskModal.vue]: It is a commented-out code block. There's a comment right above it saying that it had been ported over but also asking if it were still used. I can look in the history and try to find when it was last active. I do agree that if it's been inactive for a while then the whole thing should come out.

File: website/client/src/components/hall/heroes.vue (hunk 1 above)
Comment (CuriousMagpie) [reply website/client/src/components/hall/heroes.vue]: Fixing it in my next commit.

File: website/client/src/components/hall/patrons.vue (hunk 2 above)
Comment (CuriousMagpie) [reply website/client/src/components/hall/patrons.vue]: Fixing it in my next commit.

File: website/client/src/components/tasks/brokenTaskModal.vue (hunk 3 above)
Comment (CuriousMagpie) [reply website/client/src/components/tasks/brokenTaskModal.vue]: Last used two years ago, have removed.

File: website/common/locales/en/inventory.json (hunk 5 above)
Comment (SabreCat) [reply website/common/locales/en/inventory.json]: It does look like this one is used. You just don't find it on a `grep` because it's assembled dynamically in a template, for the Market drawer:

image

Comment (CuriousMagpie) [reply website/common/locales/en/inventory.json]: Restored!

**Review by SabreCat — APPROVED** [review]

**Comment by SabreCat** [comment]
tada! 🎉
