### PR TITLE
Fix overflow in guild member text and keyboard inaccessible member/bank lists fixes #11067

### LINKED ISSUE #11067: Text displaced off Member List button in large guilds
> raventarte   @ravenlune (9272ab2c-4b66-4b74-aebd-799725885d1c) [web] 
> It would appear that there was a CSS change to the website that now causes the text "Member List" to appear off the surrounding badge if a guild has a very large member count, and the number count itself to stop aligning with the shield icon. An example is the Habitica Help guild, versus this guild, which appears properly. Here is a screenshot comparison. I believe it is the fixed height/width values of the badge that causes this issue, and it seems to only occur if the member count is 10.1k or higher (as this is too large for the badge to handle).

Confirmed in Windows / Google Chrome.

### PR DESCRIPTION
**Pull request by J-Sanderson**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11067

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Fixes overflowing text in guild member lists with large member counts.
Fix the guild member list and gem bank divs being inaccessible to keyboard navigation.

Screenshot from 2020-10-01 19-29-41

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)
cbeeb477-d5db-4efd-8f0b-68201870482b

----
UUID:

### CODE REVIEW

File: website/client/src/components/groups/group.vue [hunk 1]
```diff
@@ -58,10 +60,13 @@
...
             <div
               v-if="!isParty"
-              class="col-4"
+              class="offset-1"
             >
               <div
                 class="item-with-icon"
+                tabindex="0"
+                role="button"
+                @keyup.enter="showMemberModal()"
```
Comment (paglias) [inline website/client/src/components/groups/group.vue]: I think here it should call `showGroupGems `

**Review by paglias — CHANGES_REQUESTED** [review]
left one comment :)

File: website/client/src/components/groups/group.vue (hunk 1 above)
Comment (J-Sanderson) [reply website/client/src/components/groups/group.vue]: copy paste fail, thanks for catching!

File: website/client/src/components/groups/group.vue [hunk 2]
```diff
@@ -25,11 +25,13 @@
         <div class="col-12 col-md-6">
           <div class="row icon-row">
             <div
-              class="col-4 offset-4"
               :class="{ 'offset-8': isParty }"
```
Comment (paglias) [inline website/client/src/components/groups/group.vue]: I think the offset here might not be necessary anymore

File: website/client/src/components/groups/group.vue [hunk 3]
```diff
@@ -225,12 +230,15 @@
     box-shadow: 0 2px 2px 0 rgba(26, 24, 29, 0.16), 0 1px 4px 0 rgba(26, 24, 29, 0.12);
     padding: 1em;
     text-align: center;
-    min-width: 80px;
-    max-width: 120px;
+    min-width: 100px;
```
Comment (paglias) [inline website/client/src/components/groups/group.vue]: I'm not sure exactly why give the min-width was set to 80px but it looks like the item here is currently 120px while with the PR it shrank a bit. Could we change it so that by defaults it's 120px wide?

File: website/client/src/components/groups/group.vue (hunk 2 above)
Comment (J-Sanderson) [reply website/client/src/components/groups/group.vue]: Yes, looks like that entire container div can go without any problems.

File: website/client/src/components/groups/group.vue (hunk 3 above)
Comment (J-Sanderson) [reply website/client/src/components/groups/group.vue]: Fixed!

**Comment by paglias** [comment]
Looking good @J-Sanderson !

@Tressley I don't think we had a zeplin for this part but just in case this is something we want to change, the space between the Members Count and Gem Bank is slightly larger than before (it wasn't a specific distance before, just what happened with the previous code) 

Schermata 2020-10-06 alle 23 09 59

Do we want to reduce it?

This is with a margin between the two of 1.5rem

Schermata 2020-10-06 alle 23 13 22

File: website/client/src/components/groups/group.vue [hunk 4]
```diff
@@ -10,7 +10,7 @@
     <group-gems-modal />
     <div class="col-12 col-sm-8 standard-page">
       <div class="row">
-        <div class="col-12 col-md-6 title-details">
+        <div class="col-12 col-md-4 title-details">
```
Comment (paglias) [inline website/client/src/components/groups/group.vue]: I think changing this to md-4 is causing some issues

Schermata 2020-10-07 alle 15 16 34

The title should have more space to expand

Comment (paglias) [reply website/client/src/components/groups/group.vue]: It should be the other way around md-8 for the title and md-4 for the badges

File: website/client/src/components/groups/group.vue [hunk 5]
```diff
@@ -225,12 +226,15 @@
...
+    min-width: 120px;
     height: 76px;
 
+    &:last-of-type {
+      margin-right: 1rem;
+    }
+
     .svg-icon.shield, .svg-icon.gem {
-      width: 28px;
+      min-width: 28px;
```
Comment (paglias) [inline website/client/src/components/groups/group.vue]: I think this should be set back to `width` not `min-width`, it's causing some issues with firefox
image

**Review by paglias — CHANGES_REQUESTED** [review]
@J-Sanderson left two comments about some issues

File: website/client/src/components/groups/group.vue (hunk 4 above)
Comment (J-Sanderson) [reply website/client/src/components/groups/group.vue]: Ok, want to make sure while I'm here that the spacing looks ok?

Screenshot from 2020-10-07 18-44-34

They also stack on certain smaller sized screens since they can't shrink below 120 pixels, is this acceptable?

Screenshot from 2020-10-07 18-48-50

For reference the same size screen looked like this before:

Screenshot from 2020-10-07 18-47-24

File: website/client/src/components/groups/group.vue (hunk 5 above)
Comment (J-Sanderson) [reply website/client/src/components/groups/group.vue]: Yeah, that shouldn't have been there, thanks for the catch. Must have done that by accident.

File: website/client/src/components/groups/group.vue (hunk 4 above)
Comment (paglias) [reply website/client/src/components/groups/group.vue]: I haven't checked but maybe having both col-md-6 instead of 8 and 4 could result in a better support for smaller screens while still allowing longer titles

Comment (J-Sanderson) [reply website/client/src/components/groups/group.vue]: Looks about the same with that. For reference the stacking occurs from widths of 768px to 892px if both are at col-md-6.

Comment (paglias) [reply website/client/src/components/groups/group.vue]: Let's keep the two col-md-6 then

Comment (J-Sanderson) [reply website/client/src/components/groups/group.vue]: Ok - pushing fixes.

**Comment by paglias** [comment]
@J-Sanderson  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!
