### PR TITLE
fix padding on various pages

### LINKED ISSUE #9603: Incorrect left and right margins on the page
Throughout the site, the content should be framed by ~24px on the left and right. These are commonly referred to as "gutters" in design/development. Below you can see an example of the incorrect alignment.

image

This touches on various areas of the site, primarily the Tasks page, Tavern, Guilds, and Party.

### PR DESCRIPTION
**Pull request by adamfitzgibbon**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9603 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Adjusted padding on a variety of pages to maintain a 24px left-right gutter.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 2d02f021-be7b-4be4-b20e-3488a00336c8

### CODE REVIEW

File: website/client/src/components/groups/tavern.vue [hunk 1]
```diff
@@ -513,10 +513,15 @@
     padding: 0em;
 
     .below-header-sections {
-      padding: 1em 1.75em 1em 1.75em;
+      padding: 1em 24px 1em 24px;
     }
   }
 
+  .px-3 {
```
Comment (paglias) [inline website/client/src/components/groups/tavern.vue]: instead of changing the rules for this class, can't we simply use `px-4`which has 24px paddings

File: website/client/src/components/groups/group.vue [hunk 2]
```diff
@@ -256,10 +256,13 @@
     background-color: $gray-600;
     padding-bottom: 2em;
 
+    .below-header-sections {
+        padding: 1em 24px 1em 24px;
```
Comment (paglias) [inline website/client/src/components/groups/group.vue]: can we use ems everywhere here? So that would be `1em 1.5em 1em 1.5em´

Comment (paglias) [reply website/client/src/components/groups/group.vue]: actually instead of using a new class this can be achieved by applying `px-4 py-3`

Comment (paglias) [reply website/client/src/components/groups/group.vue]: same thing in tavern.vue

**Review by paglias — CHANGES_REQUESTED** [review]
@adamfitzgibbon thanks for the PR! I've left a couple of comments regarding the code but the paddings work well, if you can apply the changes I'll merge it as soon as possible

File: website/client/src/components/groups/tavern.vue (hunk 1 above)
Comment (adamfitzgibbon) [reply website/client/src/components/groups/tavern.vue]: Oh I wasn't aware! I'll make those updates when I have a minute!

Comment (paglias) [reply website/client/src/components/groups/tavern.vue]: thanks! those classes come from Bootstrap's utilities https://getbootstrap.com/docs/4.3/utilities/spacing/

Comment (adamfitzgibbon) [reply website/client/src/components/groups/tavern.vue]: @paglias finally had some time to get these updated

**Review by paglias — APPROVED** [review]

**Comment by paglias** [comment]
Sorry for the delay @adamfitzgibbon , I've merged this and will go live next week. I've notated this towards your 3rd tier, thanks!
