### PR TITLE
fix tag sorting

### LINKED ISSUE #7541: Tags cannot be sorted / reordered
Tags cannot be sorted. If you change the order of the tags, the next time a sync occurs, they change back.

### PR DESCRIPTION
**Pull request by shervinmathieu**
Fixes #7541
### Changes

A sneaky bug, frustratingly hard to find.
The call to user.ops.sortTag causes the client side tag data to be sorted before the call to the API to update the database. The call to the API then receives the ID of the tag that occupied the slot of the intended tag to be sorted.

Since the tag id cannot be pulled from ui.item.data, I've instead added a variable to the code to store the id if the tag to be sorted.

There is no karma coverage for sorting tags, and I don't know how to write karma tests (maybe I should learn to do so). However, this bug would not have been detected by a karma test either.

---

UUID: c104a050-7a9a-488f-ad0f-cda73815432b

### CODE REVIEW

**Comment by shervinmathieu** [comment]
Other fixes can be attempted, for example swapping the 2 functions around so that they do not interfiere with each other, or modifying the API so that it takes the tag position instead of its id as a parameter

File: website/client/js/services/userServices.js [hunk 1]
```diff
@@ -319,8 +319,9 @@ angular.module('habitrpg')
         },
 
         sortTag: function (data) {
+          let fromId = user.tags[data.query.from].id;
```
Comment (crookedneighbor) [inline website/client/js/services/userServices.js]: This should be `var`

**Comment by crookedneighbor** [comment]
Looks good other than my one comment. Great investigation!

**Comment by shervinmathieu** [comment]
Done.

**Comment by crookedneighbor** [comment]
Good work. I've notated this toward your next tier!
