### PR TITLE
Fix keyboard inaccessible accordion in guild/party page fixes #12653

### LINKED ISSUE #12653: Accordion on guild/party page is inaccessible to keyboard navigation
Opening as advised in discussion for issue #11067

The accordion menu at the right hand side of the guild and party page uses clickable divs instead of buttons and cannot be accessed via keyboard navigation.

### PR DESCRIPTION
**Pull request by J-Sanderson**
# Fixes #12653

### Changes
The accordion menu on the right hand side of the guild/party page uses clickable divs to open and close items and is inaccessible to keyboard navigation. Replaced the divs with buttons and converted the nested divs holding the svg icons to spans, and styled to appear the same as before.

----
UUID: cbeeb477-d5db-4efd-8f0b-68201870482b

### CODE REVIEW

File: website/client/src/components/sidebarSection.vue [hunk 1]
```diff
@@ -22,21 +22,21 @@
           :target="tooltipId"
         />
       </div>
-      <div
+      <button
```
Comment (paglias) [inline website/client/src/components/sidebarSection.vue]: Looks like focused buttons get an outline 
Schermata 2020-10-10 alle 10 59 12
Schermata 2020-10-10 alle 10 59 51

I'm wondering, given that browsers might apply their own styles to standard buttons if it would be better to use a div with `aria-role="button"`

@negue do you feel like this should be extracted into its own component?

Comment (negue) [reply website/client/src/components/sidebarSection.vue]: div with `aria-role` should be fine for that.

And yes since this button already has 2 different icons and a custom style it really waits to be its own component 😁

Comment (J-Sanderson) [reply website/client/src/components/sidebarSection.vue]: I can set that up. Any naming conventions etc I should be aware of?

Comment (J-Sanderson) [reply website/client/src/components/sidebarSection.vue]: Update: I've set it to a div but it still has the focus ring. I can get rid of it, but will still need to give it some sort of focus style for accessibility. What would work for you?

Comment (paglias) [reply website/client/src/components/sidebarSection.vue]: @J-Sanderson the black ring as shown in my screenshot is fine, what i wanted to remove was the white outer ring

Comment (J-Sanderson) [reply website/client/src/components/sidebarSection.vue]: How does this look?

Screenshot from 2020-10-12 15-40-16

Comment (paglias) [reply website/client/src/components/sidebarSection.vue]: cc @Tressley

Comment (Tressley) [reply website/client/src/components/sidebarSection.vue]: This should be using focus states similar to the most recent Accessibility updates to the tasks page.

Comment (paglias) [reply website/client/src/components/sidebarSection.vue]: purple borders? the styles that you see in the screenshot are from the browser itself and they're used everywhere we haven't customized them like the tasks page
Schermata 2020-10-13 alle 09 59 11

Comment (Tressley) [reply website/client/src/components/sidebarSection.vue]: @paglias -- Ah, I could've been more clear in my initial reply. Yes, purple. Similar to the newest accessibility updates that were completed on the tasks controls.

Comment (J-Sanderson) [reply website/client/src/components/sidebarSection.vue]: Thanks for the clarification!

**Comment by paglias** [comment]
@J-Sanderson sorry for the delay, the PR is looking good, noted towards your 2nd tier
